### ISSUE TITLE
Support for iOS and Android

### ISSUE THREAD

**Issue by paulocoutinhox** [thorvg/thorvg#1167]
Hi,

It has support for iOS and Android?

Thanks.

**Comment by hermet** [comment]
@paulo-coutinho Hi, No, the build script is not prepared neither case yet. However it's written in pure C++, no pkg dependency, I think it would be a time consuming problem... wish somebody help for this.

**Comment by fire** [comment]
As far as I know Godot which uses Thorvg in the master branch compiles for apple devices and I think is working on support for Android. Not sure.

**Comment by hermet** [comment]
finished for MacOS,
working on Andorid.

**Comment by hermet** [comment]
done iOS 
https://github.com/thorvg/thorvg/pull/1681

**Comment by hermet** [comment]
done Android 
https://github.com/thorvg/thorvg/pull/1692
