### ISSUE TITLE
should the symbol transformation matrix be applied to the use element?

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#1193]
the svg sample looks differently in some svg viewers. 
it has to be checked (in svg specs) whether the result from tvg are the correct ones.

https://github.com/Samsung/thorvg/pull/1184#pullrequestreview-886748252

```
<svg viewBox="0 0 80 20" xmlns="http://www.w3.org/2000/svg">

  <symbol id="myDot" width="10" height="6" viewBox="2 -1 6 6"  overflow="visible"  transform="matrix(2 3 0 1 3 -10)" preserveAspectRatio="none">
    <g transform="matrix(2 0 0 0.6 3 -16)">
        <circle cx="1" cy="2" r="3" transform="matrix(1 0 0 3 3 -6)"/>
    </g>
  </symbol>

  <path d="M0,10 h80 M10,0 v20 M25,0 v20 M40,0 v20 M55,0 v20 M70,0 v20" fill="none" stroke="pink" />

  <use href="#myDot" x="0" y="0" style="opacity:0.8" transform="matrix(0.3 1.1 -2 0.4 13 -7)"/>                                                 
  <use href="#myDot" x="13" y="0" style="opacity:0.6" />
</svg>
```

**Comment by hermet** [comment]
tvg:
![image](https://user-images.githubusercontent.com/3711518/230288013-0a7e3e25-f447-4f35-bc95-09d5239f87e4.png)

chrome & edge:
![image](https://user-images.githubusercontent.com/3711518/230288082-8915780b-9c30-4f57-80bc-43d11214f3da.png)

**Comment by mgrudzinska** [comment]
edited version of svg:
```
<svg viewBox="0 -40 80 80" xmlns="http://www.w3.org/2000/svg">

  <symbol id="myDot" width="10" height="6" viewBox="2 -1 6 6"  overflow="visible"  transform="matrix(2 3 0 1 3 -10)" preserveAspectRatio="none">
    <g transform="matrix(2 0 0 0.6 3 -16)">
        <circle cx="1" cy="2" r="3" transform="matrix(1 0 0 3 3 -6)"/>
    </g>
  </symbol>

  <path d="M0,10 h80 M10,0 v20 M25,0 v20 M40,0 v20 M55,0 v20 M70,0 v20" fill="none" stroke="pink" />

  <use href="#myDot" x="0" y="0" style="opacity:0.8" transform="matrix(0.3 1.1 -2 0.4 13 -7)"/>                                                 
  <use href="#myDot" x="13" y="0" style="opacity:0.6" />
</svg>
```

firefox & tvg:
<img width="621" alt="Zrzut ekranu 2023-04-7 o 02 40 06" src="https://user-images.githubusercontent.com/67589014/230517828-155904fd-5606-433b-be4b-37c0cbcd0590.png">

chrome:
<img width="699" alt="Zrzut ekranu 2023-04-7 o 02 41 33" src="https://user-images.githubusercontent.com/67589014/230517922-f67887d9-96d1-4454-bb4f-26e2dacc76fe.png">

safari:
<img width="699" alt="Zrzut ekranu 2023-04-7 o 02 42 01" src="https://user-images.githubusercontent.com/67589014/230517987-e9342c14-5be7-457b-90e8-e2cbedf64aed.png">

in my opinion it's not a bug. I tried to research this subject, but it was long ago and I didn;t came to any conclusion

**Comment by hermet** [comment]
How about we close it? We have hundreds of tasks prioritized to handle. I think we don't need to waste our time for this.
