### ISSUE TITLE
Feature request: Remove Paint from Canvas

### ISSUE THREAD

**Issue by projectitis** [thorvg/thorvg#1203]
Feature request:

It is possible to update a specific Paint object on the canvas using `canvas->update(paint);`.
I would also like to be able to remove a Paint object from the canvas. For example `canvas->remove(paint);`.

It would be great if this was possible!

**Comment by projectitis** [comment]
If you think this issue should be included, I don't mind working on it?

**Comment by hermet** [comment]
@projectitis You mean you'd like to contribute it?

**Comment by projectitis** [comment]
Yes. 

I have just completed it. Am testing that it works correctly, and will then create PR and you can determine if you'd like it included or not (or other changes).

**Comment by hermet** [comment]
@projectitis thanks for your contribution :) currently I'm working for tvg 0.8 release, new features can be considered after it. I will review it after the release.
