### ISSUE TITLE
Join lines attribute misbehaviour

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#121]
Drawing dashed strokes for various join lines attributes erratically (on corners).

![dash_cap_join](https://user-images.githubusercontent.com/67589014/97369175-a95fc700-18ac-11eb-954b-40bd297f9f62.PNG)

**Comment by hermet** [comment]
![스크린샷 2023-10-05 010343](https://github.com/thorvg/thorvg/assets/3711518/4fd40191-fdaa-449a-bccb-3fa8c180f971)
