### ISSUE TITLE
is there a need for a Direct3d engine ?

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1232]
There is an OpenGL engine, but OpenGL support on Windows is not great. Is there a need for a Direct3D11 engine for ThorVG ?

**Comment by projectitis** [comment]
Hi @vtorri. This is just my opinion - 

Like @hermet said, TVG would only require very basic features of any graphics API (whether that is OpenGL or Direct3D). I believe that windows support for OpenGL is very capable of providing that.  OpenGL is also supported on more platforms than Direct3D is.

It makes sense to get OpenGL working first, and then maybe in the future, a Direct3D version based on that. It's likely quite simple to support D3D once OpenGL is working properly.

So my answer would be, yes, for the broadest support possible for TVG it makes sense to support D3D in the future, but not yet :)

**Comment by vtorri** [comment]
@hermet @projectitis  ok. Though for your information, here is the status of display on Windows nowadays:
 * Since Windows 7, GDI is not hardware accelerated. It can do vector graphics.
 * Direct3D 10, 11 and 12 (the latter being the equivalent of Vulkan), hardware accelerated.
 * GDI has been replaced with Direct2D, which is actually Direct3D with a  set of shaders for doing 2D. It's mainly for geometric shapes and text through DirectWrite. It can do vector graphics
 * OpenGL 1.1.
 * for OpenGL > 1.1, or EGL or GL ES,  you have to compile Angle (arg, the horror !), and there is no more Angle binaries for Windows anymore. See [this link](https://docs.microsoft.com/en-us/windows/win32/opengl/opengl) for the status of OpenGL on Windows. Microsoft has decided to favour its D3D technology over OpenGL.

Example, if I pass on Windows -Dengines='sw','gl', I get:

```
src/lib/gl_engine/meson.build:22:0: ERROR: C++ shared or static library 'EGL' not found
```

But I understand that you have other things to focus on and I agree that once OpenGL renderer is done, the D3D one would not be difficult. So maybe later. If you don't mind, may I keep this issue open ?

**Comment by hermet** [comment]
@vtorri thanks for info. sure. You can keep this issue open.  btw, the latest opengl version is 4.x (gles 3.x). opengl 1.x is too old version thesedays?

**Comment by vtorri** [comment]
@hermet opengl was released in 1995, so yes it's far too old

**Comment by hermet** [comment]
No idea to support this.
