### ISSUE TITLE
about TVG_EXPORT and Windows

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1234]
Hello

about TVG_EXPORT:
 * it should be available on Windows for both Microsoft compiler and mingw, so line 21 of thorvg.h : ` #if defined(_WIN32) && !defined(__clang__)`
 * I've not tested yet but I think that clang support __declspec
 * enum class are a type and should not be exported with TVG_EXPORT
 * when TVG_BUILD is not set, and no static lib is created, TVG_EXPORT should be set to __declspec(dllimport)

**Comment by hermet** [comment]
@vtorri thanks. will check it.

p.s) it would be more helpful if you send patches directly.

**Comment by vtorri** [comment]
I can send a PR for enum classes if you agree. I don't know the status of this on linux, but I think it's the same than on Windows: a type, even an enum, is not a symbol.

**Comment by vtorri** [comment]
actually; the difficult part is managing the static build on Windows.

Btw, fo me,static build on Windows is not a good idea.

**Comment by hermet** [comment]
> num classes

Sure, you can go onto this if you think it's necessary.

**Comment by hermet** [comment]
> I can send a PR for enum classes if you agree. I don't know the status of this on linux, but I think it's the same than on Windows: a type, even an enum, is not a symbol.

@vtorri Sure, you can go on this if you think it's necessary.
