### ISSUE TITLE
unifying svg2png and svg2tvg

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1250]
what about unifying the 2 tools into a program ? for example tvg-convert ? A bit like librsvg convert tool. The reasons behind this proposal are
 * unifying the code style (C++ classes of svg2png vs C functions of svg2tvg)
 * factorize the code (some parts are the same)

**Comment by hermet** [comment]
vg2tvg

**Comment by hermet** [comment]
I think we can add png_saver in tvg lib first, then we can unify the tools ?

**Comment by vtorri** [comment]
probably, i've not looked in details right now.
