### ISSUE TITLE
unit tests: failures when loaders/savers are not enabled

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1251]
I've tested the unit tests (on Windows) and I have remarked that png (or jpeg, or etc..) tests are failing when png loader is not enabled. Which seems normal.

But if the loaders are not mandatory, then don't you think that the corresponding tests should be disabled ?

On Windows, if I enable all the loaders and savers, all the tests are passing, except that the program is returning a strange value, hence `ninja test` is failing. There is not a lot of details from meson logs :(

**Comment by hermet** [comment]
hopefully this has been fixed by https://github.com/thorvg/thorvg/pull/1348
