### ISSUE TITLE
`svg2png` should have option to choose where create png file

### ISSUE THREAD

**Issue by qarmin** [thorvg/thorvg#1254]
`svg2png` only can take as arguments input files, but there is no way to choose where png files will be created.
For now tool for `/home/a.svg` create without any question file `/home/a.png`

**Comment by vtorri** [comment]
might also related to #1250 ? so all the tools behave similarly

**Comment by hermet** [comment]
@qarmin  so you'd like to  use:
```svg2png  input_folder/*    output_folder``` 
is it right?

**Comment by qarmin** [comment]
Something like that,
Usually I use only one file at time
