### ISSUE TITLE
Supports the user to find the element's ID of SVG 

### ISSUE THREAD

**Issue by JSUYA** [thorvg/thorvg#1276]
We support finding `Paint` created via SVG using `Accessor`.
However, there is no way to check which of the elements declared by paint in svg.

In addition to `identifier()`, we can add `tag` or `id` of string type to `Paint` and add it for user to set and get.
Or we can add a way to provide `id` list for svg or tvg in picture.

ex svg)
```
<svg id="svg1" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <circle id = "1" r="32" cx="35" cy="65" fill="#F00" opacity="0.5"/>
  <circle id = "2" r="32" cx="65" cy="65" fill="#0F0" opacity="0.5"/>
  <circle id = "3" r="32" cx="50" cy="35" fill="#00F" opacity="0.5"/>
</svg>
```

**Comment by hermet** [comment]
tvg paint hierarchy won't be exactly identical with svg's data structure.. seems quite fragile. Need to think a concrete solution...

**Comment by hermet** [comment]
Let's close this and raise a issue when the user comes up with a requirement.
