### ISSUE TITLE
Support ABGR colorspace for Images

### ISSUE THREAD

**Issue by bchrescionko** [thorvg/thorvg#1310]
Color of embedded png image in svg file doesn't change color, despite using different color spaces.

Sample svg file:
![test_bluedot](https://user-images.githubusercontent.com/91251249/213503663-dc7e3cf4-f46f-415f-8e70-3a8dbc883f57.svg)

**Comment by mgrudzinska** [comment]
Description:
currently only the ARGB colorspace is supported for ```Image```s. Other channels joining methods should be included (like ABGR).
