### ISSUE TITLE
svg loader: viewbox of svgs without any viewbox information

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#1332]
it's partially regarding the https://github.com/godotengine/godot/issues/72478. 
It has to be confirmed whether svgs without any viewbox and widht/height information should be clipped starting in 0,0 point or the whole image should be visible and no clipping should be applied.

**Comment by mgrudzinska** [comment]
I'm not 100% sure, but I think this is the answer : https://www.w3.org/TR/SVG2/geometry.html#XProperty
the default value of x and y attributes is zero. I don't see any reason why this should be changed in case no viewbox and width/height information is given in the svg file.

**Comment by capnm** [comment]
I think, at least from the user's point of view, it should be handled like _auto_, that is, treated as a 100% image size.
https://www.w3.org/TR/SVG2/geometry.html#Sizing

**Comment by mgrudzinska** [comment]
result for now (master + #1344)

```
<svg>
    <path stroke-width="100" stroke="red" fill="green" d="M-50 100 v 550 h 600 Z M 600 -50 h -600 v 500 Z"/>
</svg>
```
<img width="324" alt="Zrzut ekranu 2023-04-2 o 14 24 51" src="https://user-images.githubusercontent.com/67589014/229352708-dc8be839-1b0c-4d30-ab13-ea1b8d09c5e7.png">


as you can see the image is cut, so that it starts in 0,0. That's the whole image:

<img width="375" alt="Zrzut ekranu 2023-04-2 o 14 31 14" src="https://user-images.githubusercontent.com/67589014/229352981-3d2dd253-9548-4966-b718-cea45d15e0e0.png">

@capnm as I asked in one of the Godot issues - do you think that the whole image should be visible? these are very specific cases, I'm not sure how often do they appear and what is the expected result from the user perspective...

**Comment by capnm** [comment]
Ah sorry, now I understand what you meant... The cut at 0,0 unfortunately makes most of these images unusable. The main problem is the thickness of a path touching the 0,0 axes, you can only see the half of the thickness. You can take a look at the svg's in https://kenney.nl/assets/pattern-pack-2 for example.

![grafik](https://user-images.githubusercontent.com/4047289/229371853-3e8628b5-e498-4b80-bb87-76fda4fa9d1a.png)

**Comment by mgrudzinska** [comment]
@hermet @junsu could you please comment?
I'm ok with changing #1344 in such a way that the whole image is drawn for svg without viewbox and width/height information. In the current version (master and also current version of #1344) x=y=0 is now enforced. [That](https://www.w3.org/TR/SVG2/geometry.html#XProperty) was the arg I used for the current approach, but I'm really not sure whether this arg applies to this situation. 

Below examples from https://github.com/godotengine/godot/issues/72478:

result when we force x=y=0:
<img width="700" alt="Zrzut ekranu 2023-04-3 o 00 30 22" src="https://user-images.githubusercontent.com/67589014/229382870-7912deb9-2eda-4a5b-9e31-c548abee4430.png">

what guys from godot expect (I made a comment in #1344 what has to be removed to achieve this result):
<img width="700" alt="Zrzut ekranu 2023-04-3 o 00 10 12" src="https://user-images.githubusercontent.com/67589014/229382885-8000ff19-ed0e-4ff5-a1cc-40079819dfa7.png">

**Comment by capnm** [comment]
![image](https://user-images.githubusercontent.com/4047289/229493869-53624ccf-498a-4ce6-ba72-cd06d4804c98.png)
:+1:
