### ISSUE TITLE
Bug in SVG path stroke drawing causes horns to appear

### ISSUE THREAD

**Issue by AlfishSoftware** [thorvg/thorvg#1336]
This SVG renders incorrectly:
```svg
<svg id="svg" width="64" height="64" xmlns="http://www.w3.org/2000/svg" viewBox="320 192 64 64"><path d="m 365.51212,202.55632 C 362.29764,202.26797 360.28835,203.80976 360,206 l -2,16 v -18 c 0,-2.20914 -1.79086,-4 -4,-4 -2.20914,0 -4,1.79086 -4,4 v 18 l -2,-16 c -0.28835,-2.19024 -2.29765,-3.73203 -4.48788,-3.44368 l -10 30 h 40 z" fill="red" stroke="blue" stroke-linejoin="round" stroke-width="4"/></svg>
```
It should render like this (works fine in browser, Ubuntu Image Viewer and in other tools like NanoSVG):
![thor-breaker](https://user-images.githubusercontent.com/101953341/227435896-b04d50c5-32c9-4028-840f-8e81c5df24bf.svg)
But in ThorVG it's buggy. This is from ThorVG Viewer:
![image](https://user-images.githubusercontent.com/101953341/227434703-1ada0813-c40a-424e-bf65-fc28f9e2ba28.png)
Notice the creepy evil horns of despair.
It's consistently appearing in all my shapes with this particular exact curve. Changing `stroke-linejoin` or `stroke-width` has no effect on the bug, so it must be caused by something in the path calculations. Perhaps some division by zero or similar? Or maybe it's drawing strokes using circle slices for some reason, with a distant center and incorrect fill? No idea.

**Comment by JSUYA** [comment]
Hi @hermet 
```cpp
    auto shape1 = tvg::Shape::gen();

    //Appends Paths
    shape1->moveTo(200,200 );
    shape1->lineTo(200,400);
    shape1->lineTo(200+30,200);

    shape1->close();
    shape1->fill(0, 0, 255, 255);
    shape1->stroke(40);
    shape1->stroke(255, 0, 0, 255);;
    //shape1->stroke(tvg::StrokeJoin::Round);
    if (canvas->push(move(shape1)) != tvg::Result::Success) return;

    auto shape2 = tvg::Shape::gen();

    //Appends Paths
    shape2->moveTo(40,20 );
    shape2->lineTo(40,40);
    shape2->lineTo(40+3,20);

    shape2->close();
    shape2->fill(0, 0, 255, 255);
    shape2->stroke(4);
    shape2->stroke(255, 0, 0, 255);;
    //shape2->stroke(tvg::StrokeJoin::Round);
    shape2->transform({10,0,0,0,10,0,0,0,10});
    if (canvas->push(move(shape2)) != tvg::Result::Success) return;
```

This happens when the edges of the scaled up shape are very sharp.

<img src="https://github.com/JSUYA/jsuya.github.io/blob/master/tvg_sharp.png?raw=true">

**Comment by mgrudzinska** [comment]
@hermet the intersect being true seems to be a problem:
https://github.com/mgrudzinska/thorvg/commit/ef569b3bd4aea5501b54a11454b77254d9dd7225

from the tvgSwStroke.cpp: the else part of this code is problematic:
```
    if (!intersect) {
        delta = {static_cast<SwCoord>(stroke.width), 0};
        mathRotate(delta, stroke.angleOut + rotate);
        SCALE(stroke, delta);
        delta += stroke.center;
        border->movable = false;
    } else {  //THIS PART SEEMS TO BE A PROBLEM
        //compute median angle
        auto phi = stroke.angleIn + theta;
        auto thcos = mathCos(theta);
        delta = {static_cast<SwCoord>(mathDivide(stroke.width, thcos)), 0};
        mathRotate(delta, phi + rotate);
        SCALE(stroke, delta);
        delta += stroke.center;
    }
```

I didn't prepare a pr since I don't fully understand what was the idea behind this part of the code and maybe removing it is not the best solution. 
Could you please explain? it may be useful for me to understand it in the future

**Comment by hermet** [comment]
Thank you for sharing. This is a part of my history that is quite old, so I'll need to review it thoroughly. I plan to revisit it in a couple of days.

**Comment by mgrudzinska** [comment]
maybe connected with #1341 or #954

**Comment by mgrudzinska** [comment]
maybe connected with #1341 (no transformation is used) or #954

**Comment by hermet** [comment]
The root cause is the given stroke width value hasn't been scaled by its transform-xy while all coordinates have.
