### ISSUE TITLE
Unsupported attribute: paint-order

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#1340]
```
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400" >
<path style="fill:#4140ff;stroke:#ff00ff;stroke-width:19;paint-order:markers stroke fill" d="m 100,100 h 200 v 200 z "/>
</svg>
```

found [here](https://github.com/godotengine/godot/pull/75508#pullrequestreview-1366082740)

**Comment by JSUYA** [comment]
I think, we can change the paint order by extracting the stroke and fill raster code of SwRenderer::renderShape() as each function and changing the order in Shape::Impl::render(). it seems that Shape's API needs to be added for this. (for use in the loader)
This is not likely to be a commonly used API. (we will probably have to use BETA_API.)
Any good idea?

**Comment by mgrudzinska** [comment]
@JSUYA fyi #1346 (still draft - I need to refactor a bit)
this api will be more useful after we implement markers :)

**Comment by hermet** [comment]
fyi, Marker is out of current thorvg feature. it's neither out of SVG tiny spec.

**Comment by mgrudzinska** [comment]
solved in https://github.com/thorvg/thorvg/pull/1371
