### ISSUE TITLE
Enhance logging feature

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1351]
1. If TVG could define colors for the log message types, it would be easier to read and distinguish them.
2. Printing the log source[file/line] will provide an intuitive way to identify the issue being pointed to.

**Comment by mgrudzinska** [comment]
@hermet - like this #1358?

**Comment by hermet** [comment]
@mgrudzinska yeah. guess so. good job.

**Comment by hermet** [comment]
@mgrudzinska right now, i'm closing this. if you think warning type is necessary, later you can suggest it.

**Comment by JSUYA** [comment]
log has improved a lot!!
A small wish is to put a small symbol in front of the log.
log -> [L] . Error -> [E], (warning(?) -> [W] , info (?)-> [I])
This is a log message from another project I'm involved in.
<img src="https://github.com/JSUYA/jsuya.github.io/blob/master/log_example.png?raw=true"/>
how about this?

**Comment by hermet** [comment]
We've experienced this with EFL logs as well.

As the result, I'd like to make the prefix simplify and let users focus on the REAL context because too long log message bothers to focus on the context. Even I'd like to remove the filepath(../src/lib) since we already have the domain name in the head. (or vice versa) Long messages bothers readers to read them specially when the terminal width is not enough large. 

So... Maybe. but in my opinion, people could notice the message type by color. it's just 2 types, quite simple.

**Comment by hermet** [comment]
Come to think of it, the tag might be useful when user filters the log data.

**Comment by mgrudzinska** [comment]
> Even I'd like to remove the filepath(../src/lib) since we already have the domain name in the head. (or vice versa)
I don;t like these long paths as well, but I spoke with a few other programmers and they said, that a good log contains a path, so... :)

**Comment by hermet** [comment]
@mgrudzinska We need logical thinking and sufficient experience in our discussions. Unfortunately, we have no idea about the other programmers except you.
