### ISSUE TITLE
[info] EFL dependencies on Windows

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1354]
Hello

I have released the EFL dependencies on Windows today: https://github.com/vtorri/ewpi/releases

there is an NSIS installer (created on Linux, so without virus afaik)

I've successfully built the EFL with them. I'll soon release an NSIS installer for the EFL themselves

**Comment by hermet** [comment]
@vtorri thanks for info. Could you please share it in our community discussion (https://discord.com/invite/n25xj6J6HM) instead of the issue pages? :-)

**Comment by vtorri** [comment]
@hermet i thik it's done

**Comment by hermet** [comment]
@vtorri thanks!
