### ISSUE TITLE
Svg2png create files with wrong alignment

### ISSUE THREAD

**Issue by qarmin** [thorvg/thorvg#1368]
ThorVg version - 08b833b5bb8d94366a3feacd0b781531171cf933

File browser - rsvg png - thorvg png

![Screenshot from 2023-04-16 13-27-17](https://user-images.githubusercontent.com/41945903/232306929-cf609460-e31f-4dfd-823b-47799dd78180.png)

[BrokenSVG.zip](https://github.com/thorvg/thorvg/files/11242118/BrokenSVG.zip)

**Comment by hermet** [comment]
@qarmin any reason you mentioned this ?https://github.com/thorvg/thorvg/commit/08b833b5bb8d94366a3feacd0b781531171cf933

**Comment by qarmin** [comment]
1. I used this version of ThorVg
2. Looks like regression, I don't remember similar behavior before. Will try to check if worked well with older versions

**Comment by qarmin** [comment]
Bisect shows that this is regession from d60a7bec7e5af32ecee45dfd26f7612b94b37088 CC @mgrudzinska 
```
commit d60a7bec7e5af32ecee45dfd26f7612b94b37088 (refs/bisect/bad)
Author: Mira Grudzinska <veleveta@gmail.com>
Date:   Sat Apr 1 17:14:04 2023 +0200

    svg_loader: fixing svgs without viewbox attr
    
    For svgs without any viewbox and width/height
    whole image is drawn. Before it was forced
    to set x=y=0.
```

**Comment by mgrudzinska** [comment]
> Bisect shows that this is regession from [d60a7be](https://github.com/thorvg/thorvg/commit/d60a7bec7e5af32ecee45dfd26f7612b94b37088) CC @mgrudzinska

I knew it was my fault.... xd
I'll taka care of that asap (try today in the evening)

**Comment by mgrudzinska** [comment]
it occurred because I tried to make [the godot ](https://github.com/thorvg/thorvg/issues/1332#issuecomment-1493457351) work.
now it should work in general.

**Comment by hermet** [comment]
@qarmin we were appreciated if you confirm the fix.

**Comment by qarmin** [comment]
Now this files looks identical like in rsvg
