### ISSUE TITLE
Drop CAPI binding in the next ThorVG?

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1374]
Should we remove the CAPI binding? While it was introduced for Tizen EFL, it's currently not being maintained by anyone.

**Comment by JSUYA** [comment]
However, tizen is still using these APIs, and there seems to be other projects using thorvg_capi, although there is only one. (https://github.com/zhad3/bindbc-thorvg)
Unmanagement is problematic, but I against erase it.
How about versioning? We can show that the operation of the api is not guaranteed through a note,

**Comment by mgrudzinska** [comment]
if we decide to keep them, I can add the missing apis and test coverage. and take care of it in the future

**Comment by hermet** [comment]
@JSUYA https://build.tizen.org/package/show/Tizen:Unified/thorvg?rev=33
Could you please confirm what version of thorvg tizen8 uses?

If they do not upgrade Thorvg, it does not make sense for our new Thorvg to keep CapI for Tizen. Instead, Tizen could continue using Thorvg 0.x.

**Comment by fire** [comment]
Will there be a replacement c api?

**Comment by hermet** [comment]
@fire Only EFL in Tizen uses thorvg c-binding and Tizen is killing it. Main graphics stack(Dali) in Tizen uses c++ version.

**Comment by fire** [comment]
Does Thorvg plan on external bindings from rust, zig, or elixir? These and other lanhusges only have cffis.

**Comment by hermet** [comment]
@fire I don't know about zir or elixir much but Rust lang is the quite popluar thesedays. I'd like to support it if we have a manpower. That's why we need to trim unnecessary features. :)

**Comment by fire** [comment]
I believe rust requires a c ffi https://doc.rust-lang.org/rust-by-example/std_misc/ffi.html

**Comment by JSUYA** [comment]
> @JSUYA https://build.tizen.org/package/show/Tizen:6.5:Unified:ref:20230407.1/thorvg Could you please confirm what version of thorvg tizen8 uses?

https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/latest/repos/standard/packages/armv7l/thorvg-0.8.10-1.armv7l.rpm
The recently released Tizen 7.0 uses thorvg-0.6.7(tizenvg), but version updates have been ongoing since then.
(There has been no update for the past year, but it has been recently.  v0.8.10)

> If they do not upgrade Thorvg, it does not make sense for our new Thorvg to keep CapI for Tizen. Instead, Tizen could continue using Thorvg 0.x.

As you said, they were killed it, so they are no longer of any use. hahaha.. Dali/NUI use c++ apis.
But from another point of view, CAPI binding is our asset. Do we really need to delete it? I think it will be useful.
Since we are oriented towards light weight, it will be useful in a C language based environment.

**Comment by mihashco** [comment]
Hi. The version in Tizen has been bumped up to the latest version.

**Comment by hermet** [comment]
> As you said, they were killed it, so they are no longer of any use. hahaha.. Dali/NUI use c++ apis.
> But from another point of view, CAPI binding is our asset. Do we really need to delete it? I think it will be useful.
> Since we are oriented towards light weight, it will be useful in a C language based environment.

I hope so but it's not 0 cost. Unless any practical requirement, we don't need to add it in ThorVG 1. 

> I believe rust requires a c ffi https://doc.rust-lang.org/rust-by-example/std_misc/ffi.html

That is useful when thorvg provides only c binding but If thorvg provides rust binding, it doesn't need to use ffi for thorvg.

**Comment by hermet** [comment]
> Hi. The version in Tizen has been bumped up to the latest version.

@mihashco Hi. Thorvg is planning to upgrade its major version from 0 to 1 and will be trimming unnecessary features. What is your opinion on Tizen if Thorvg 1 drops its C binding?

**Comment by hermet** [comment]
> As you said, they were killed it, so they are no longer of any use. hahaha.. Dali/NUI use c++ apis.
> But from another point of view, CAPI binding is our asset. Do we really need to delete it? I think it will be useful.
> Since we are oriented towards light weight, it will be useful in a C language based environment.

@JSUYA We hope so but it's not zero cost. We need practical requirements or use cases before confirming it.

**Comment by hermet** [comment]
> if we decide to keep them, I can add the missing apis and test coverage. and take care of it in the future

@mgrudzinska  You know, you can do it anytime since c-binding is our official feature in current thorvg. :)

**Comment by mihashco** [comment]
> > Hi. The version in Tizen has been bumped up to the latest version.
> 
> @mihashco Hi. Thorvg is planning to upgrade its major version from 0 to 1 and will be trimming unnecessary features. What is your opinion on Tizen if Thorvg 1 drops its C binding?

Hi. We have to keep capi in tizen fork until it is used in the EFL. If you want to drop capi support we have to write wrapper in separated module to get thorvg engine updates.

**Comment by mgrudzinska** [comment]
@hermet I see only the identifier apis that aren;t present in capi. all other are in beta, so I don;t think that we want to prepare capis for them, especially if capi binding is removed. is it right?

**Comment by hermet** [comment]
@mgrudzinska  It's not mandatory to add BETA apis in bindings but we might need to catch-up the api test. Since we confirmed the CAPIs are useful in Tizen, we'd rather keep it in tvg 1.0

**Comment by hermet** [comment]
So it's still necessary in Tizen. Let's keep it in 1.x
