### ISSUE TITLE
TVG Saver portability issue

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1380]
There seems to be an issue with porting TVG Saver to Windows.

ThorVG Viewer Result:

[2192.svg in the example]
![image](https://user-images.githubusercontent.com/3711518/232975045-91c8bb0d-f561-4063-a05b-07912ba69cb6.png)

[2192.tvg in the example]
![image](https://user-images.githubusercontent.com/3711518/232975012-cee5a8a3-990a-477f-a6e7-aae9298516ca.png)

Like the above, all other tvg results are not working correctly.

Tested svg2tvg on the Windows.

**Comment by vtorri** [comment]
in tvg saver, there are 2 calls of _fopen(), lines 173 and 196:

    auto fp = _fopen(path.c_str(), "w+");

you should use the binary mode instead of the text mode

**Comment by mgrudzinska** [comment]
@vtorri yes, you were right with the binary mode on windows. this was responsible for the bunch of error, like 'corrupted tvg file', segfaults etc. thx for that

regarding multi call of the fopen - there are two occurrences, but only one is called. either flushTo is called and the saveEncoding is left before the file is opened inside it, or flushTo isn't called and saveEncoding opens the file, writes to it and closes it.

regarding preprocessor conditions:
it was introduced in https://github.com/thorvg/thorvg/commit/282b9288ab3763813c7bda953a1af9ee1d3b83e3, need to investigate...

**Comment by hermet** [comment]
Confirmed this issue was fixed. 
+ The build was successful with MSVC when I removed that preprocessor. Need to verify on MacOS.
