### ISSUE TITLE
tvg saver: strange preprocessor condition

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1401]
line 41: #if defined(_MSC_VER) && defined(__clang__)

shouldn't it be a logical OR ?

**Comment by hermet** [comment]
@vtorri Thanks, we don't need to address code review for each one here. Please comment [here](https://github.com/thorvg/thorvg/issues/1380) or in our chat (Discord). Otherwise, please submit a pull request (PR) :)

**Comment by hermet** [comment]
btw, that code is not used at all and it seems no problems on msvc build.
