### ISSUE TITLE
usage of the long type on Windows

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1402]
the `long` type is used in the code. Note that it behaves differently on Windows vs unix:

 * long is always a 32-bits type on Windows
 * it is 32-bits on 32 bits arch and 64-bit on 64 bits arch on unix

so according to the usage of `long`, it could introduce issues. This type should not be used for portable code.

**Comment by hermet** [comment]
@vtorri Thanks, we don't need to address code review for each one https://github.com/thorvg/thorvg/issues/1380. Please comment here or in our chat (Discord).
Otherwise, please submit a pull request (PR) :)
