### ISSUE TITLE
Support static WebP loader

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1427]
WebP is the compact and optimal image format in the industry. 
It is widely used among platforms and apps these days. Let's prioritize supporting external WebP.

https://chromium.googlesource.com/webm/libwebp/

**Comment by vtorri** [comment]
jpeg-xl is far superior to webp, but less used

**Comment by hermet** [comment]
Some history here:
https://www.roboleary.net/webdev/2023/03/06/next-web-image-format-not-jpegxl.html

**Comment by hermet** [comment]
for static decoder: https://github.com/jacklicn/libwebp
