### ISSUE TITLE
TypeScript Binding Support

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1428]
TS binding is useful for web development environments, including our ThorVG viewer. 
We should consider adding official TS bindings to enhance the usability of our ThorVG viewer and 3rd-party frontend devs.
~An alternative TS binding could be Rust. We need to discuss before proceeding with this task.~

- 1st phase is to provide Lottie Animation Player Package for Web.
- Apply the player in thorvg.viewer

```
- thorvg/web/*
 ```

**Comment by xland** [comment]
Do you mean to integrate an JavaScript engine like QuickJs or JavaScriptCore into Thorvg?

**Comment by hermet** [comment]
Not really,  thorvg webassembly + JS.
