### ISSUE TITLE
Wrong TVG result

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1440]
examples/AA_5.tvg:
![image](https://github.com/thorvg/thorvg/assets/3711518/2fede766-9eba-4393-b253-dafa7373481e)

Normal:
![image](https://github.com/thorvg/thorvg/assets/3711518/bca67fff-fc9f-4a74-b992-0cedfc583369)

**Comment by mgrudzinska** [comment]
#1442 solves some of the problems, not all

**Comment by mgrudzinska** [comment]
now #1442 should solve all the problems

screen of the tvg file:
<img width="355" alt="Zrzut ekranu 2023-05-10 o 18 49 39" src="https://github.com/thorvg/thorvg/assets/67589014/002bd144-eba1-478d-9962-f0c5ba752fa3">

**Comment by JSUYA** [comment]
> eh.. Still I'm reproduciable. Did you check TVG? (Not SVG) How about the result by ThorVG Viewer?

Oh sorry my mistake. I checked with SVG
