### ISSUE TITLE
Incorrectly renegered SVG files (from Godot)

### ISSUE THREAD

**Issue by JonnyTech** [thorvg/thorvg#1451]
Not sure if this should be linked to #1255 but here are a couple of broken svg files that I have found - this is linked from https://github.com/godotengine/godot/issues/77094

https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/eu.svg
https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/us.svg

**Comment by clemens-tolboom** [comment]
# IN
![EUR](https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/eu.svg)
# OUT
![d](https://user-images.githubusercontent.com/3584732/238156906-db744227-ab0f-4dac-9af4-b081d007e8dd.png)

**Comment by JSUYA** [comment]
https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/eu.svg
I've simplified the problem a bit more.
`<use>` declared in `<defs>` is not being drawn. @mgrudzinska Could you please check this?
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
  <defs>
    <g id="d">
        <path id="a" d="m10 10 h10 v10 h-10 z"/>
        <use fill="#f00" xlink:href="#a" y="-15" />
    </g>
  </defs>
    <use fill="#fc0" xlink:href="#d" width="100%" height="100%" y="+15"/>
</svg>
```

https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/us.svg
@hermet @mgrudzinska `<marker-mid>` is used in this file.
https://www.w3.org/TR/SVG2/painting.html#VertexMarkerProperties
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-mid
We need discussion about supporting features related to markers.

**Comment by mgrudzinska** [comment]
after both, the #1452 and #1453 are applied the eu flag is correct. the us flag looks better, but since markers are used, only one star is visible. 

implementing markers sounds fun for me, but I don't know how much appreciated it will be, it's not commonly used feature....

**Comment by JonnyTech** [comment]
Thank you all - are you happy for me to close this issue?

**Comment by capnm** [comment]
Please have some patience, the developers ask you or close the issue after a commit itself. 
(us.svg: Unsupported elements used [Elements: marker])

**Comment by clemens-tolboom** [comment]
FWIW https://www.google.com/search?q=svg+%22marker-mid%22 gives 7K results.

I was interested in this US flag problem.

So the US flag is (edited) drawing line segments where each `marker-mid` is a star.

```xml
<svg xmlns="http://www.w3.org/2000/svg" id="flag-icons-us" viewBox="0 0 640 480">
  <path fill="#bd3d44" d="M0 0h640v480H0"/>
  <path stroke="#fff" stroke-width="37" d="M0 55.3h640M0 129h640M0 203h640M0 277h640M0 351h640M0 425h640"/>
  <path fill="#192f5d" d="M0 0h364.8v258.5H0"/>
  <marker id="a" markerHeight="30" markerWidth="30">
    <path fill="#fff" d="m14 0 9 27L0 10h28L5 27z"/>
  </marker>
  <path fill="none" marker-mid="url(#a)" d="
m0 0 16 11 h61 61 61 61 60
L47 37  h61 61 60 61
L16 63  h61 61 61 61 60
L47 89  h61 61 60 61
L16 115 h61 61 61 61 60
L47 141 h61 61 60 61
L16 166 h61 61 61 61 60
L47 192 h61 61 60 61
L16 218 h61 61 61 61 60
L0 0"/>
</svg>
```

**Comment by clemens-tolboom** [comment]
There is one file src/examples/images/gallardo.svg with `marker-mid:none;`

**Comment by hermet** [comment]
@clemens-tolboom SVG has a wide range of features, but Thorvg is currently focused on aligning with the SVG Tiny 1.2 specification, which is designed for lightweight devices like mobile devices. However, it's worth noting that Thorvg does not include support for the "marker-mid" property as it is not part of the SVG Tiny 1.2 specification.

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/issues/1460

**Comment by clemens-tolboom** [comment]
Thanks for the blazing fast fixes :)
