### ISSUE TITLE
Support WebGPU raster backend

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1479]
Example working condition:

- [x] Shape
- [x] MultiShapes
- [x] Path
- [x] PathCopy
- [x] Scene
- [x] Transforms
- [x] Accessor
- [x] CustomTransform
- [x] Animation
- [x] Update
- [x] PictureSvg
- [x] DataLoad
- [x] LinearGradient
- [x] RadialGradient
- [x] PictureJpg
- [x] PicturePng
- [x] PictureWebp
- [x] SceneTransform
- [x] GradientTransform
- [x] FillRule
- [x] ImageScaleDown
- [x] ImageScaleUp
- [x] Arc
- [x] StrokeLine
- [x] DirectUpdate
- [x] Text
- [x] Retaining
- [x] Performance
- [x] Stroke
- [x] AnimateMasking
- [x] FillSpread
- [x] InvLumaMasking
- [x] Duplicate
- [ ] Viewport
- [ ] StrokeTrim
- [ ] PictureRaw
- [ ] InvMasking
- [ ] SceneBlending
- [ ] Masking
- [ ] LumaMasking
- [ ] GradientMasking
- [ ] ClipPath
- [ ] LottieExtensions
- [ ] Opacity
- [ ] StrokeMiterLimit
- [ ] MaskingMethods
- [ ] Texmap
- [ ] GradientStroke
- [ ] Blending
- [ ] PictureTvg
- [ ] Svg
- [ ] Tvg
- [ ] Lottie

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/pull/1693

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/wiki/24'-Development-Roadmap

**Comment by hermet** [comment]
@kunitoki Yes, we do now.

**Comment by hermet** [comment]
Currently 32 resources are incomplete support in Lottie examples:
- [ ] 11555.json
- [ ] 27746-joypixels-partying-face-emoji-animation.json
- [ ] 5317-fireworkds.json
- [ ] 5344-honey-sack-hud.json
- [ ] a_mountain.json
- [ ] batman.json
- [ ] driving.json
- [ ] eid_mubarak.json
- [ ] fiery_skull.json
- [ ] fly_in_beaker.json
- [ ] fun_animation.json
- [ ] game_finished.json
- [ ] gradient_background.json
- [ ] growup.json
- [ ] guitar.json
- [ ] hamburger.json
- [ ] hola.json
- [ ] insta_camera.json
- [ ] intelia_logo_animation.json
- [ ] isometric.json
- [ ] like.json
- [ ] masking.json
- [ ] open_envelope.json
- [ ] personal_character.json
- [ ] polystar.json
- [ ] rufo.json
- [ ] seawalk.json
- [ ] skullboy.json
- [ ] starburst.json
- [ ] starts_transparent.json
- [ ] stroke_dash.json
- [ ] threads.json

**Comment by mgrudzinska** [comment]
macos:
AnimateMasking:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 15 40 08" src="https://github.com/thorvg/thorvg/assets/67589014/31800ff3-2fcb-4a62-ae74-a839e1037a43">

DataLoad - check quality 
<img width="400" alt="Zrzut ekranu 2024-06-19 o 15 43 30" src="https://github.com/thorvg/thorvg/assets/67589014/53a3dda5-c7bb-474b-a501-0dc79996471d">

GradientStroke:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 15 48 47" src="https://github.com/thorvg/thorvg/assets/67589014/8b96fde4-a000-4399-be53-97bec9eeb417">

Lottie crashed

LottieExtension crashed

MultiCanvas - "Not Support WebGPU" info

Performance:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 15 59 22" src="https://github.com/thorvg/thorvg/assets/67589014/03e73691-1cb5-4c27-84f0-2b9f212cad71">

PictureRaw:
<img width="400" alt=" " src="https://github.com/thorvg/thorvg/assets/67589014/20b7de58-1ac3-445e-bb22-54cc90c35a3c">

PictureTvg:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 16 03 43" src="https://github.com/thorvg/thorvg/assets/67589014/84590ca4-62fd-4190-b084-aeeab72d5fa7">

SceneBlending:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 16 05 55" src="https://github.com/thorvg/thorvg/assets/67589014/7af43d36-8105-4994-9fb7-b670855f4ff3">

StrokeMitterlimit:
<img width="400" alt="Zrzut ekranu 2024-06-19 o 16 09 26" src="https://github.com/thorvg/thorvg/assets/67589014/3da6745b-5b3f-4a60-8887-36d63e7fcf55">

Svg - hangs

Tvg - hangs



not listed above:
StrokeTrim - doesn't work
Viewport - doesn't work
FillSpread - works

**Comment by hermet** [comment]
Examples Pass Rate: 62%
