### ISSUE TITLE
When closing a path with `z`, the next stroke still applies a linejoin effect

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1487]
After I optimized a lot of Godot's SVGs, which uses this library, one of the simple SVGs broke:

![image](https://github.com/thorvg/thorvg/assets/85438892/31e58212-593d-4224-8bf0-57595ac05358)

`<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2 2h12v12H2zl12 12" fill="none" stroke-width="2" stroke="#ffca5f"/></svg>`

It can be fixed by moving by a zero vector `m0 0` after `z` closes the path.

**Expected behavior:** After the path is closed, linejoin applies only between the closure stroke and the initial stroke.

**Actual behavior:** When the path is closed and another stroke is drawn immediately from the same location, it seems as though linejoin is drawn between the closing stroke and the new stroke, as well as between the initial stroke and the new stroke.

![image](https://github.com/thorvg/thorvg/assets/85438892/2bcec2fb-5520-437d-a104-2bc58274fe97)

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/pull/2118
