### ISSUE TITLE
mention EFL installer on Windows in README

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#1529]
can you please add in https://github.com/thorvg/thorvg#examples the EFL installer on Windows ?

see https://github.com/vtorri/ewpi/releases 

thank you

**Comment by hermet** [comment]
@vtorri thanks, I believe adding windows package to https://www.enlightenment.org/download would be a more reliable option. Are there any potential issues in doing so?

**Comment by vtorri** [comment]
@hermet i don't think that I have the rights to do so. I'll ask raster

**Comment by vtorri** [comment]
@hermet https://download.enlightenment.org/rel/win/efl/

**Comment by hermet** [comment]
@vtorri  https://github.com/thorvg/thorvg/commit/56deda19fd13d2c90b04f1119e372751e6953f8b
