### ISSUE TITLE
Windows build error due to strip option

### ISSUE THREAD

**Issue by rinechran** [thorvg/thorvg#1574]
https://github.com/thorvg/thorvg/blob/052cfea4b1251eb016d83586f81111d289748e85/meson.build#L3C127-L3C132

Using the 'strip=true' option causes errors on Windows. If it's not related to size constraints, I believe it's better to remove it. Alternatively, we can consider adding this option only for the Linux platform. What do you think about that approach?

**Comment by vtorri** [comment]
No problem with that script, using MSYS2 + mingw-w64 (x86_64) :

```bash
#! /bin/bash

export CFLAGS="-g3 -ggdb3 -Og -pipe"
export CXXFLAGS="-g3 -ggdb3 -Og -pipe"

rm -rf builddir

meson setup \
      --prefix=/opt/thor_64 \
      --buildtype=debug \
      --default-library shared \
      -Dvector=false \
      -Dtools=all \
      -Dexamples=true \
      -Dloaders='all' \
      -Dsavers=all \
      -Dbindings=capi \
      -Dlog=true \
      -Dtests=true \
      builddir

ninja -j8 -C builddir
```

**Comment by rinechran** [comment]
There is no big problem with using mingw, but errors occur when building with vs.

Debugging information is stored separately in the form of pdb when built with windows, resulting in an error when using the option.
![image](https://github.com/thorvg/thorvg/assets/15512801/ffbe609f-b894-476e-95d6-72c2329c2c37)

**Comment by hermet** [comment]
So it says it's a meson bug. what version do you use? it's an out of thorvg problem.

It builds successfully on my side.

meson build --backend=vs
![image](https://github.com/thorvg/thorvg/assets/3711518/755b98d3-a381-4b67-a90a-a959a473b4f3)

meson build manually
![image](https://github.com/thorvg/thorvg/assets/3711518/788c6079-1b8b-4cd0-ba0f-b5d0a447cf9f)

**Comment by rinechran** [comment]
![image](https://github.com/thorvg/thorvg/assets/15512801/ec9286d5-c4ed-4a30-8760-b37047aeb4ed)

The meson used in vcpkg is 0.62.1

**Comment by vtorri** [comment]
which version of meson ?

**Comment by vtorri** [comment]
latest meson is 1.2, 0.62.1 is quite old

pip install meson

**Comment by rinechran** [comment]
All right.
