### ISSUE TITLE
Improve Code quality

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1578]
We can observe that CodeFactor detects some points for refactoring to improve code quality. We should consider aiming for at least a score of A. Currently it's A-

https://www.codefactor.io/repository/github/hermet/thorvg

![image](https://github.com/thorvg/thorvg/assets/3711518/71325ee0-7e36-456c-a04f-70abbd40ac12)

**Comment by JSUYA** [comment]
Apart from method's complexity, some of our codes have an ordering dependency on header include. (Transitive inclusions)
The google c++ style guide provides some concepts to solve this problem. 
https://google.github.io/styleguide/cppguide.html#Include_What_You_Use
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

what do you think about it?

**Comment by hermet** [comment]
@JSUYA Conceptually, each file should explicitly include headers if they depend on them. The problem is that somebody might forget to include a header, and it's not easy to detect this omission during the review stage because even reviewers may not notice it when transitive inclusions implicitly hide it. In my case, I'm not overly concerned about this, as any breakage can be promptly detected during testing. We can easily identify the missing header in the necessary file, allowing us to include it at that time.

The only header that truly matters for the transition is the client API header (thorvg.h/thorvg_capi.h) for us.
