### ISSUE TITLE
support stroke dash offset function

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1591]
The "stroke dash offset" feature is commonly used. 
The "stroke()" API might need to have an additional parameter to apply the offset in the drawing from the backend.

Result stroke(const float* dashPattern, uint32_t cnt) noexcept;
-> Result stroke(const float* dashPattern, uint32_t cnt, float offset = 0.0f) noexcept;

**Comment by mgrudzinska** [comment]
```
<svg viewBox="-10 0 50 20" xmlns="http://www.w3.org/2000/svg">
  <!-- No dash array -->
  <line x1="0" y1="1" x2="30" y2="1" stroke="black" />

  <!-- No dash offset -->
  <line x1="0" y1="3" x2="30" y2="3" stroke="black" stroke-dasharray="3.4 1.3 2 0.5" stroke-linecap="butt" />


  <line x1="0" y1="5" x2="30" y2="5" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="1.2" />

  <line x1="0" y1="6.1" x2="30" y2="6.1" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="8.4" />


  <line x1="0" y1="8" x2="30" y2="8" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="4.1" />

  <line x1="0" y1="9.1" x2="30" y2="9.1" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="11.3" />


  <line x1="0" y1="11" x2="30" y2="11" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="5.7" />

  <line x1="0" y1="12.1" x2="30" y2="12.1" stroke="blue"
        stroke-dasharray="3.4 1.3 2 0.5" stroke-dashoffset="12.9" />
</svg>
```

result from tvg after my changes (as expected):
<img width="387" alt="Zrzut ekranu 2023-08-16 o 23 52 36" src="https://github.com/thorvg/thorvg/assets/67589014/53b30b79-8cb7-4ebb-ab01-53ab4ccaa0de">

need to test negative values of offset and will be ready :)

**Comment by hermet** [comment]
Great, I'm looking forward to the result. :-)

**Comment by mgrudzinska** [comment]
@hermet 
changing api like this ``` Result stroke(const float* dashPattern, uint32_t cnt, float offset = 0.0f) noexcept;```
will cause a problem, because we have already ```Result stroke(uint8_t r, uint8_t g, uint8_t b, uint8_t a = 255) noexcept;```

so calling stroke(0, 255, 0) is ambiguous. 
I'm not sure how to solve this... we could remove the def value of ```a``` but I assume that it's a common api, so probably not the best idea. so a new ```Result dashOffset(float offset)``` api?

**Comment by hermet** [comment]
how about -> strokeDash(dashPattern, patternCnt, offset)   ?

**Comment by hermet** [comment]
ok, you already pushed a patch. Reverting alpha value might be better to go for now.
