### ISSUE TITLE
simple svg renders incorrectly

### ISSUE THREAD

**Issue by mieldepoche** [thorvg/thorvg#1593]
```svg
<?xml version="1.0"?>
<svg width="110" height="110" xmlns="http://www.w3.org/2000/svg">
	<path fill-rule="evenodd" fill="#ffffffff" d="M 0 0 L 0 110 110 110 110 0 z M 50 50 L 60 50 60 60 50 60 z " />
	<path fill="none" stroke="#000000ff" stroke-width="8" d="M 46 46 L 60 46 60 60 46 60 z " />
</svg>
```

![cell.svg](https://github.com/thorvg/thorvg/assets/71937306/0eb25266-a2e4-4c73-a1a2-db1744d7943d)

*edit*: after experimenting a bit, it seems the problem is that colors are specified with alpha. Replacing `#ffffffff` with `#ffffff` and so on aboves solves the rendering problem. Still, supporting this may be desirable?

og issue:

- thorvg renders this file incorrectly
- It renders correctly in all but one of the other software I tried (gimp, the image viewing software of my os, literally all web-based svg-checking tools I could find all work) but thorvg fails to draw it correctly (and so do krita for what it's worth).
- I made it myself manually so I guess something could be off, but I couldn't figure it out.

| https://www.thorvg.org/viewer | most other software |
|-|-|
| ![image](https://github.com/thorvg/thorvg/assets/71937306/20a78fc5-1f19-44e0-917f-eccf5ffcaa07) | ![image](https://github.com/thorvg/thorvg/assets/71937306/f75c6d67-e8d8-45de-95c3-a594c26be029) |

**Comment by capnm** [comment]
Don't your experiments ignore the `color` specifications? Please read:
https://svgwg.org/svg2-draft/painting.html#ColorProperty
https://www.w3.org/TR/css-color-3/#color

By violating specs, you can expect the applications to act randomly. E.g. Firefox and Inkscape paint this identically to ThorVG.

**Comment by mieldepoche** [comment]
> If you violate the specifications, you can expect the applications to behave arbitrarily

yep, it took me some time to realize what was wrong, in part because of the widely shared behavior the tools I tested exhibit (which btw firefox (115.0.2) respects on my end :thinking: )

In any case, I feel it's not that important of a feature in the end.
