### ISSUE TITLE
Performance issue on mcu

### ISSUE THREAD

**Issue by xlbao123** [thorvg/thorvg#1619]
I would like to port thorvg to my microcontroller board, which features a Cortex-M33 core and runs FreeRTOS. I've noticed that Thorvg relies on C++14, which isn't very friendly for microcontroller platforms due to its usage of certain C++ features like concurrency-related APIs. Do you happen to know if there are any plans to decouple these codes and transition to an operating system adaptation layer instead?

**Comment by hermet** [comment]
@xlbao123 Hello, I guess it depends on the capacity. Any information about c++ version(or spec), we can consider to replace?

**Comment by hermet** [comment]
@xlbao123 Hello, I believe it depends on the capacity. Do you have any information about the C++ version (or specification) that we could consider replacing?

**Comment by xlbao123** [comment]
@hermet 
I apologize for the delayed response; I only recently started working on this project. I wanted to take a moment to update you on my progress and would greatly appreciate your feedback.

Thanks to the newly added `THORVG_THREAD_SUPPORT `macro, the porting process on my microcontroller didn’t take much time, and it’s running smoothly. However, the performance is quite slow—I’m only getting about 3-4 fps with lottie files. I’ve done some tracing, and I’ve attached the graphs below. I have a few questions and would appreciate your insights:
![1725330104962](https://github.com/user-attachments/assets/2f9ad5b9-f6c7-442f-9dfa-a24760d5b19b)
![1725330158028](https://github.com/user-attachments/assets/235dbdf3-efd0-4380-afcb-b2bf46bd70a2)
![1725330183276](https://github.com/user-attachments/assets/7d599239-c3b7-4446-918d-ce66746239a1)

1. The `update `process takes an very long time. Is this because the rasterization of each frame happens during this stage? I plan to dig deeper into this area and refine the trace data when I have the time.

2. The microcontroller I’m using has a 2D GPU that supports OpenVG Lite features. I’m considering adding support for this GPU in the rendering process. Could you guide me on where to start with this task?

3. My goal is to achieve around 20 fps on the microcontroller. To reach this target, would it be feasible to precompute the `update `step for each frame offline on a PC and generate an intermediate format file, then only perform the `draw `step on the microcontroller?

I would greatly appreciate any additional suggestions you might have.

**Comment by hermet** [comment]
> 1. The `update `process takes an very long time. Is this because the rasterization of each frame happens during this stage? I plan to dig deeper into this area and refine the trace data when I have the time.

Without threading, it will perform some pre-processing for vector outlines in those updates(), and the rasterization should not occur there. I guess it must be here:
![image](https://github.com/user-attachments/assets/467606af-5532-4dd0-8208-c9c1f123c594)

> 2\. The microcontroller I’m using has a 2D GPU that supports OpenVG Lite features. I’m considering adding support for this GPU in the rendering process. Could you guide me on where to start with this task?

I'm surprised that OpenVG is available for you; however, this wouldn't be an easy or cheap task. What about using OpenGL? Is it not available on your system?

> 3\. My goal is to achieve around 20 fps on the microcontroller. To reach this target, would it be feasible to precompute the `update `step for each frame offline on a PC and generate an intermediate format file, then only perform the `draw `step on the microcontroller?

Let's see. We still need to determine whether the slowdown in update() is reasonable or not.

- Are you playing a single animation?
- What version of ThorVG are you using?
- Could you share the JSON resource to confirm how complex the Lottie file is?
- Does your system available Thread?

**Comment by xlbao123** [comment]
> > 2. The microcontroller I’m using has a 2D GPU that supports OpenVG Lite features. I’m considering adding support for this GPU in the rendering process. Could you guide me on where to start with this task?
> 
> I'm surprised that OpenVG is available for you; however, this wouldn't be an easy or cheap task. What about using OpenGL? Is it not available on your system?

Yes, for MCUs, I haven't seen any that support OpenGL. Typically, they have a 2D GPU that supports some openvg features（OpenVG Lite）, such as the STM32U5 or i.MX RT series.

> 
> > 3. My goal is to achieve around 20 fps on the microcontroller. To reach this target, would it be feasible to precompute the `update `step for each frame offline on a PC and generate an intermediate format file, then only perform the `draw `step on the microcontroller?
> 
> Let's see. We still need to determine whether the slowdown in update() is reasonable or not.
> 
> * Are you playing a single animation?
> * What version of ThorVG are you using?
> * Could you share the JSON resource to confirm how complex the Lottie file is?
> * Does your system available Thread?

I used the latest Thorvg code with several Lottie files from the examples folder. I think I need to clarify my hardware environment: it's a Cortex-M33 microcontroller with a 200MHz clock speed, and the PSRAM is also 200MHz. I believe the performance issue is due to the hardware (as a reference, software decoding a 500x500 8-bit PNG image on this microcontroller takes about 30ms). I'm not sure if anyone else has tested on similar hardware, but based on my results, the current performance is understandable.

I measured some trace data; for example, with the file 11555.json, the hotspot functions in the `update `phase are `_decomposeOutline `and `_genDashOutline`, while in the render phase, the hotspot function is the `rasterShape `interface. I think this is reasonable as well. I've uploaded the [trace file](https://github.com/user-attachments/files/16863370/lottie-11555.zip) here if you're interested in taking a look (you can open it with [https://ui.perfetto.dev/](https://ui.perfetto.dev/)).

Lastly, I still want to try to find a solution—are there any plans to support OpenVG (lite) in the future, or to make Thorvg more  easily utilize some hardware renderers to accelerate performance?

**Comment by hermet** [comment]
@xlbao123 Hi,
- How about the performance if playing simple animations? [hourglass.json](https://github.com/user-attachments/files/16884176/hourglass.json) Complex and fancy visuals would not be suitable for those super lowend devices.
- Could you please double-check the attached trace file? It's just a JSON file, and I'd like to see the actual data on the device you have.
- There are no plans for the ThorVG team to add OpenVG support.
- However, ThorVG is open to contributions. You'll find a few backends (`sw_engine`, `gl_engine`, `wg_engine`) in the `src/renderer/` directory. You might consider adding a `vg_engine` and contributing it. You can refer to the `RenderMethod` in `tvgRender.h`, which acts like a Render Hardware Interface (RHI) in ThorVG. You could implement OpenVG support for those interfaces

![image](https://github.com/user-attachments/assets/b8bd151d-fc12-4399-aaa8-a9b546057d6a)

- The best reference could be `SwRenderer inheriting RenderMethod` in `tvgSwRender.h`, 
- We welcome, you can freely talk & discuss openvg implementation and troubles you have. probably, [discord ](https://discord.gg/n25xj6J6HM) channel or [discussion](https://github.com/orgs/thorvg/discussions) is a good for this. I think the designated backend engine maintainers could guide you with this but I guess it won't be an easy job.

Still, it's good to investigate for thorvg performance, but just so you know, this situation reminds me of the time, about 15 years ago, when I was involved in developing UI systems / platforms for smartphones. Back then, supporting a visually rich UX on low-spec mobile phones (compared to today) was quite challenging. Vector graphics with animations, in particular, consumed too many hardware resources, so using vector-based GUIs or SVGs wasn’t a good strategy at the time. We tried to solve everything with simple shapes or image-based GUIs (almost). In other words, for complex scenes, sequential image animations were a better alternative. Even long after vector graphics and SVGs had emerged, they weren't considered viable options for embedded devices. It wasn’t until around 2012, when hardware specifications improved significantly, that the trend shifted from image-based to vector-based graphics.

**Comment by xlbao123** [comment]
> @xlbao123 Hi,
> 
> * How about the performance if playing simple animations? [hourglass.json](https://github.com/user-attachments/files/16884176/hourglass.json) Complex and fancy visuals would not be suitable for those super lowend devices.
> * Could you please double-check the attached trace file? It's just a JSON file, and I'd like to see the actual data on the device you have.

I tested the `hourglass.json`, and the results are much better, with each frame rendering time close to 30ms. I've also attached the trace file [here](https://github.com/user-attachments/files/16901726/hourglass.zip). The trace file is in JSON format (Google Trace Event format), and you can view it by visiting [https://ui.perfetto.dev/](https://ui.perfetto.dev/) and selecting 'Open Trace File'."

> * There are no plans for the ThorVG team to add OpenVG support.
> * However, ThorVG is open to contributions. You'll find a few backends (`sw_engine`, `gl_engine`, `wg_engine`) in the `src/renderer/` directory. You might consider adding a `vg_engine` and contributing it. You can refer to the `RenderMethod` in `tvgRender.h`, which is kind of like a Render Hardware Interface (RHI) in ThorVG. You could implement OpenVG support for those interfaces
> 
> ![image](https://private-user-images.githubusercontent.com/3711518/364628226-b8bd151d-fc12-4399-aaa8-a9b546057d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTYwMDksIm5iZiI6MTcyNTUxNTcwOSwicGF0aCI6Ii8zNzExNTE4LzM2NDYyODIyNi1iOGJkMTUxZC1mYzEyLTQzOTktYWFhOC1hOWI1NDYwNTdkNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDU1NTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUxOTI3MGU1ZDIzZGM0YWZkZmU0ZWIwMjBjY2JiNGY4NmVkMGI0OGMzMDBmZjIzNzQxOGRiZjQ3ZjhjZTY3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CcJl88tooS_rFtnpPROUXdy3Fw9QF5N4uverCPHD9IM)
> 
> * The best reference could be `SwRenderer inheriting RenderMethod` in `tvgSwRender.h`,
> * We welcome, you can freely talk & discuss openvg implementation and troubles you have. probably, [discord ](https://discord.gg/n25xj6J6HM) channel or [discussion](https://github.com/orgs/thorvg/discussions) is a good for this. I think the designated backend engine maintainers could guide you with this but I guess it won't be an easy job.

Alright, I'll take a look at this. Based on the trace data, I believe that by utilizing the 2D GPU, those less complex Lottie files should be able to reach a usable level.
> 
> Still, it's good to investigate for thorvg performance, but just so you know, this situation reminds me of the time, about 15 years ago, when I was involved in developing UI systems / platforms for smartphones. Back then, supporting a visually rich UX on low-spec mobile phones (compared to today) was quite challenging. Vector graphics with animations, in particular, consumed too many hardware resources, so using vector-based GUIs or SVGs wasn’t a good strategy at the time. We tried to solve everything with simple shapes or image-based GUIs (almost). In other words, for complex scenes, sequential image animations were a better alternative. Even long after vector graphics and SVGs had emerged, they weren't considered viable options for embedded devices. It wasn’t until around 2012, when hardware specifications improved significantly, that the trend shifted from image-based to vector-based graphics.

I totally agree with you. Thank you very much for your amazing project and patient answers😊.

**Comment by hermet** [comment]
> I tested the `hourglass.json`, and the results are much better, with each frame rendering time close to 30ms. I've also attached the trace file [here](https://github.com/user-attachments/files/16901726/hourglass.zip). The trace file is in JSON format (Google Trace Event format), and you can view it by visiting https://ui.perfetto.dev/ and selecting 'Open Trace File'."

The attached file still seems to be wrong. :-)

**Comment by hermet** [comment]
@xlbao123 Hi, could you please try to compare the performance with this code?

```
//tvgSwRasterC.h (23 line)
template<typename PIXEL_T>
static void inline cRasterPixels(PIXEL_T* dst, PIXEL_T val, uint32_t offset, int32_t len)
{
    dst += offset;

    while (len > 1) {
        *dst = val;
        len --;
        dst ++;
    }
}
```

**Comment by xlbao123** [comment]
> @xlbao123 Hi, could you please try to compare the performance with this code?
> 
> ```
> //tvgSwRasterC.h (23 line)
> template<typename PIXEL_T>
> static void inline cRasterPixels(PIXEL_T* dst, PIXEL_T val, uint32_t offset, int32_t len)
> {
>     dst += offset;
> 
>     while (len > 1) {
>         *dst = val;
>         len --;
>         dst ++;
>     }
> }
> ```

The results are similar. it seems that the hardware's memory bandwidth is the main bottleneck. Anyway, thank you very much! ❤️
