### ISSUE TITLE
Version 0.10.x fails to build with `NOMINMAX` on VS 2017

### ISSUE THREAD

**Issue by akien-mga** [thorvg/thorvg#1661]
See this Godot bug report: https://github.com/godotengine/godot/issues/81618

We define `NOMINMAX` as is customary for a project that needs to include `<windows.h>` and all its legacy problematic macros.

While thorvg builds fine with VS 2022, it seems to lack the `min` and `max` definition in VS 2017 in this case, so `tvgSwCommon.h` fails building:
```
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(366): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(367): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(368): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(375): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(376): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(377): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(405): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(406): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(407): error C3861: 'min': identifier not found
```

This can be fixed by replacing the use of `min` and `max` by `std::min` and `std::max` (and adding `#include <algorithm>`).

Here's a patch: https://github.com/akien-mga/godot/blob/thorvg-0.10.6/thirdparty/thorvg/patches/fix-vs2017-nominmax.patch

---

Side question: I wanted to make a PR with this fix, but I don't see any branch with the `0.10.x` code... Is this private?
I would really encourage keeping such code public so that the tags can be sourced from a branch that actually belongs in the repository. Currently `v0.10.6` and older tags seem to be orphan commits.

**Comment by hermet** [comment]
@akien-mga Thanks for report. I will review your patch. Currently, ThorVG doesn't maintain release branches by mistake in the beginning. Instead, you can jump to a checkpoint from a release tag. ThorVG will preserve all the release branches after the 1.0 official release. It's almost there.
