### ISSUE TITLE
About project progress

### ISSUE THREAD

**Issue by xland** [thorvg/thorvg#1665]
I check `ThorVG`‘s progressing in every few days.
I'm really looking forward to [Font Drawing](https://github.com/thorvg/thorvg/issues/969) feature (And [Anti-aliasing](https://github.com/thorvg/thorvg/issues/1543)）.
But I found that this feature will not be implemented until version 1.1.

I am considering whether to use 'ThorVG' in my new project.
So，When will version 1.1 be released?
Will it be finished by the end of this year(2023)?

Thanks very much.

**Comment by hermet** [comment]
Hello, the font drawing has been postponed in terms of landing the task. The 1.1 plan is still uncertain at this point. I estimate that the team could start the task around November (after the 1.0 release), and I anticipate it would take approximately 3 months to complete the very basic font drawing feature. 

https://github.com/thorvg/thorvg/wiki/23'-Development-Milestone
https://github.com/thorvg/thorvg/wiki/v1.0-Release-Plan

**Comment by xland** [comment]
OK~
Thanks for your reply.
