### ISSUE TITLE
incorrect dash offset position

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1686]
Dash-offset result is different with inkscape version. 

![image](https://github.com/thorvg/thorvg/assets/3711518/27f53589-755a-404a-8122-3f62fcb517f4)

```
<svg width="512" height="512" version="1.1" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
	<g fill="none">
		<g stroke-width="20">
			<path d="m20 40h120l-20 90-80-10v-100" stroke="#f00" stroke-linecap="round" stroke-linejoin="bevel"/>
			<path d="m170 40h120l-20 90-80-10v-100" stroke="#ff0" stroke-linecap="square" stroke-linejoin="bevel"/>
			<path d="m320 40h120l-20 90-80-10v-100" stroke="#0f0" stroke-linecap="square" stroke-miterlimit="5"/>
		</g>
		<g stroke-dasharray="40, 40, 60" stroke-width="20">
			<path d="m20 175.21h120l-20 90-80-10v-100" stroke="#f00" stroke-linecap="round" stroke-linejoin="round"/>
			<path d="m170 175.21h120l-20 90-80-10v-100" stroke="#ff0" stroke-linecap="square" stroke-linejoin="bevel"/>
			<path d="m320 175.21h120l-20 90-80-10v-100" stroke="#0f0" stroke-linecap="square" stroke-miterlimit="5"/>
		</g>
		<g stroke-width="15">
			<path d="m137.52 295.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#f00" stroke-linecap="round" stroke-linejoin="round"/>
			<path d="m287.52 295.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#ff0" stroke-linecap="square" stroke-linejoin="bevel"/>
			<path d="m437.52 295.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#0f0" stroke-linecap="square" stroke-miterlimit="5"/>
		</g>
		<g stroke-dashoffset="10" stroke-width="10">
			<path d="m137.52 405.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#f00" stroke-dasharray="30,20" stroke-linecap="round" stroke-linejoin="round"/>
			<path d="m287.52 405.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#ff0" stroke-dasharray="30, 20" stroke-linecap="square" stroke-linejoin="bevel"/>
			<path d="m437.52 405.83a100 100 0 0 1-58.193 77.9l-40.912-91.248z" stroke="#0f0" stroke-dasharray="30, 20" stroke-linecap="square" stroke-miterlimit="5"/>
		</g>
		<g stroke="#ff0" stroke-linejoin="bevel" stroke-width="10">
			<ellipse cx="475" cy="245" rx="15" ry="75" stroke-dashoffset="5"/>
			<ellipse cx="475" cy="410" rx="15" ry="75" stroke-dasharray="30, 10" stroke-dashoffset="20"/>
			<ellipse cx="475" cy="79.999" rx="15" ry="75" stroke-dasharray="30" stroke-linecap="square"/>
		</g>
	</g>
</svg>
```

History: https://github.com/thorvg/thorvg/pull/1685

**Comment by capnm** [comment]
+ inline SVG == Inkscape == another viewers
![test](https://github.com/thorvg/thorvg/assets/4047289/4f3d6590-ccd1-44ca-b9ea-dc4c044fad5f)

**Comment by mgrudzinska** [comment]
after #1985:
<img src="https://github.com/thorvg/thorvg/assets/67589014/8f06d3ec-1f2e-4174-8821-ac64ce082188" width="400">

This is almost perfect except for the ellipses. It is because the starting point for the dashed lines being chosen differently in TVG and Inkscape. This could be easily changed in the appendCircle function, but I haven't found any information in the SVG standard specifying where this point should be. So, changing it just because it is set differently in another tool doesn't seem like the best idea, in my opinion.

Just to see whether the result would be exactly the same, I changed it, and yes, then everything looks like it does in Inkscape:
<img src="https://github.com/thorvg/thorvg/assets/67589014/b3d78b94-5359-47e4-9c98-1de61bdf4c31" width="400">

**Comment by capnm** [comment]
@mgrudzinska nice to see you again!

> but I haven't found any information in the SVG standard specifying where this point should be.

Only found this about the path start of the stroke for an SVG ellipse (circle): :

https://svgwg.org/svg2-draft/shapes.html#EllipseElement
`Mathematically, an ‘ellipse’ element is mapped to an equivalent ‘path’ element that consists of four elliptical arc segments, each covering a quarter of the ellipse. The path begins at the "3 o'clock" point on the radius and proceeds in a clock-wise direction (before any transformation). `

I have taken some screenshots to show how the various applications view the SVG:
[Dash-offset-test.pdf](https://github.com/thorvg/thorvg/files/14317954/Dash-offset-test.pdf)

**Comment by mgrudzinska** [comment]
> @mgrudzinska nice to see you again!

nice to be back and see all of you here!

> https://svgwg.org/svg2-draft/shapes.html#EllipseElement `Mathematically, an ‘ellipse’ element is mapped to an equivalent ‘path’ element that consists of four elliptical arc segments, each covering a quarter of the ellipse. The path begins at the "3 o'clock" point on the radius and proceeds in a clock-wise direction (before any transformation). `

Thx! applied in #1985. 

Now the results from Inkscape/gimp/browsers and ThorVG are the same.

just to be sure I check more precisely:
```
<svg width="512" height="512" version="1.1" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
<g fill="none" stroke="#f00" stroke-linejoin="bevel" stroke-width="15">
  <ellipse cx="50" cy="245" rx="45" ry="75" stroke-dasharray="29.3"
stroke-dashoffset="0" />
<ellipse cx="250" cy="245" rx="45" ry="75" stroke-dasharray="29.3"
stroke-dashoffset="7" />
<ellipse cx="450" cy="245" rx="45" ry="75" stroke-dasharray="28.1"
stroke-linecap="square" />
</g>
</svg>
```

before:
<img width="573" alt="Zrzut ekranu 2024-02-19 o 02 27 19" src="https://github.com/thorvg/thorvg/assets/67589014/4451f3de-ba73-4e40-9a00-3989cc462d12">

ThorVG after #1985 (the expected results):
<img width="591" alt="Zrzut ekranu 2024-02-19 o 02 26 49" src="https://github.com/thorvg/thorvg/assets/67589014/5c418558-07f2-437e-8590-0167d7fe5b58">
