### ISSUE TITLE
Support gif saver

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1712]
- src/savers/gif: Add a saver module to export the scenes by converting and exporting them to a GIF file.
- Additionally, we can include another tool: lottie2gif.

**Comment by hermet** [comment]
@JSUYA  I'm working on my side, based on your progress.

**Comment by JSUYA** [comment]
> @JSUYA I'm working on my side, based on your progress.

I will update PR as soon as possible. I am sorry for being late.
