### ISSUE TITLE
SVG fill-opacity blending incorrect

### ISSUE THREAD

**Issue by lostminds** [thorvg/thorvg#1716]
The compositing/blending of svg elements with fill-opacity seems to be incorrect in v0.11.1 (same in 0.10 via Godot 4.2beta1 where I first found the issue). Below is a simple example svg, with a red rectangle and then a semi-transparent black rectangle on top.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 1206 1200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">
            <rect x="219" y="207" width="563" height="563" fill="rgb(255,0,0)"/>
            <rect x="426" y="401" width="523" height="523" fill="rgb(0,0,0)" fill-opacity="0.5"/>
</svg>
```
On the left you can see how this is expected to render (in Firefox) and on the right the rendered output in the [ThorVG viewer](https://thorvg.github.io/thorvg.viewer/)

![Screenshot 2023-10-19 at 12 23 18](https://github.com/thorvg/thorvg/assets/17763524/9966a004-99b6-4bfe-87ba-0b4328f4fdb2)

The blend mode seems to be incorrect for the overlapping area, resulting in addition instead of the expected normal blend. And it also seems that for areas that blend with the background (the non-overlapping area) the result is fully opaque instead of the expected alpha of the semitransparent rectangle.

**Comment by lostminds** [comment]
Interestingly in Godot the blending of the overlapping areas seems to be correct. At least it doesn't look like it's additive blending as above. But the issue with the fully opaque background-blending is there. I'm not sure if this is a change from v 0.10 in Godot 4.2beta1 to the version in the ThorVG viewer or something based on the rendering context. 

Godot left, firefox right
![Screenshot 2023-10-19 at 12 48 35](https://github.com/thorvg/thorvg/assets/17763524/d3a2cd52-930c-4bae-b09a-735daccaffb5)

**Comment by capnm** [comment]
![image](https://github.com/thorvg/thorvg/assets/4047289/08b69b8c-1f4c-4319-ba18-c635c07db42b)

**Comment by lostminds** [comment]
> Is a regression between Godot 4.2.dev3 (good) - 4.2.dev4 (bad)

I guess this means it's a regression in ThorVG 0.10.0 from ThorVG 0.9.0, as this is I think what changed in 4.2.dev4 https://github.com/godotengine/godot/pull/80095

**Comment by capnm** [comment]
Yes, thanks! I know, already running git bisect.

**Comment by capnm** [comment]
@hermet the regression is caused by c50d2fde5fcf4ff60765e8903fd1218165a53765

**Comment by hermet** [comment]
@capnm thanks, i will check it soon 👍

**Comment by hermet** [comment]
Fixed:
![image](https://github.com/thorvg/thorvg/assets/3711518/e4168d07-db4a-4d9d-8d37-759f06239fa4)

**Comment by hermet** [comment]
fixed:
![image](https://github.com/thorvg/thorvg/assets/3711518/c08a36c2-8c60-4be7-9f22-9f80bf908bb9)

**Comment by hermet** [comment]
@lostminds @capnm  please check this release thanks for your support! https://github.com/thorvg/thorvg/releases/tag/v0.11.2

**Comment by lostminds** [comment]
Great, thanks for the quick fix @hermet and @capnm!
