### ISSUE TITLE
LVGL integration

### ISSUE THREAD

**Issue by kisvegabor** [thorvg/thorvg#1742]
Hi,

We will integrate your amazing library into [LVGL](https://lvgl.io/). We already have the required the APIs and architecture in LVGL for that, and it really works with ThorVG, if we build and install it on Linux using Meson.

However, for easier integration into **any** platform (STM32, NXP, ESP, Arduino, etc) it would be great to make ThorVG part of LVGL so that people just need to enable a config in our config file(e.g.  `LV_USE_THORVG`) and ThorVG would be enabled just like any other file of LVGL. It means that we copy-paste the required ThorVG files into LVGL and tweak them if needed.  

However LVGL is quite build system agnostic. You just need to compile all the C files. (Maybe the content of some of them are disabled via `#if LV_USE_SOMETHING`.) 

So I wonder if it's possible to integrate ThorVG this way and what could be main issues.

Even if it's not possible we will advertise that LVGL uses ThorVG as vector render engine, however with a deeper integration I'm sure that we could reach more people.

**Comment by hermet** [comment]
@kisvegabor Hello, thank you for reaching out to the ThorVG project.  It's incredibly exciting to hear that LVGL is exploring the possibility of the ThorVG integation.

Firstly, in response to your question, I currently have some uncertainty about the specifics. 

It's important to note that both ThorVG and LVGL are independently managed projects. While LVGL depends on ThorVG, the ideal scenario would be for ThorVG to remove a dependency for LVGL. From an architectural perspective, it's imperative to follow the building block stacking principle, which typically progresses from the bottom to the top. Straying from this structure could complicate the task of maintaining robust/compact code within ThorVG and other projects such as Godot. The challenge lies in discerning when #if-endif statements become obsolete, redundant, or broken due to changes in LVGL and ThorVG.

Therefore, before seeking further clarification, we should deliberate on the methodology to address this concern:

- How to test and verify the #if-endif statement code from ThorVG with its Continuous Integration (CI) process.

Or maybe, ThorVG might consider incorporating portability code to directly support STM32, NXP, ESP, and Arduino systems.

Otherwise, perhaps you could provide any initial patches, and we can collaboratively explore suitable solutions.

Thank you for your understanding and let's discuss further to reach a proper consensus.

**Comment by kisvegabor** [comment]
I absolutely agree that ThorVg shouldn't contain any LVGL specific things. However I wonder if we can figure out something more generic to make it easy to build via managed build systems. 

We have added [this](https://github.com/lvgl/lvgl/pull/4691/files#diff-dca7907cd2c6bcb629059780280622eeac2215ea8b264b09e247f6b105a3a8d5R23-R24) to each ThorVG cpp and h file. So now we can easily enable the files via a define, which can come from either a header file or Kconfig too. 

We have kept only the files we need, but In the same there could be defines for each feature. Basically the equivalents of  Meson build options. Meson could automatically set the these defines too. E.g. when the SVG laoder is enabled in Meson set `THORVG_USE_LOADER_SVG=1`. Without Meson we could use these defines only. However, to make the cpp and hfiles see these defines a `thorvg_config.h` file needs to be included in all the files. Of course can be made optional by having something like:
```c
#ifndef THORVG_NO_CONFIG_H
#include "thorvg_config.h"
#endif
```

To make it really easy to integrate "thorvg_config.h" always should be included from a relative path to save the include path configuration too. 

This way ThorVg could be a just a "drop into any build system or environment" library which in my opinion would help lot the use it on much more places. 

> How to test and verify the #if-endif statement code from ThorVG with its Continuous Integration (CI) process.

Great question! So you would like to test if the `#if THORVG_USE_...` defines are correctly added to all the file, right? If so probably a different build is required where you can use e.g.  a simple Make and pass `-DTHORVG_USE_...` options and/or use `thorvg_conf.h` file. In the end you need to test if e.g. the SVG related functions are really available if you have enabled them.

**Comment by hermet** [comment]
> We have added [this](https://github.com/lvgl/lvgl/pull/4691/files#diff-dca7907cd2c6bcb629059780280622eeac2215ea8b264b09e247f6b105a3a8d5R23-R24) to each ThorVG cpp and h file. So now we can easily enable the files via a define, which can come from either a header file or Kconfig too.

First of all, let's clarify this:

ThorVG already has a structure-based design, where features are organized into separate folders:
```
renderer
renderer/sw
renderer/gl
renderer/wg
loader/svg
loader/lottie
loader/tvg
saver/tvg
...
```
The features enabled during the Meson build process are introduced to the binary through the generated thorvg config.h file, which may look like this:
```
#pragma once
#define THORVG_GIF_SAVER_SUPPORT 1
#define THORVG_JPG_LOADER_SUPPORT 1
#define THORVG_LOG_ENABLED 1
#define THORVG_LOTTIE_LOADER_SUPPORT 1
#define THORVG_PNG_LOADER_SUPPORT 1
#define THORVG_SVG_LOADER_SUPPORT 1
#define THORVG_SW_RASTER_SUPPORT 1
#define THORVG_TVG_LOADER_SUPPORT 1
#define THORVG_TVG_SAVER_SUPPORT 1
#define THORVG_VERSION_STRING "0.11.99"
```

Let's assume that A file in the ThorVG project has been refactored and now depends on another existing B file. If LVGL decides to disable B, it may break LVGL. I don't believe that enabling or disabling features on a per-file basis is a good idea. It would make the project less maintainable and more fragile. **All files in the same directory** are expected to work together. If LVGL wants to use primitive vector drawing, I think it could configure the build script to enable only the necessary folders, such as [renderer/common/sw_engine]. If LVGL wishes to use SVG and Lottie features simultaneously, it can enable the folders [renderer/common/sw_engine/lottie/svg] as needed.

Doesn't this folder-based approach work for LVGL? I believe this is the better approach we should consider. Additionally, we might be able to reach a compromise by adding more definitions (if necessary) to the above ThorVG config.h.

**Comment by hermet** [comment]
@kisvegabor Yes, that would be much better. Users could use a custom config.h to enable only the necessary parts. Additionally, we can further categorize the modules if it's deemed useful.

So far, here is the full list of thorvg features.

```
//engines
#define THORVG_WG_RASTER_SUPPORT 1
#define THORVG_GL_RASTER_SUPPORT 1
#define THORVG_SW_RASTER_SUPPORT 1

//capi binding
#define THORVG_CAPI_BINDING_SUPPORT 1

//savers
#define THORVG_GIF_SAVER_SUPPORT 1
#define THORVG_TVG_SAVER_SUPPORT 1

//loaders
#define THORVG_PNG_LOADER_SUPPORT 1
#define THORVG_JPG_LOADER_SUPPORT 1
#define THORVG_LOTTIE_LOADER_SUPPORT 1
#define THORVG_SVG_LOADER_SUPPORT 1
#define THORVG_TVG_LOADER_SUPPORT 1
#define THORVG_WEBP_LOADER_SUPPORT 1

//etc
#define THORVG_LOG_ENABLED 1
#define THORVG_VERSION_STRING "0.11.99"
```

**Comment by kisvegabor** [comment]
It looks really great! 
Will this be added to your roadmap? If so, let me know when we can test it. :blush:

**Comment by hermet** [comment]
@kisvegabor The list of the config is already in. LVGL could make a config.h or adding the defines  above only necessaries, somewhere in your configuration.

I guess so far these are necessary by LVGL.

//for vector primitives 
#define THORVG_SW_RASTER_SUPPORT 1
#define THORVG_CAPI_BINDING_SUPPORT 1
#define THORVG_VERSION_STRING "0.11.99"

//for svg
#define THORVG_SVG_LOADER_SUPPORT 1

 //for lottie?
#define THORVG_LOTTIE_LOADER_SUPPORT 1

**Comment by kisvegabor** [comment]
Yes, I think we need only these.

From our side the `#if THORVG_SW_RASTER_SUPPORT` and similar guards in cpp and h files are missing to try replacing Meson with managed build.

**Comment by hermet** [comment]
@kisvegabor Hello, it seems that ThorVG has been merged into LVGL? I wonder if you don' mind if ThorVG adds LVGL integration showcase in ThorVG practice page.

![image](https://github.com/thorvg/thorvg/assets/3711518/c0bcb8a0-5050-4e5f-9bad-c1d2f07fc193)

**Comment by kisvegabor** [comment]
Yes, it's merged indeed, however the version in which is added (v9.0) will be released only in January. I don't know if it's a problem.

Anyway, it would be a great honor to be listed among the practices! Please let me know when LVGL added so that I can announce this great achievement. :slightly_smiling_face:

**Comment by hermet** [comment]
Ok, let's post it when LVGL v0.9 is released. Thanks!

**Comment by kisvegabor** [comment]
Sure, I'll let you know!
