### ISSUE TITLE
Revise the Canvas::clear() API.

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1779]
Add a chance to clear buffer with a specific color.

Expected API:
virtual Result Canvas::clear(uint8_t r, uint8_t g, uint8_t b, uint8_t a)

**Comment by hermet** [comment]
@SergeyLebedkin @RuiwenTang Hello, Please let me know if you have any opinion.

**Comment by RuiwenTang** [comment]
There is already a `clear` function on the canvas, which means clear all paints pushed into this canvas. Will this cause ambiguity?

BTW，does the `Canvas::clear(r,g,b,a)` method designed to be called repeatedly during a frame of drawing like this:
```
canvas->push(shape)
canvas->clear(0, 0, 0, 0)
canvas->push(shape)
```
Or is it just to clear the remaining drawing content at the beginning of a frame like this:
```
canvas->push(shape)

canvas->clear(0, 0, 0, 0)
canvas->draw()
canvas->sync()

```

**Comment by hermet** [comment]
> here is already a `clear` function on the canvas, which means clear all paints pushed into this canvas. Will this cause ambiguity?

Let's see how we can remove the clear() for paints and merge it with new one, even though both resides within the codebase,  they are quite simple and explicitly identified with different parameters.

> BTW，does the `Canvas::clear(r,g,b,a)` method designed to be called repeatedly during a frame of drawing like this:

The second case. Clear(r, g,b , a) is not mandatory btw, if user fill the explicit background with a shape.

**Comment by RuiwenTang** [comment]
> The second case. Clear(r, g,b , a) is not mandatory btw, if user fill the explicit background with a shape.

For this case. Can we put the `color parameters` in `Canvas::draw()` like 
```Canvas::draw(uint8_t r = 0, uint8_t g = 0, uint8_t b = 0, uint8_t a = 0)```
Since when begin a RenderPass in GPU backend, can specify a clean color if the color attachment load_op is `Clear` which is the most common use case.

**Comment by hermet** [comment]
clear buffer is not

> > The second case. Clear(r, g,b , a) is not mandatory btw, if user fill the explicit background with a shape.
> 
> For this case. Can we put the `color parameters` in `Canvas::draw()` like `Canvas::draw(uint8_t r = 0, uint8_t g = 0, uint8_t b = 0, uint8_t a = 0)` Since when begin a RenderPass in GPU backend, can specify a clean color if the color attachment load_op is `Clear` (which is the most common use case.)

You can store the clear buffer value in the engine side and conduct the clear() later in the preRender?

**Comment by hermet** [comment]
```
canvas->clear(r, g, b, a)  //optional
canvas->draw()
canvas->sync()
```

```
canvas->draw(r, g, b, a) or canvas->draw()
canvas->sync()
```

```
canvas->clearColor(r, g, b, a)         //set a clear color   (optional)
canvas->draw(clear = true)             //conduct the clear. (++dependency, clear = true is only valid when clearColor is properly set up)
```

**Comment by RuiwenTang** [comment]
> That case, we should provide both draw() / draw(r, g ,b, a). Clear buffer shouldn't be mandatory for users. You can store the clear buffer value in the engine side and conduct the actual-clear later in the preRender?

Store the clear value is not difficult, but I'm worried that this will cause additional ambiguity.
Like:
```
canvas->push(shape1)
canvas->clear(0, 0, 0, 0)
canvas->push(shape2)

canvas->draw()
```
Semantically this code should clear the drawing of the first shape. but in reality, the `clear` function only effected the background color of the canvas

**Comment by hermet** [comment]
Yes, I don't foresee any troubles once we provide proper guides.

**Comment by SergeyLebedkin** [comment]
> @SergeyLebedkin Hello, I'm gonna push this soon. Please show your opinion "agree ot not"

Just check this. Nothing is broken on wgpu side

**Comment by hermet** [comment]
We gonna arrange the color value later when user demand comes out clear.
