### ISSUE TITLE
Strokes not showing for basic shapes outside of the canvas

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1785]
Basic shapes are trimmed entirely when they are outside of the canvas, even if they have a big enough stroke to be partially on the canvas.

Example:

![image](https://github.com/thorvg/thorvg/assets/85438892/37ef41aa-6208-40a8-b534-37bfd44763a5)

When I move the circle 0.002 pixels down, enough to be ever so slightly on top of the canvas:

![image](https://github.com/thorvg/thorvg/assets/85438892/50deea99-0be1-49f8-b690-6b79cfff4ff4)

The SVG: `<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="-4.001" r="4" stroke="#8da5f3" stroke-width="3"/></svg>`

How it's displayed on my Desktop:

![image](https://github.com/thorvg/thorvg/assets/85438892/ec554742-d910-4ee8-ac0d-eaa66bba4415)

I've found this issue with circle, line, ellipse, and rect. I have not found it with path.

**Comment by hermet** [comment]
@MewPurPur, Thanks, the fix has been prepared, and we will release v0.11.5 on 24th Nov. If you encounter any issues, please let us know. We are open to adjusting the release date if necessary.
