### ISSUE TITLE
Not able to compile thorvg without thread support

### ISSUE THREAD

**Issue by adamscott** [thorvg/thorvg#1821]
I'm trying to create a version of Godot 4.x that would compile without thread support. 

This is to make the editor and to export games on a non-COOP/COEP web environment. Due to Meltdown and Spectre, the web platform requires COOP and COEP in order to have access to `SharedArrayBuffer`, which is required by Emscripten to compile and use threads.

Unfortunately, I can compile thorvg without `USE_PTHREADS=1`, but it will inevitably crash when trying to instantiate `tvg::TaskScheduler`, even if we could set `tvg::TaskScheduler::async(false)` afterwards.

![Capture d’écran du 2023-12-06 14-09-53](https://github.com/thorvg/thorvg/assets/270928/342df159-bd0e-48e5-af84-09930343abbb)

Ideally, it should be possible to compile thorvg in a way to forgo the use of threads.

**Comment by hermet** [comment]
@adamscott Hello, basically ThorVG supports intrinsic threading, and you can easily toggle this feature with a single API call. You can set the desired thread number(0) in the initializer. Probably, you can find the call this in Godot(modules/svg/register_type.cpp:45)
```
tvg::Initializer::init(tvg::CanvasEngine::Sw, 1); -> tvg::Initializer::init(tvg::CanvasEngine::Sw, 0);
```
![image](https://github.com/thorvg/thorvg/assets/3711518/32298a1c-8a64-4410-8bce-c80336a71952)

That's all you need to do.
