### ISSUE TITLE
Regression: After v0.11.6 – Godot deadlocks, distorted images

### ISSUE THREAD

**Issue by capnm** [thorvg/thorvg#1826]
I compiled recent github tips from Godot (4.3) and ThorVG today and see a huge increase in deadlocks (I have to switch the editor to `single window mode` to keep it running) and SVG -> texture, icon distortions:

![image](https://github.com/thorvg/thorvg/assets/4047289/d171af88-cfab-412e-a2f4-f27f70ac3185)
![image](https://github.com/thorvg/thorvg/assets/4047289/5e5ca73f-bb18-4413-9c6b-38cb4dc3f708)

Godot git-tip + ThorVG v0.11.5 works fine, not sure what the reason is. I can take a closer look next week with the debugger.

**Comment by hermet** [comment]
@capnm Hello, thorvg is undergoing significant changes for its 1.0 release. With this release, there will be some compatibility breaks, and these changes have already been implemented in the main branch. Meanwhile, we will maintain compatibility during the v0.x releases. Therefore, v0.11 (and upcoming v0.12) must be compatible with Godot. For your information, I guess these two patches in main might occur abi breaks in godot.

```
commit f2c29063d25cce3efc1b6d4039bd54dc23d8d630
Author: Hermet Park <hermet@lottiefiles.com>
Date:   Thu Nov 23 01:10:18 2023 +0900

    api: updated the recent changed api again.

    Reordered by the data packing size.
    Also removed a wrong capi default parameter value.

    Result Picture::load(const char* data, uint32_t size, const std::string& mimeType, bool copy = false, const std::string& rpath = "")
    -> Result load(const char* data, uint32_t size, const std::string& mimeType, const std::string& rpath = "", bool copy = false)

    Tvg_Result tvg_picture_load_data(Tvg_Paint* paint, const char *data, uint32_t size, const char *mimetype, bool copy, const char* resourcePath)
    -> Tvg_Result tvg_picture_load_data(Tvg_Paint* paint, const char *data, uint32_t size, const char *mimetype, const char* resourcePath, bool copy);
```
```
commit 548962f5f8868429b9ebf5ce6fb9005dcb9a606a
Author: Sergii Liebodkin <sergii@lottiefiles.com>
Date:   Mon Nov 20 10:59:38 2023 +0900

    apis/engines: Revise the clear() buffer behavior.

    ThorVG has offered an option to clear the buffer since version 1.0.
    This is essential when users utilize the canvas target buffer
    with the main render target. They share the buffer
    and need to draw contents onto the existing contents.

    API:
    Result Canvas::clear(bool free = true)
    -> Result Canvas::clear(bool paints = true, bool buffer = true)

    Tvg_Result tvg_canvas_clear(Tvg_Canvas* canvas, bool free);
    -> Tvg_Result tvg_canvas_clear(Tvg_Canvas* canvas, bool paints, bool buffer);

    Issue: https://github.com/thorvg/thorvg/issues/1779

    Co-Authored-By: Hermet Park <hermet@lottiefiles.com>
```

**Comment by hermet** [comment]
@capnm I suggest you to see the v0.11.x branch for sync-up, and v0.12.x when it's introduced(planning it end of this month)

**Comment by hermet** [comment]
@capnm Hello Martin, Happy New Year! ThorVG is set to be released with version 0.12.0. Could you please confirm if there are any regression issues from the Godot? You can see v0.12.x branch for the integration: https://github.com/thorvg/thorvg/tree/v0.12.x

**Comment by capnm** [comment]
@hermet I'm getting some linker errors right now, but I'll fix it ASAP.
Happy new year!

**Comment by capnm** [comment]
LGTM!

Current CI run:  https://github.com/capnm/godot4/actions/runs/7370790095
