### ISSUE TITLE
Gradients don't work when scaling causes them to be larger than ~2896.309 px

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1834]
`<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><linearGradient x2="289.64" gradientUnits="userSpaceOnUse" id="a"><stop stop-color="red"/></linearGradient><rect width="16" height="16" fill="yellow"><circle r="16" fill="url(#a)"/></svg>`

For example, this SVG needs to be scaled 10x to reach that barrier. If you plug it for example in the ThorVG viewer, the red circle will stop showing from 160x160 onward.

The number is 2048 * sqrt(2)

**Comment by hermet** [comment]
@MewPurPur 
![image](https://github.com/thorvg/thorvg/assets/3711518/f1f28a2a-8a5d-489b-a717-1b04e5c7c462)

**Comment by capnm** [comment]
Hi @MewPurPur, btw. your SVG contains a syntax error (<rect ........ />). Please always try to check the syntax to get more reliable results. 

```
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
<linearGradient x2="289.64" gradientUnits="userSpaceOnUse" id="a">
<stop stop-color="red"/>
</linearGradient>
<rect width="16" height="16" fill="yellow"/>
<circle r="16" fill="url(#a)"/>
</svg>

```
![gdi86128](https://github.com/thorvg/thorvg/assets/4047289/6caf11b4-c707-41f9-8ca9-7175709944e3)
