### ISSUE TITLE
web/lottie-player: please check this codepen example I created:

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1858]
please check this codepen example I created: https://codepen.io/aidosmf/pen/PoLYzVX

if I would like to change styles programmatically, there is no way to access it from the instance. The public methods are not workings as well

_Originally posted by @Aidosmf in https://github.com/thorvg/thorvg/pull/1817#discussion_r1434875039_

**Comment by tinyjin** [comment]
Thank you! @Aidosmf 
Let me take a look deeper into this example.

Since it's standard web component, I guess the creation should be like this
```ts
// wrong
import { LottiePlayer } from "https://esm.sh/@thorvg/lottie-player";
...
const player = await createPlayer()

// correct
import 'https://unpkg.com/@thorvg/lottie-player@latest/dist/lottie-player.js';
...
const player = document.createElement('lottie-player');
```

unsure yet, I'll prepare valid example for js-creation.

It's really good for improving test suite by the way = )
