### ISSUE TITLE
svg2png had no content.

### ISSUE THREAD

**Issue by zengzm1212** [thorvg/thorvg#1868]
![image](https://github.com/thorvg/thorvg/assets/59642136/22b1f9a6-de67-463b-b767-19d05200305b)
When I used the svg2png tool (src/tools/svg2png/svg2png.cpp), I found that the exported png image had no content.
After further checking the code, I found that the canvas->target function here did not assign a value to the buffer. Want to confirm if this is a BUG?

**Comment by hermet** [comment]
@zengzm1212 Hello, could you please provide detailed steps on how to reproduce the issue? probably, the tool arguments info and svg data you used will be useful.

**Comment by zengzm1212** [comment]
![image](https://github.com/thorvg/thorvg/assets/59642136/e89b59e5-7850-455f-b886-2e4f5752c4c6)
![image](https://github.com/thorvg/thorvg/assets/59642136/cbc95b66-882b-483e-9ac7-012f56ea9351)
![mbe_art](https://github.com/thorvg/thorvg/assets/59642136/3d24e238-8f14-47ba-bab8-0636da2e94a8)
@hermet  Here is the code I tested and the svg file I used

**Comment by hermet** [comment]
It works perfect from my side. 

1. Probably, you need to confirm the file path?  E:\svg_files\mbe_art.svg <---- ?
2. Please double check the return value "tvg::Result result = picture->load(path);"
3.  Please double check the "w", "h" value .


This is the generated png.
![293135782-3d24e238-8f14-47ba-bab8-0636da2e94a8](https://github.com/thorvg/thorvg/assets/3711518/0376e336-0e49-41d4-8aa7-fdd1eba3a545)
