### ISSUE TITLE
web/documentation: integrate JSDoc & update readme

### ISSUE THREAD

**Issue by tinyjin** [thorvg/thorvg#1883]
thinking removing API part from README and keeping Usage as our main guidance.
also considering JSDoc into https://www.thorvg.org/apis. so we can provide library users with main point of usage.

[JSDoc](https://github.com/jsdoc/jsdoc)
- most starred API documentation tool in web dev
- trusted by official typescript [link](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)

**Comment by tinyjin** [comment]
@hermet Please leave your opinion, jsdoc is just new idea, might need to check

**Comment by hermet** [comment]
moved here: https://github.com/thorvg/thorvg.web/issues/21
