### ISSUE TITLE
Double quotes inside single quotes in SVG interpreted as error.

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1892]
`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="7" a='"'/></svg>` is a SVG that won't render. The issue seems to be with XML parsing, since "a" isn't a real attribute and should just be ignored if the parsing is correct.

**Comment by capnm** [comment]
```xml
<svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg">
  <circle cx="80" cy="80" r="70" a='"'/>
</svg>
```
![single-double-qoutes](https://github.com/thorvg/thorvg/assets/4047289/80fa0279-4e12-417b-bd11-d307f5c6f4ee)

**Comment by hermet** [comment]
Thanks, it will be in v0.12.1 release.
