### ISSUE TITLE
Support pure sync mode without mutexes and tasks

### ISSUE THREAD

**Issue by kisvegabor** [thorvg/thorvg#1900]
When I built ThorVG on STM32 it turned out the `mutex` and some other task related C++ modules are not implemented there. I haven't tried, but I suspect that it's true for other vendors/platforms too.

As we are using ThorVG only in sync mode I removed all the mutex and task related parts from `tvgTaskScheduler.cpp` and `tvgTaskScheduler.h`. See the changes here https://github.com/lvgl/lvgl/pull/5249

Now it works, but I wonder if it would make sense to allow enabling a simple "sync only" mode with a define.

What do you think?

**Comment by hermet** [comment]
@kisvegabor Hello, I agree with your opinion. We can remove the threading feature from the compilation on the end side. Please let me consider making it compilable for both scenarios. I will come up with the solution.

**Comment by kisvegabor** [comment]
Thank you! :blush: 

We copy pasted the source code ThorVG into LVGL and modified it a little bit. Therefore for us the best would be to have a define in a config file we can alter this behavior.
