### ISSUE TITLE
How to remove the buffer clearing behavior in SwRenderer::preRender

### ISSUE THREAD

**Issue by FASTSHIFT** [thorvg/thorvg#1901]
I implemented an embedded GPU simulator based on ThorVG: https://github.com/FASTSHIFT/vg_lite_tvg.
 Using the vector rendering function provided by ThorVG to simulate the GPU-driven API to reduce the time of debugging on the hardware as much as possible.
I used it to complete most of the debugging work of [LVGL](https://github.com/lvgl/lvgl)+[GPU Porting](https://github.com/lvgl/lvgl/tree/master/src/draw/vg_lite) programs on PC, and it ran well on the device.

During use, I noticed that `SwRenderer` would call `rasterClear` to clean the contents of the buffer before each rendering, which resulted in the contents of the old buffer being cleared every time the target was reset, and on the hardware device my GPU does not automatically clear the buffer.

My temporary approach at the moment is to simply remove the rasterClear call in preRender:
![image](https://github.com/thorvg/thorvg/assets/26767803/bf0a3012-1139-4a06-a09e-2d36247a5ea9)

Is it possible to add an interface to control whether to automatically clear the buffer?

**Comment by kisvegabor** [comment]
Great news! 

Actually we are still not sure how to track the changes of ThorVG. Right now we needed to add modifications for 3 issues:
1. This one
2. https://github.com/thorvg/thorvg/issues/1742
3. https://github.com/thorvg/thorvg/pull/1898

Only https://github.com/thorvg/thorvg/issues/1742 is not resolved yet. If it were updated, we could just copy paste the required folders to LVGL on ThorVG releases.

**Comment by hermet** [comment]
@capnm Ok, Thanks. Note that the clear call is necessary with thorvg/main, but if this clear call is introduced in the official Godot release with ThorVG (0.12.x), the clear will actually be performed twice. This might slightly reduce performance in SVG drawing. Probably, that will be good if it could apply the clear call patch only for the CI godot + thorvg/main test.

**Comment by capnm** [comment]
> ... Probably, that will be good if it could apply the clear call patch only for the CI godot + thorvg/main test.

Yes, that's exactly what I try to do. It helps me to catch new issues in my projects that might occur later in the releases more quickly.
