### ISSUE TITLE
Non-uniform scaling results in wrongly shaped SVG strokes

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1915]
`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M8 0l4 1-4 1-4-1Z" fill="none" stroke="#def" stroke-linejoin="round" transform="matrix(1, 0, 0, 5, 0, 3)"/></svg>`

![image](https://github.com/thorvg/thorvg/assets/85438892/86835ac2-4eb5-4abe-88d7-138ada05c432)

Expected:

![image](https://github.com/thorvg/thorvg/assets/85438892/b84ecdab-0d27-4709-b7d1-3c6d7a9dafcd)

**Comment by JSUYA** [comment]
Hi @hermet 

This is tvg code for this issue.
Hope this help you.

```cpp
    auto shape1 = tvg::Shape::gen();
    shape1->moveTo(8, 0);
    shape1->lineTo(12, 1);
    shape1->lineTo(8, 2);
    shape1->lineTo(4, 1);
    shape1->close();

    tvg::Matrix m = {50, 0, 0,
                     0, 250, 150,
                     0, 0, 1};

    shape1->transform(m);

    shape1->strokeFill(255, 0, 0); 
    shape1->strokeJoin(tvg::StrokeJoin::Round); 
    shape1->strokeWidth(1); 

    if (canvas->push(std::move(shape1)) != tvg::Result::Success) return;
```

**Comment by hermet** [comment]
Same issue: https://github.com/thorvg/thorvg/issues/954

**Comment by mgrudzinska** [comment]
> Same issue: #954

#954 still contains bugs that need to be solved
