### ISSUE TITLE
SVG: Small chance that the first visible element, if it's opacity is different from 1, will have its stroke clipped incorrectly.

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1931]
I found this from an issue for my SVG editor which is made in Godot 4.2.1, which currently uses ThorVG 0.11.5: https://github.com/MewPurPur/GodSVG/issues/319 (The user uses Windows, so the issue is likely OS-agnostic).

If you want to dig into what my SVG editor does: It uses a TextureRect, and the code for redrawing is in the display_texture.gd file. Shouldn't be anything out of the ordinary.

Basically, there is a small chance that whenever the SVG redraws, the first visible element, if it's opacity is less than 1, will have part of its stroke clipped. This does not occur with fill-opacity or stroke-opacity, only with the `opacity` attribute. Here's a good example:

https://github.com/thorvg/thorvg/assets/85438892/67379422-6413-495a-81c5-f4004d70d3c6

In this example, I'm panning in order to demonstrate the problem, because in my app this currently causes the SVG to re-render. The issue can, however, also occur when the redraws don't happen in short succession.

`<svg viewBox="0 0 8 8" xmlns="http://www.w3.org/2000/svg"><line x1="5" y1="2" x2="6" y2="6" opacity=".4" stroke="#fac" stroke-width="2" stroke-linecap="round"/><line x1="2" y1="2" x2="3" y2="6" opacity=".4" stroke="#def" stroke-width="2" stroke-linecap="round"/></svg>`

**Comment by hermet** [comment]
@MewPurPur hello, i wonder this is still a valid issue from your side.

**Comment by MewPurPur** [comment]
I'll report back soon.

**Comment by hermet** [comment]
@MewPurPur ping?

**Comment by MewPurPur** [comment]
Can't reproduce this is in Godot 4.2.2.rc2
