### ISSUE TITLE
Cases of incorrect rendering of lottie graphics

### ISSUE THREAD

**Issue by MrZillaGold** [thorvg/thorvg#1933]
WASM environment, reproduced at https://www.thorvg.org/viewer. 

Rlottie viewer: https://rlottie.github.io/

#### Thorvg (invalid):

<img width="323" alt="Снимок экрана 2024-01-23 в 21 16 10" src="https://github.com/thorvg/thorvg/assets/42776347/ce1b7ec5-31f8-490f-a933-109285e61689">

#### Rlottie (valid):

<img width="221" alt="Снимок экрана 2024-01-23 в 21 17 41" src="https://github.com/thorvg/thorvg/assets/42776347/be306fc4-e885-42c4-b1a4-53e99c5a6b64">

#### Thorvg (invalid):

missed hands stroke

<img width="519" alt="Снимок экрана 2024-01-23 в 21 26 46" src="https://github.com/thorvg/thorvg/assets/42776347/f3a5934e-fd14-4896-b4be-eab35b5b5874">

#### Rlottie (valid):

<img width="597" alt="Снимок экрана 2024-01-23 в 21 22 29" src="https://github.com/thorvg/thorvg/assets/42776347/37b75723-5b1a-4505-906f-ef83f4f4cdbf">

#### Thorvg (invalid):

missed hand stroke

<img width="456" alt="Снимок экрана 2024-01-23 в 21 31 09" src="https://github.com/thorvg/thorvg/assets/42776347/f8fdd408-8e67-4eca-aebd-10f4a7fd3d33">

#### Rlottie (valid):

<img width="418" alt="Снимок экрана 2024-01-23 в 21 29 35" src="https://github.com/thorvg/thorvg/assets/42776347/2a80efa4-d2ba-4f22-9321-992899523720">

**Comment by hermet** [comment]
@MrZillaGold Thanks for reporting the issue, The fix will be applied in the next release(v0.12.3)

![image](https://github.com/thorvg/thorvg/assets/3711518/4ec3f8b7-bfb2-490f-a7f9-86250a63e98d)
![image](https://github.com/thorvg/thorvg/assets/3711518/9f5f4b09-3075-435b-804e-54b9150acf51)
