### ISSUE TITLE
Case of incorrect rendering of lottie graphics

### ISSUE THREAD

**Issue by MrZillaGold** [thorvg/thorvg#1939]
[mJgCB-JGDYU.json](https://github.com/thorvg/thorvg/files/14076350/mJgCB-JGDYU.json) - 18 frame

thorvg (invalid)

<img width="361" alt="Снимок экрана 2024-01-28 в 17 21 58" src="https://github.com/thorvg/thorvg/assets/42776347/02b53c27-016b-4e42-af96-d0ad47b515b3">

rlottie (valid)

<img width="361" alt="Снимок экрана 2024-01-28 в 17 23 07" src="https://github.com/thorvg/thorvg/assets/42776347/10e94c58-6c02-4cbe-a540-0cbe7f1a32f6">

**Comment by hermet** [comment]
fixed:
![image](https://github.com/thorvg/thorvg/assets/3711518/51342822-452d-440d-ad5c-ba1a3e2778f8)

**Comment by hermet** [comment]
thanks for reporting the issue, the fix will be applied in the next release (0.12.4)
