### ISSUE TITLE
Update the thorvg viewer to support `.lottie`

### ISSUE THREAD

**Issue by fire** [thorvg/thorvg#1946]
https://www.thorvg.org/viewer could support lottie.

**Comment by capnm** [comment]
You can drop the Lottie *.json file, animate it and even export it as GIF image.

**Comment by hermet** [comment]
@capnm Lottie refers to a collection of animations in JSON format. I think @fire was the one intended here. https://dotlottie.io/intro/.  :)

By the way, Lottie has become an industry-standard format hosted by the Linux Foundation. I'm looking forward to Godot supporting this file format soon. https://www.linuxfoundation.org/press/announcing-lottie-animation-community

**Comment by capnm** [comment]
Oh, I didn't know he meant dot Lottie. I wish we had something like dot dot svg :)

**Comment by hermet** [comment]
@theashraf Hello, any suggestion to play with the thorvg based .lottie?

**Comment by theashraf** [comment]
I'd suggest using the [dotlottie-web](https://github.com/LottieFiles/dotlottie-web) player, as it can handle both Lottie JSON and .lottie files, and it exclusively uses ThorVG as a renderer.

There is a collection of CodePen examples you can find [here](https://codepen.io/collection/rxPaBN) demonstrating dotlottie-web usage.

**Comment by hermet** [comment]
@fire Hello, The .lottie player team has launched its own viewer https://lottiefiles.github.io/dotlottie-web/, which operates on the ThorVG engine. Since ThorVG itself doesn't have the dotLottie format, the dotLottie viewer is likely the best place for testing .lottie formats. Please try it. Thanks.
