### ISSUE TITLE
First rows/column of pixels missing from embedded png in SVG

### ISSUE THREAD

**Issue by lostminds** [thorvg/thorvg#1949]
I was experimenting with embedding bitmap images using inline xlink data urls in SVG <image> tags, and since I was using a very simple data set I noticed what I think is a bug in ThorVG: It seems that the first vertical and horizontal line of pixels is not rendered correctly. I seems to be rendering the image data from pixel (1,1) to (size,size) onto the size of the element instead of (0,0) to (size,size). If you're using higher resolution images or images that don't extend to the edge this will be hard to see, but with this simple test bitmap it was quite noticeable. 

_EDIT: On closer inspection it looks more like an offset where it's reading the pixel data from (1,1) to (size+1,size+1) but the overflow size+1 is repeating the adjacent pixel?_

![Screenshot 2024-02-01 at 16 20 39](https://github.com/thorvg/thorvg/assets/17763524/652323fd-ad01-4b7d-938f-a4954e5a6f57)
Firefox on the left with expected appearance.

Test SVG:
![EmbeddedBitmap](https://github.com/thorvg/thorvg/assets/17763524/de17c713-2453-408c-a186-bac90327776c)

```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="500px" height="400px" viewBox="0 0 200 200" xml:space="preserve">
<image x="50" y="50" width="100" height="100" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
</svg>
```

**Comment by JSUYA** [comment]
@hermet I think, It looks like a problem with SwRaster's upScaler.
If you draw this 5x5 size image as a PicturePng example, you can get the same result.
(Images can be downloaded by pasting this addr into Chrome)
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==

**Comment by lostminds** [comment]
> I think, It looks like a problem with SwRaster's upScaler.

In https://github.com/thorvg/thorvg/blob/9a6eff8ce29dc2d338ff8cca1cd2934faadbeb62/src/renderer/sw_engine/tvgSwRaster.cpp#L251 

Could it be the case that the initial cast
```
auto rx = (size_t)(sx);
auto ry = (size_t)(sy);
```
is not setting rx and ry to floor(sx) and floor(sy) as I guess is intended, and instead returning something like ceil(sx) and ceil(sy)? 

But if that was the case the following dx and dy calculation should be wrong (reversed) with sx<rx etc, which should be apparent in the rendered result. However, since these values are cast to unsigned ints:
```
auto dx = static_cast<uint8_t>((sx - rx) * 255.0f);
auto dy = static_cast<uint8_t>((sy - ry) * 255.0f); 
```
this reversed dx and dy interpolation direction might be hidden when if the sign is removed somehow in this cast.

**Comment by hermet** [comment]
@lostminds Thanks, I'll revisit it soon, or perhaps you could contribute to the improvement? It seems you're quite knowledgeable in it. :-)

**Comment by lostminds** [comment]
Thank you for the invitation @hermet , but I do not feel I'm familiar enough with the project code base or the logistics of building, testing etc to be able to make a pull request of my own. I'm mostly interacting very indirectly with ThorVG by using it to render generated SVG code in a Godot-based parametric design project I'm working on.

**Comment by hermet** [comment]
No problem, thanks for reporting issues, we will check them soon.
