### ISSUE TITLE
[SVG] `fill="url(#a b)"` syntax is wrong so it should render as default, but renders the "a" ID instead

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1983]
`url(#id)` syntax is the only valid way to reference an id. Having whitespace after it should be okay as they should be trimmed, but having more characters after that shouldn't be ok and should make the fill render black.

**Comment by capnm** [comment]
The user agents seems to follow the association between emptiness, transparency, space, and blackness ;)

**Comment by MewPurPur** [comment]
SVG to show the bug:

`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a"><stop stop-color="#fac"/></linearGradient><rect width="16" height="16" fill="url(#a k)"/></svg>`

<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a"><stop stop-color="#fac"/></linearGradient><rect width="16" height="16" fill="url(#a k)"/></svg>

ThorVG Viewer shows it as pink.

**Comment by JSUYA** [comment]
@MewPurPur Thank you for your report. I didn't check to in detail.
“a k” was recognized as “a”.
This is because the space after the url should be ignored, but we recognized it as an ID until a space appears.
(id="a", "url(#a )" works fine.)
I will fix soon.

**Comment by capnm** [comment]
Test for both cases:
```xml
<svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg">
<defs>
  <linearGradient id="" x2="1">
    <stop stop-color="#0f0"/>
  </linearGradient>
  <linearGradient id="b" x2="1">
    <stop stop-color="#00f"/>
  </linearGradient>
  <linearGradient id="bl ack" x2="1">
    <stop stop-color="#ff0"/>
  </linearGradient>
</defs>

<rect width="160" height="160" fill="red"/>
<rect width="140" height="140" stroke="#f0f" stroke-width="10" fill="url(#)"/>
<rect width="40" height="100" stroke="#0ff" stroke-width="10" fill="url(#bl ack)"/>

</svg>
```
![image](https://github.com/thorvg/thorvg/assets/4047289/a410868a-28ac-4d3d-8c8f-da167cd5258c)

Web Browser:
![image](https://github.com/thorvg/thorvg/assets/4047289/342971c7-8755-48a3-b54b-b1bd7de9a4cd)
