### ISSUE TITLE
Divergence of starting points between SVG and Lottie standards

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#1997]
https://github.com/thorvg/thorvg/pull/1987#issuecomment-1953394872

#1987 and #1996 are fixes to meet the svg standard. Since the lottie starting points are defined differently, there needs to be added some 'shift'.

**Comment by hermet** [comment]
`appendShapes` is a utility function for app developers, whereas SVG/Lottie can directly utilize `appendPath` to compose any shapes in accordance with their specifications.
