### ISSUE TITLE
What technique is used to triangulate shapes?

### ISSUE THREAD

**Issue by sasmaster** [thorvg/thorvg#2011]
Hi.
I have found this awesome lib via google and I am curious what kind of tessellation algorithm is used under the hood. Is it offline triangulation on CPU? Or something like "stencil-then-cover" trick to triangulate in real time? 
Thanks.

**Comment by hermet** [comment]
@RuiwenTang @SergeyLebedkin

**Comment by RuiwenTang** [comment]
We have a triangulation algorithm and use it in the GL backend, but there are some cases that this algorithm can't handle, so we also use 'stencils and cover' method for those cases.

**Comment by SergeyLebedkin** [comment]
> Hi. I have found this awesome lib via google and I am curious what kind of tessellation algorithm is used under the hood. Is it offline triangulation on CPU? Or something like "stencil-then-cover" trick to triangulate in real time? Thanks.

Thank you for your interest in our project.
In WebGPU renderer we are using "stencil-then-cover" trick and compute shaders for final blend and composition
