### ISSUE TITLE
Incorrect outline for specific curve

### ISSUE THREAD

**Issue by detomon** [thorvg/thorvg#2015]
When converting [curve.svg](https://github.com/thorvg/thorvg/assets/4883379/c1007242-ce3e-4a68-9219-d23194c3fd1d) with `svg2png` the result looks incorrect:

![curve_bad](https://github.com/thorvg/thorvg/assets/4883379/4847f643-e270-48f7-807a-362887900629)

Expected:

![curve_good](https://github.com/thorvg/thorvg/assets/4883379/4f982eba-3488-4a22-8f79-ddeb630d22d2)

I bisected the commits and this one seems to be the culprit: https://github.com/thorvg/thorvg/commit/35ddc5fe5643042fcea8717a9e19ffab0b7e1033

**Comment by hermet** [comment]
@detomon the fix will be applied in v0.12.7, thanks.
