### ISSUE TITLE
Adding a web build test CI

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2043]
like other platforms, The Web CI build could prevents any breakage in WASM bindings.

![image](https://github.com/thorvg/thorvg/assets/3711518/398d9446-d5f6-4d0c-8479-d057d43eb0c0)

**Comment by tinyjin** [comment]
Hello, this is breif idea for supporting Web CI.

**Step 1. Supports basic installation & build pipeline**
- WASM build & player integration
- Dependency verification with `package.json`
- Verify registration (npm, unpkg and jsdeliver)

**Step 2. JS unit test**
In `web/example`, we have controller to check some cases for js-interface & wasm-binding.
- we can build those cases in test code
- https://www.npmjs.com/package/jest

**Step 3. Rendering test via [test-automation](https://github.com/thorvg/thorvg.test-automation)**

**Comment by hermet** [comment]
- The purpose of this is to prevent breakage due to intensive ThorVG changes.
- We can begin with the WASM build test to prevent API breakages.
- Test Automation is used for verifying the rendering regression tests of ThorVG. While it can be separate, it is integrated into CI instead.
