### ISSUE TITLE
Lottie: Animation Segment(Marker) Support

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2044]
The concept of using markers in Lottie animations is known, where markers are used to control animation playback by specifying start and end points without needing to know the exact frame numbers.

Sample:
[marker.json](https://github.com/thorvg/thorvg/files/14552673/marker.json)

API usage:
```
lottie->load("sample.json");

lottie->segment("sectionA") ;                    //specify the SectionA marked by Lottie spec.
auto frame = lottie->frameCnt();   //returns the "SectionA" frame count
auto duration = lottie->duration();  //returns the SectionA duration in seconds
...

lottie->segment(begin: 0.3, end: 0.7);        //specify the segment 0.3 ~ 0.7 ?
auto frame = lottie->frameCnt();       //returns the 0.3 ~ 0.7 frame count
auto duration = lottie->duration();    //returns the 0.3 ~ 0.7 duration in seconds
...

**Comment by hermet** [comment]
Acquire Marker List
```
uint32_t LottieAnimation::markerCnt();  //return the marker count
const char* LottieAnimation::markers(uint32_t idx); //return the marker name by a given index.
```

**Comment by fall2019** [comment]
Okay. I will add it.

**Comment by hermet** [comment]
@theashraf

> * Is there a way to determine the beginning and ending frame number of a given marker ? cause we have a use case where the user want to know the segment value for UI purposes

Makes sense. Probably, thorvg could provide an extra api:
```
//Return the begin, end values of the given marker.
Result LottieAnimation::segment(const char* marker, float* begin, float* end)
```

> * Would applying a segment or a marker update the animation total_frames and duration information we get from `tvg_get_total_frames` and `tvg_get_duration` apis ?

Yes.


I anticipate that dotLottie will replace the segment with the marker name. Could you please clarify in what scenarios dotLottie requires the use of this API?
```
Result LottieAnimation::segment(float begin, float end);  //Set the segment with a specific range.
```

**Comment by theashraf** [comment]
@hermet

In dotLottie, we offer support for both named segments (Markers) and standard segments. So, the following API would be beneficial:

```cpp
Result LottieAnimation::segment(float begin, float end);
```

This is useful in scenarios where users want to specify a custom segment for playback that does not have an associated named marker within the Lottie JSON
