### ISSUE TITLE
Storing the address of local variable

### ISSUE THREAD

**Issue by kisvegabor** [thorvg/thorvg#2051]
Hi,

While compiling ThorVG for ESP32 I get this warning (converted to error):

```
error: storing the address of local variable 'context' in '*this.LottieParser::context' [-Werror=dangling-pointer=]
 1255 |     this->context = &context;
```

**Comment by hermet** [comment]
@kisvegabor hello, you might wanna confirm fix by this https://github.com/thorvg/thorvg/pull/2052
