### ISSUE TITLE
thorvg msys2 package support

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2081]
https://packages.msys2.org/package/

**Comment by vtorri** [comment]
i have created the package. List of installed files : 

```
$ find .
.
./bin
./bin/libthorvg-0.dll
./bin/lottie2gif.exe
./bin/svg2png.exe
./bin/svg2tvg.exe
./include
./include/thorvg.h
./include/thorvg_capi.h
./include/thorvg_lottie.h
./lib
./lib/libthorvg.dll.a
./lib/pkgconfig
./lib/pkgconfig/thorvg.pc
./share
./share/licenses
./share/licenses/thorvg
./share/licenses/thorvg/LICENSE
```

I have tried svg2png with tiger.svg and lottie2git with lottieslot.json and they work

compilation : 

```
 meson setup \
      --prefix="${MINGW_PREFIX}" \
      --wrap-mode=nodownload \
      --buildtype=release \
      -Ddefault_library=shared \
      -Dloaders=all \
      -Dsavers=all \
      -Dbindings=capi \
      -Dtools=all \
      -Dtests=true \
      ../${_realname}-${pkgver}
```

if it's ok, i'll submit the package

**Comment by hermet** [comment]
@vtorri Thanks, one thing, -Dtests looks unnecessary for the packaging.

**Comment by vtorri** [comment]
@hermet not unnecessary : meson test is performed after the build. It enforces that at least the tests are passing

**Comment by hermet** [comment]
@vtorri looks good to me.

**Comment by hermet** [comment]
https://github.com/msys2/MINGW-packages/commit/3740bfbba029468ccfe0bf84a97829cea916c268

**Comment by hermet** [comment]
@vtorri Thanks. I'm not a big fan of MSYS2, but once this is accepted, we can probably add the installation guide alongside the 'Install with vcpkg' section.

![image](https://github.com/thorvg/thorvg/assets/3711518/ee8f7e70-4992-483f-b6dd-70f6b0e425b2)
