### ISSUE TITLE
Thin rounded rectangle path stroke artifacts

### ISSUE THREAD

**Issue by lmdsp** [thorvg/thorvg#2088]
This simple svg just draws a 1px stroke rounded rectangle path using lines and cubics.

```svg
<svg width="58" height="19" viewBox="0 0 58 19" fill="none" version="1.1" id="svg7" xmlns="http://www.w3.org/2000/svg">
   <path
      d="m 9.5,0.5 h 39 c 4.9706,0 9,4.02944 9,9 0,4.9706 -4.0294,9 -9,9 h -39 c -4.97056,0 -9,-4.0294 -9,-9 0,-4.97056 4.02944,-9 9,-9 z"
      stroke="#ffffff" id="path5" />
</svg>
```

This is the rendered image in ThorVG 0.12.9 with no scaling applied.
As can be seen the corners seem quite off

![rounded](https://github.com/thorvg/thorvg/assets/1681470/273511b4-629b-4aff-b926-84a2d7403149)

If we inspect this more closely in [pixspy](https://pixspy.com/),
we can notice that the pixel coverage isn't uniform across the stroke.

<img width="574" alt="image" src="https://github.com/thorvg/thorvg/assets/1681470/b0b0921c-5545-4593-b203-d2e8104ca2bd">

This is how the same svg looks renderered by [svgviewer](https://www.svgviewer.dev/) running in Chrome:

<img width="407" alt="image" src="https://github.com/thorvg/thorvg/assets/1681470/585d1553-64bb-4a50-9a68-aed9232df8c4">

The problem gradually fades away as the stroke width is increased. As thin strokes are very commonplace in UI design I believe this is quite an important issue.

**Comment by hermet** [comment]
Somehow, the software renderer compromises quality for performance, this is more of a quality issue than a bug, instead you can observe the svgviewer doesn't seem to render 1-pixel widths accurately.

**Comment by lmdsp** [comment]
@hermet I did more tests and found out that the rendering looks quite perfect when using straight alpha `tvg::SwCanvas::ABGR8888S`. 

![rounded_thor](https://github.com/thorvg/thorvg/assets/1681470/993e38e7-2166-4d0c-a217-e5b8044cf1b1)

For comparison this is the same rendered with [LunaSVG](https://github.com/sammycage/lunasvg)

![rounded_luna](https://github.com/thorvg/thorvg/assets/1681470/b2047350-952b-41a8-bd3c-f1dad04fd715)

Perhaps it's a bug in our rendering engine that doesn't handle pre-multiplied alpha correctly (although it should). 

I saw this parameter documentation from `Picture::load(uint32_t* data, uint32_t w, uint32_t h, bool copy) noexcept` at line 1318 that seems to be left over from a previous version
`* @param[in] premultiplied If @c true, the given image data is alpha-premultiplied.`
Could this be related in any way ?

**Comment by hermet** [comment]
@lmdsp it makes sense that the rendering result appears darker than expected when the option is not properly configured. If you're integrating a native system that expects straight (unpremultiplied alpha) images for composition, you'll need to configure the canvas using `tvg::SwCanvas::ABGR8888S`. This setting is optional because some systems support straight alpha, while others support pre-multiplied alpha. Otherwise, both ways are supported. So I think you just need to use the straight mode. That's all. The `load()` function you mentioned is not relevant to vector drawing.
