### ISSUE TITLE
Masking display incorrectly

### ISSUE THREAD

**Issue by JSUYA** [thorvg/thorvg#209]
In Masking.cpp example.
When mask object has transparency, the result wrong display.
Alpha is applied to the stroke and fill of the target.

Test code
```cpp
diff --git a/src/examples/Masking.cpp b/src/examples/Masking.cpp
index 8d517ef..fc942d7 100644
--- a/src/examples/Masking.cpp
+++ b/src/examples/Masking.cpp
@@ -52,13 +52,14 @@ void tvgDrawCmds(tvg::Canvas* canvas)
     star->lineTo(426, 161);
     star->lineTo(546, 143);
     star->close();
-    star->stroke(10);
+    star->stroke(30);
     star->stroke(255, 255, 255, 255);
 
     //Mask3
     auto mask3 = tvg::Shape::gen();
     mask3->appendCircle(600, 200, 125, 125);
-    mask3->fill(255, 255, 255, 255);
+    mask3->fill(255, 255, 255, 125);
+    //or mask3->opacity(125);
     star->composite(move(mask3), tvg::CompositeMethod::AlphaMask);
     if (canvas->push(move(star)) != tvg::Result::Success) return;

```
![image](https://user-images.githubusercontent.com/7413838/104146224-573f3400-540d-11eb-80b8-dea02830b8fd.png)

**Comment by hermet** [comment]
Looks this is correct behavior as masking just doing as it's role.  masking should not change its source's behavior.

**Comment by hermet** [comment]
Sorry, I misunderstood.

**Comment by mgrudzinska** [comment]
TODO:
- Translucent linear gradient
- Opaque radial gradient
- Translucent radial gradient
- antialiasing in opaque linear gradient

**Comment by mgrudzinska** [comment]
#326 should close the subject of the gradient shapes with masks

**Comment by mgrudzinska** [comment]
@hermet @JSUYA @patrykka 

I have a question - how should the expected result of the following code look like?

```
        //-------------------------------------------
        auto shape1 = tvg::Shape::gen();
        shape1->appendRect(400, 0, 400, 400, 0, 0);
        shape1->fill(255, 0, 0, 255);

        //Alpha Mask
        auto mask1 = tvg::Shape::gen();
        mask1->appendCircle(600, 200, 180, 180);
        mask1->fill(0, 0, 0, 127);

        shape1->composite(move(mask1), tvg::CompositeMethod::AlphaMask);
        canvas->push(move(shape1));

        //-------------------------------------------
        auto shape2 = tvg::Shape::gen();
        shape2->appendRect(0, 0, 400, 400, 0, 0);
        shape2->fill(255, 0, 0, 255);

        //Inv Alpha Mask
        auto mask2 = tvg::Shape::gen();
        mask2->appendCircle(200, 200, 180, 180);
        mask2->fill(0, 0, 0, 127);

        shape2->composite(move(mask2), tvg::CompositeMethod::InvAlphaMask);
        canvas->push(move(shape2));
```

1. the current result from tvg (inv mask - left, mask - right):
![inv_pyt](https://user-images.githubusercontent.com/67589014/114069163-f8b81380-989e-11eb-87e1-b3488863cd6e.PNG)

2. I'd expect this one (inv mask - left, mask - right):
![inv_pyt_exp](https://user-images.githubusercontent.com/67589014/114069188-ff468b00-989e-11eb-9872-b534dcd4dcb8.PNG)

3. or this one (inv mask - left, mask - right):
![inv_pyt_exp2](https://user-images.githubusercontent.com/67589014/114070576-73356300-98a0-11eb-849b-ab7bc981f44b.PNG)

Our current version doesn't seem to be consistent for me. I think the **third one** is the correct one.

**Comment by mgrudzinska** [comment]
@JSUYA what do you think?
There are my current results, but I still have to improve the code:

left - mask,      right - inv mask
![mask_inv_ok](https://user-images.githubusercontent.com/67589014/114327883-23be9380-9b3b-11eb-8bdb-842a0553ed70.PNG)

**Comment by mgrudzinska** [comment]
#337

**Comment by hermet** [comment]
just checked, it's still valid issue.

**Comment by mgrudzinska** [comment]
@JSUYA @hermet please check after #519 and #520 are merged.
just to make sure that I understood the problem in this issue correctly

**Comment by hermet** [comment]
Probably same issue: https://github.com/thorvg/thorvg/issues/1423
