### ISSUE TITLE
Ask for help how to use SvgLoader

### ISSUE THREAD

**Issue by zengzm1212** [thorvg/thorvg#2097]
![image](https://github.com/thorvg/thorvg/assets/59642136/b71ff066-b7d2-4cf7-a1f6-9a691314488f)

![image](https://github.com/thorvg/thorvg/assets/59642136/fe58b988-5bd6-4ead-b276-31873842e4da)

When I use thorvg to load an svg file, if the svg file has the **Viewbox** flag, it will not execute run(0); and this function will actually parse the svg file and build the root scene. I would like to ask how to get the file information with **Viewbox** flag?
Thanks!

PS: The above two functions are in tvgSvgLoader.cpp.

**Comment by JSUYA** [comment]
Hi @zengzm1212  Thank you for your interesting.
If the viewbox flag is set, run() will be called appropriately depending on the TaskScheduler.
The reason run(0) is called when there is no viewbox flag is to search the height, width attribute and internal elements and predict the size of the svg in advance.
Is there anything you would like to improve?
Can you ask a more detailed question?
What file information do you want?
The viewbox flag is set when the viewbox attribute is declared in _attrParseSvgNode.

**Comment by zengzm1212** [comment]
My specific scenario is that I have an svg file and I want to import it to obtain its contours, edges and other geometric information.  Could you provide an example? Thanks!

**Comment by JSUYA** [comment]
> My specific scenario is that I have an svg file and I want to import it to obtain its contours, edges and other geometric information. Could you provide an example? Thanks!

You can use bounds() and size() API. `contours` is unsupported.

```cpp
    auto picture = tvg::Picture::gen();
    picture->load(/*SVG FILE PATH*/);

    float _x, _y, _w, _h;
    picture->size(&_w, &_h);
    printf("size : %f %f\n", _w, _h);
    picture->bounds(&_x, &_y, &_w, &_h);
    printf("bounds : %f %f %f %f\n",_x, _y, _w, _h);
```

**Comment by hermet** [comment]
@zengzm1212, Basically ThorVG has been designed to provide the complete SVG scene image. Note that (just in case) the Accessor class allows users to traverse the picture (SVG) scene tree. You can probably acquire path commands and vertex coordinates information from it, although I don't recommend doing so because it's difficult to understand the overall scene context without a current understanding of the SVG data context. See Accessor.cpp in src/examples. 

```
/**
 * @class Accessor
 *
 * @brief The Accessor is a utility class to debug the Scene structure by traversing the scene-tree.
 *
 * The Accessor helps you search specific nodes to read the property information, figure out the structure of the scene tree and its size.
 *
 * @warning We strongly warn you not to change the paints of a scene unless you really know the design-structure.
 *
 * @since 0.10
 */
class TVG_API Accessor final
{
public:
    ~Accessor();

    /**
     * @brief Set the access function for traversing the Picture scene tree nodes.
     *
     * @param[in] picture The picture node to traverse the internal scene-tree.
     * @param[in] func The callback function calling for every paint nodes of the Picture.
     *
     * @return Return the given @p picture instance.
     *
     * @note The bitmap based picture might not have the scene-tree.
     */
    std::unique_ptr<Picture> set(std::unique_ptr<Picture> picture, std::function<bool(const Paint* paint)> func) noexcept;

    /**
     * @brief Creates a new Accessor object.
     *
     * @return A new Accessor object.
     */
    static std::unique_ptr<Accessor> gen() noexcept;

    _TVG_DECLARE_PRIVATE(Accessor);
};
```
