### ISSUE TITLE
ThorVG freezes completely if an equal sign is in certain places

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#2116]
`<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><circle =r="1"/></svg>`

ThorVG Viewer will stop responding if this is given to it.

The bug has existed for a long time; I can reproduce this in Godot 4.2.1 which uses a version of ThorVG that's 3+ months old.

**Comment by hermet** [comment]
culprit:
```
commit 7ab5cb90aa1eecf68b9fbe5919322313d7fa43c7
Author: Hermet Park <hermet@lottiefiles.com>
Date:   Mon Dec 11 16:22:23 2023 +0900

    infra: renamed the folders, images -> resources.

    these folders might have more than images.
```

**Comment by hermet** [comment]
@JSUYA Probably, you can help this issue, it's fall in the infinite loop by this:
```
 =r="1"/>
```
![image](https://github.com/thorvg/thorvg/assets/3711518/5f1a1aa5-bd03-4783-8a17-92b501e837ac)
