### ISSUE TITLE
SVG stroke-width with a percentage uses the width instead of the diagonal over sqrt(2)

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#2131]
https://svgwg.org/svg2-draft/painting.html#StrokeWidth

![image](https://github.com/thorvg/thorvg/assets/85438892/1be3fed5-641d-4477-9ad2-8ca71d248d31)

Example: `<svg width="100" height="50" xmlns="http://www.w3.org/2000/svg"><rect x="15" y="15" width="70" height="20" fill="none" stroke="#def" stroke-width="10%"/><rect x="15" y="15" width="70" height="20" fill="none" stroke="#fac" stroke-opacity=".6" stroke-width="10"/></svg>`

Conforming to the SVG specification, 10% should amount to ~7.9px, as shown below - the two rects don't perfectly align. This isn't the case if you test this with ThorVG viewer right now. There may be more attributes with this flaw.

![image](https://github.com/thorvg/thorvg/assets/85438892/bf6f947d-1d4d-471a-9210-7186014d52a6)

**Comment by hermet** [comment]
ThorVG:
![image](https://github.com/user-attachments/assets/3a753c67-e6b9-4ab7-87a1-55511463d3c7)

**Comment by MewPurPur** [comment]
Yeah, this is wrong. The rectangles shouldn't align perfectly. You're taking 10% of the width, when stroke-width is not an x or y-based. The specification says that such attributes should be based on the diagonal length.

**Comment by hermet** [comment]
@MewPurPur @JSUYA The fix will be in v0.15.0. Thanks.
