### ISSUE TITLE
AVX: examples shows up black screen when AVX is enabled.

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2146]
- [ ] Performance
- [ ] Masking

**Comment by hermet** [comment]
8bits rasterization is missing in avxRasterTranslucentRle()

**Comment by hermet** [comment]
@rinechran you might be interested in this ?

**Comment by rinechran** [comment]
That's interesting, but can i start working on it next week?

**Comment by hermet** [comment]
It is an open task, no pushing.
