### ISSUE TITLE
Update vcpkg-related Package-Distribution.md

### ISSUE THREAD

**Issue by rinechran** [thorvg/thorvg#2161]
Since PRs cannot be submitted to a wiki, a separate repository was created and the issue has been resolved. Please refer to this for your information.

https://github.com/rinechran/thorvg_wiki/blob/main/Package-Distrubution.md

**Comment by hermet** [comment]
@rinechran thanks, updated. Please double-check here: https://github.com/thorvg/thorvg/wiki/Package-Distrubution
