### ISSUE TITLE
lottie: support missing Advanced Text feature

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2178]
- [x] Range Selector https://lottiefiles.github.io/lottie-docs/text/#text-range
- [x] Alignment Options https://lottiefiles.github.io/lottie-docs/text/#text-alignment-options

**Comment by tinyjin** [comment]
The Text Advanced Feature aims to resolve broken texts in Lottie.

In the early stages of this process, text rendering was improved by fixing text grouping and newly supporting the Text Tracking feature.

See also:
- Text Tracking Support :#2254
- Text Alignment/Justification Correction : #2218

**Comment by tinyjin** [comment]
The full support for Text Range Selector will be gradually added in the following steps.

### Phase 1
Initial & Partial Support
- Text Range Selector (Units)
- Text Style (Color, Opacity, Width, Transform)

### Phase 2
Full Support of Text Style
- Hue, Saturation, Brightness, Blur, Spacing

### Phase3
Full Support of Range Selector
- Easing, Randomize, Shape, Smoothness, Text Based, Max Amount

**Comment by hermet** [comment]
@mgrudzinska, could you please share any resource that addresses the bug fixed by this commit?

**Comment by hermet** [comment]
Separated the text path as it is uncommon: https://github.com/thorvg/thorvg/issues/2888
