### ISSUE TITLE
svg: a regression bug

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2206]
This breaks the rendering: https://github.com/thorvg/thorvg/pull/2148

```
commit 938946d3ba514f9950ca6e2da4411cb5d79e17a3 (HEAD)
Author: JunsuChoi <jsuya.choi@samsung.com>
Date:   Fri Apr 5 13:42:02 2024 +0900

    loader/svg: Skip to invalid polygon

    If a Polygon's points array is odd, it is not a valid shape.
```

![image](https://github.com/thorvg/thorvg/assets/3711518/ea811a40-853c-4e0a-94e5-81fdbd65c718)

**Comment by JSUYA** [comment]
um... In my environment, svg works fine.
https://github.com/thorvg/thorvg/pull/2148 patch is no longer drawn if polygon type elements's points array do not match in pairs. Therefore, it has nothing to do with color change.
And `gallardo.svg`, which is displayed incorrectly, does not use the polygon element.
`152932619-bd3d6921-72df-4f09-856b-f9743ae32a14.svg` displayed fine using polygon elements in my environment.

It's strange that `1630446379Bahamas-patriotic-flag-symbol.svg` is reversed.

**Comment by hermet** [comment]
@JSUYA Please try it with `-Dlog=true`

**Comment by JSUYA** [comment]
oh! ok i found it. i will make pr soon. thanks

**Comment by mgrudzinska** [comment]
https://github.com/thorvg/thorvg/pull/2212
