### ISSUE TITLE
question about source code

### ISSUE THREAD

**Issue by rinechran** [thorvg/thorvg#2214]
1. rw.invalid is true. Are there any conditions under which it becomes false?

https://github.com/thorvg/thorvg/blob/568846491da025b57823adc63ae4920c6e7c7eef/src/renderer/sw_engine/tvgSwRle.cpp#L924 

2 I'm not very knowledgeable about this, so I don't understand the purpose of bandSize and Cell.

https://github.com/thorvg/thorvg/blob/568846491da025b57823adc63ae4920c6e7c7eef/src/renderer/sw_engine/tvgSwRle.cpp#L931

https://github.com/thorvg/thorvg/blob/568846491da025b57823adc63ae4920c6e7c7eef/src/renderer/sw_engine/tvgSwRle.cpp#L913

**Comment by hermet** [comment]
@rinechran Hello.
1. The maintainers here are all busy with plenty of tasks. If you have any issue on that, please come up with the context. 
2. It can be quite challenging and frustrating to explain the difficult parts to someone who is unfamiliar with the basic code. In my experience, understanding complex logic directly from the code can be more intuitive and easier than following verbal instructions. If you consider yourself an experienced programmer, please review the code carefully.
