### ISSUE TITLE
lottie: support "skew" property

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2262]
ThorVG is missing support for these two properties:
`sk`: Skew amount as an angle in degrees
`sa`: Direction at which skew is applied, in degrees (0 skews along the X axis, 90 along the Y axis)

Please refer: https://lottiefiles.github.io/lottie-docs/concepts/#transform

Entry points to implement:
```
LottieTransform* LottieParser::parseTransform(bool ddd)  //tvgLottieParser.cpp
bool _updateTransform(LottieTransform* transform, float frameNo, bool autoOrient, Matrix& matrix, uint8_t& opacity, LottieExpressions* exps) //tvgLottieBuilder.cpp
```

**Comment by mgrudzinska** [comment]
<img width="697" alt="Zrzut ekranu 2024-05-15 o 01 42 00" src="https://github.com/thorvg/thorvg/assets/67589014/d19a8da1-190b-4b96-ab9e-d92b1a6d4327">
 
but I didn't find a viewer supporting skew in repeater
