### ISSUE TITLE
Always get Invalid argument error while loading svg files on Windows

### ISSUE THREAD

**Issue by GTSKA** [thorvg/thorvg#2301]
[TestThorVG.zip](https://github.com/thorvg/thorvg/files/15392543/TestThorVG.zip)
I tried both using my own code and other's as https://github.com/mmaciola/thorvg-freeglut, however whenever I play the program I get the same error. SVG works, as far as I know since I've been able to draw basic shapes such as circles, however even the star shape example marks some compilation error and loading svg files always result in the same error "InvalidArguments"

**Comment by hermet** [comment]
related: https://github.com/thorvg/thorvg/issues/1244

**Comment by hermet** [comment]
@GTSKA Hello, some questions.
1. Which api returns InvalidArgument? Is this right in your test code?
![image](https://github.com/thorvg/thorvg/assets/3711518/feaa27c5-54c0-45d4-a150-b8b0b47a806d)
2. Could you please share the meson build option did you use? 
3. Could you please confirm that `tiger.svg` file exists in the same folder of your executable program?

**Comment by GTSKA** [comment]
1. Correct load triggers that issue, I tried relative path, absolute path and also this as done in SVGToPNG
`const char* realFile(const char* path)
{
    //real path
#ifdef _WIN32
    path = _fullpath(full, path, PATH_MAX);
#else
    path = realpath(path, full);
#endif
    return path;
}`
2.I'm trying to compile calling the .lib into a vs project, but before I generated the library using `meson setup builddir --backend=vs`
3.As mentioned before I can confirm the file does exist either on the same program path, folder inside C, pasted on several posible locations. Using both relative and absolute paths and even like that all the times it failed

**Comment by hermet** [comment]
@GTSKA could please copy the builddir\config.h here?

**Comment by GTSKA** [comment]
![image](https://github.com/thorvg/thorvg/assets/2157894/64ae8409-e86e-4cb9-9e4f-f57886534c1f)

**Comment by GTSKA** [comment]
somehow before entering that function all seems fine, once it enters string gets corrupted and then marks that the path is empty

**Comment by hermet** [comment]
@GTSKA please double check the path your side. i think the root point is there.

**Comment by GTSKA** [comment]
could it be on how the thorvg is compiled? like building issues? the problem seems related to that

**Comment by hermet** [comment]
@GTSKA if the path is empty, i don't think so. please double check how you made the `path` here. 
![image](https://github.com/thorvg/thorvg/assets/3711518/6a7b91b3-d5b6-4b34-a312-b98d7d4f5fbb)

**Comment by GTSKA** [comment]
[TestThorVG.zip](https://github.com/thorvg/thorvg/files/15420421/TestThorVG.zip)
`std::string path = "tiger.svg";
        auto real_path = realFile(path.c_str());
        int ret = 0;
        if (real_path) {
            if (isDirectory(real_path)) {
                //load from directory
                cout << "Trying load from directory \"" << real_path << "\"." << endl;
                if ((ret = handleDirectory(real_path)))
                {
                }

            }
            else if (svgFile(path.c_str())) {
                //load single file
                if ((ret = renderFile(real_path)))
                {
                }
            }
            else {
                //not a directory and not .svg file
                cout << "Error: File \"" << path << "\" is not a proper svg file." << endl;
            }

        }`
I used svg2png code here, as mentioned earlier

**Comment by hermet** [comment]
Please do debugging if you think you are a good programmer.

**Comment by GTSKA** [comment]
more likely i'm not a good programmer, besides breakpoints and variable inspection I can't give you more info from my debugging, That's why i first raised the ticket in discussion but there I was suggested that could be an issue from thorvg, not on my side.

**Comment by hermet** [comment]
@GTSKA The path is standard C++, not ThorVG. Building the path is the user's responsibility, not ThorVG's. I have already suggested the sample code for you. That code is perfectly work here and there, but only you have a trouble. Now, I believe you can at least try to debug it line by line to see which code line might be causing the issue rather than saying "I'm not a good programmer"

**Comment by GTSKA** [comment]
What I'm trying to explain is that I overwrote my code twice with suggested examples and is still not running it breaks when calling the functions from the generated .lib file I made, you keep insisting on me sending and invalid path when my question has been beside that, I've been debugging and it breaks when entering to the lib, could be even a corrupt .lib or not properly set, the point is that I can't advance from that point I sent evidence that the string is working then is sent and it brokes, not sure what could be either an architecture issue or something else. I checked on other forums and more people mentioned to have issues with the library, that ok I can understand bay get solved by using EFL, but as I said my intention was to not use EFL and understand if I was messing up while creating the .lib so it corrupts the path string when the function is called. I get you won't get paid for helping me, yet I asked for help because I don't understand what's going on, thanks for your time. And sorry if you think I'm somehow attacking you

**Comment by hermet** [comment]
Non taken, Non offense. Probably I misunderstood your situation from the beginning. https://github.com/orgs/thorvg/discussions/2299

Now, you think this issue is about compilation / linking problem. I'm sure if the compilation didn't make it properly,  or a certain linking issue is there, then app wouldn't be launched at all.

Please clarify these points:
a. please place the thorvg dll in the same folder of your executable(program).
b. If [b] doesn't work, please build thorvg with `-Ddefault_library=static`
c. if [c] doesn't work please double-check with thorvg "tools" whether they are working good or not. You can build them with the option `-Dtools=all` You can find out the compiled tools such as `lottie2gif`, `svg2png` etc.  Please put the thorvg dll in one of the executable folder and then try it.

**Comment by hermet** [comment]
@GTSKA Hello, I tested again with Visual Studio 2022 on Windows, and `tools` works perfectly. I think there might be something wrong with your system. I used the Meson `--backend=vs` option. The tests on Windows have been accomplished with several systems including CI automation, local tests, other projects, and many other contributors who are based on Windows. Please try testing on another machine.
