### ISSUE TITLE
Refactoring the renderer - raster engines.

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2313]
Time to clean up the code. In order to maintain code, data structure consistency, it is necessary to unify the following separate definitions:

```
Point / GlPoint / WgPoint
```

There are two possible approaches:

1. Add the necessary math functions in `renderer/tvgMath.h` and retain them as `Point`.
2. Introduce `RenderPoint` inheriting `Point` in `tvgRender.h`, add the necessary point methods to it, and replace all `Point`/`GlPoint`/`WgPoint` usages inside ThorVG with `RenderPoint`

**Comment by hermet** [comment]
cc @SergeyLebedkin @RuiwenTang

**Comment by RuiwenTang** [comment]
I prefer the first option, it also reduces some binary size ：）
