### ISSUE TITLE
lottie: incorrect polystar transform direction

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2328]
the rotation direction should be CW, not CCW? The direction is not matched with lottie-web.
[polystar_anim.json](https://github.com/thorvg/thorvg/files/15478118/polystar_anim.json)

**Comment by mgrudzinska** [comment]
AE (same as in ThorVG):
![May-29-2024 20-40-04](https://github.com/thorvg/thorvg/assets/67589014/b3191f1e-bd38-40a2-8d33-4d8b7eaf235b)
