### ISSUE TITLE
lottie: high cpu usage causing a browser freeze 

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2332]
I noticed very high CPU usage when playing this animation on dotlottie-rs: [notification.json](https://github.com/thorvg/thorvg/files/15495049/notification.json).

When playing in the browser, the browser freezes. I observed the same issue with the thorvg viewer.

Related issue: [https://github.com/LottieFiles/dotlottie-web/issues/221](https://github.com/LottieFiles/dotlottie-web/issues/221)

**Comment by hermet** [comment]
Huge size shapes with range [503005.187500 ~ -605279.125000] significantly affect the RLE segmentation performance.

**Comment by baseplate-admin** [comment]
Hi @hermet, the file seems to play with [`lottie-player`](https://www.npmjs.com/package/@lottiefiles/lottie-player)
