### ISSUE TITLE
TVG image format enhancement

### ISSUE THREAD

**Issue by FASTSHIFT** [thorvg/thorvg#2348]
Hi, do we have plans to add more attributes to the tvg format? 
For example, `use` and `group`, `xlink` and primitive shapes: `rect`, `circle`, so that after the image is loaded successfully, Users can change the content of the image by modifying the referenced properties, such as shape and color, rather than just displaying a static image, to prepare for later SVG animation.

**Comment by FASTSHIFT** [comment]
> Hello, you might wanna check `class Accessor`. Please have a look at this for it: #2055

Yes, this matches my needs.

> TVG Scene and SVG DOM are not 1:1 matched. If you are expecting SVG (SMIL) animation, it won't be compatible.

If we only record the reference relationship, there should be no need to retain the DOM structure, right? We only need to add an additional data structure to record the reference name, and look up the referenced drawing properties according to the name (ID) when drawing.

> We are considering supporting binary-based animation in the TVG format.

Is it similar to SMIL? Add the start and end points and animation time attributes to tvg. Is there an API to dynamically modify the attributes? For example, let the animation support change according to the sensor data.

**Comment by hermet** [comment]
> If we only record the reference relationship, there should be no need to retain the DOM structure, right? We only need to add an additional data structure to record the reference name, and look up the referenced drawing properties according to the name (ID) when drawing.

On the SVG side, references are closely tied to the nodes, and those nodes cannot exist in the ThorVG scene tree.



> Is it similar to SMIL? Add the start and end points and animation time attributes to tvg. Is there an API to dynamically modify the attributes? For example, let the animation support change according to the sensor data.

No similar SMIL. but a general vector animation which could be the most compact structure based on the thorvg engine but it will be able to support those dynamic property changes.

@FASTSHIFT By the way, you can currently use Lottie Animation for that. ThorVG will soon support dynamic property changes as well, as you can see in this sample: https://github.com/thorvg/thorvg/issues/2055. Alternatively, you might be interested in dotLottie animation, which is more functional for user interactions, theming, state changes, etc. Please check it out. Currently it's Rust-based but it could be a better option for you.

dotlottie?: https://dotlottie.io/intro/
dotlottie showcases: https://lottiefiles.github.io/dotlottie-web/

**Comment by FASTSHIFT** [comment]
Thank you for your answer~
