### ISSUE TITLE
lottie: not rendering

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2349]
I'm not able to play this animation on thorvg viewer, any idea ? 

[test.json](https://github.com/user-attachments/files/15531971/test.json)

**Comment by tinyjin** [comment]
Thank you @theashraf for reporting.

In my machine, `EXE_BAD_ACCEES` has caused.
![CleanShot 2024-06-03 at 19 03 19@2x](https://github.com/thorvg/thorvg/assets/11167117/470856f8-042c-4c76-b08a-34d2937a67bf)

Seems like the animation faces infinite loop between `_updateMatte` and `_updateLayer`.
![CleanShot 2024-06-03 at 19 03 00@2x](https://github.com/thorvg/thorvg/assets/11167117/1d53552a-8c6a-43b8-820a-389308180c95)

**Comment by tinyjin** [comment]
This code line occurs the incorrect loop.

```cpp
if (!_updateMatte(root, layer, frameNo, exps)) return;
```

Without this, it goes render, but matte is broken.
![CleanShot 2024-06-03 at 19 08 35](https://github.com/thorvg/thorvg/assets/11167117/54de3b40-784b-4947-ac61-de64ebbe16d1)

**Comment by mgrudzinska** [comment]
@theashraf already fixed on main, will be present in v0.13.7
