### ISSUE TITLE
Text in svg cannot be displayed correctly

### ISSUE THREAD

**Issue by zengzm1212** [thorvg/thorvg#2350]
Below is the svg file I used for testing
![svg_text](https://github.com/thorvg/thorvg/assets/59642136/bbff97c7-0b71-4a12-89b1-10979f36bcc4)

**Comment by hermet** [comment]
System font is required. It is currently out of ThorVG's spec support.

**Comment by zengzm1212** [comment]
@hermet  Could you load the text information into svgloader first?

**Comment by hermet** [comment]
@zengzm1212 figuring out the system font in thorvg side is not simple. Let's see. :-)

**Comment by hermet** [comment]
@zengzm1212 Alternatively, your app? is direcltly able to load the system font using the ThorVG Text API. This will likely enable SVG to support this text soon.

**Comment by zengzm1212** [comment]
![image](https://github.com/thorvg/thorvg/assets/59642136/b0378325-07f1-4fe7-8392-f974359f298c)

I want to use SvgLoader to load the information in svg and then convert it into my own data structure, but I found that the corresponding SvgNode is not generated when loading text.
I'm going to simply add a TextNode for myself.  Anyway, thank you very much for your answers.

**Comment by hermet** [comment]
@zengzm1212 see -> https://github.com/thorvg/thorvg/pull/2246/files

**Comment by mgrudzinska** [comment]
@zengzm1212 can you please confirm whether we can close this issue? 
[the text node support](https://github.com/thorvg/thorvg/pull/2362) is already merged  into main, will be present in v0.13.8
