### ISSUE TITLE
CAPI: Support the Text

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2374]
### Discussed in https://github.com/orgs/thorvg/discussions/2340

<div type='discussions-op-text'>

<sup>Originally posted by **Jean-Amaro** June  1, 2024</sup>
Is there a way to create a text, using the C-API, similarly to what `tvg::Text` does in C++?</div>

**Comment by mgrudzinska** [comment]
```
TVG_API Tvg_Paint* tvg_text_new(void);
TVG_API Tvg_Result tvg_text_font(Tvg_Paint* paint, const char* name, float size, const char* style);
TVG_API Tvg_Result tvg_text_set_text(Tvg_Paint* paint, const char* text);
TVG_API Tvg_Result tvg_text_set_fill_color(Tvg_Paint* paint, uint8_t r, uint8_t g, uint8_t b);
TVG_API Tvg_Result tvg_text_set_linear_gradient(Tvg_Paint* paint, Tvg_Gradient* gradient);
TVG_API Tvg_Result tvg_text_set_radial_gradient(Tvg_Paint* paint, Tvg_Gradient* gradient);
TVG_API Tvg_Result tvg_load_font(const char* path);
TVG_API Tvg_Result tvg_unload_font(const char* path);
```

**Comment by hermet** [comment]
@mgrudzinska  

It seems like there could be some debate over whether we should attach the `text` prefix or not.
```
TVG_API Tvg_Result tvg_text_load_font(const char* path);
TVG_API Tvg_Result tvg_text_unload_font(const char* path);
```
Probably, we can also consider skipping the `font` postfix name.
```
TVG_API Tvg_Result tvg_text_load(const char* path);
TVG_API Tvg_Result tvg_text_unload(const char* path);
```

**Comment by mgrudzinska** [comment]
@hermet of, do you want me to change to```tvg_text_load``` and ```tvg_text_unload``` right away or discuss it first?

```tvg_text_set_fill_color``` and ```tvg_text_set_linear_gradient``` - I used the names exactly like for shapes, although shapes naming in't perfect, because ```tvg_text_set_linear_gradient``` seems to be missing 'fill' (compare to stroke's apis:
```tvg_shape_set_stroke_color``` and ```tvg_shape_set_stroke_linear_gradient```)

**Comment by hermet** [comment]
> of, do you want me to change to`tvg_text_load` and `tvg_text_unload` right away or discuss it first?

@mgrudzinska I strongly suggest that API/new feature design consensus should come first, followed by the code (PR).

**Comment by mgrudzinska** [comment]
I've changed pr to draft, it's ready, but I need to polish it after we decide what names to use etc

```tvg_text_load``` - for now we use ```text``` as a name of the object type, also as a string we want to write. if we keep this name it will also refer to a font file. imo confusing, but maybe for other it's not.

**Comment by mgrudzinska** [comment]
@hermet do you think this is the moment when you can decide on the names? So I could apply changes and mark [this pr ](https://github.com/thorvg/thorvg/pull/2377)as ready for review

**Comment by hermet** [comment]
@mgrudzinska Please take it easy. We can wait for the requester's response for a week. There's no need to rush this. You have bigger fish to fry.

**Comment by hermet** [comment]
> `tvg_text_load` - for now we use `text` as a name of the object type, also as a string we want to write. if we keep this name it will also refer to a font file. imo confusing, but maybe for other it's not.

Or, the mechanism may look like:

PREFIX_DOMAIN_BEHAVIOR( TARGET )

c++:
`tvg::Picture::load(image);`
`tvg::Text::load(font);`
c:
`tvg_picture_load(pic, mage);`
`tvg_text_load((skip), font);`    vs    `tvg_load_font(font)`

**Comment by hermet** [comment]
@mgrudzinska Please try to listen to various opinions and make a decision. In the end, you will confirm the API. thanks. 
\+ @tinyjin @JSUYA

**Comment by capnm** [comment]
@hermet `tvg_picture_load_data` ->  I assume you also need `tvg_font_load_data` to load the font from the memory block?

**Comment by mgrudzinska** [comment]
> @hermet `tvg_picture_load_data` -> I assume you also need `tvg_font_load_data` to load the font from the memory block?

@capnm yes, this will be added. when we started the discussion there was not such c++ api


> Also maybe: thing _ what to do with the thing
> 
> TVG_API Tvg_Result tvg_text_set(Tvg_Paint* paint, const char* text); 

then this one is incomplete - set what?


> TVG_API Tvg_Result tvg_font_load(const char* path); TVG_API Tvg_Result tvg_font_unload(const char* path); TVG_API Tvg_Result tvg_font_load_data(...); TVG_API Tvg_Result tvg_font_unload_data(...); TVG_API Tvg_Result tvg_font_get_names(...); ...

this one I like! thx :) initially I didn't want to use this order, since we don't have a font object, so I thought this may be confusing, but it seems to be consistent with other statics we have, like `tvg_engine_init`, `tvg_engine_term`.

**Comment by mgrudzinska** [comment]
> Or, the mechanism may look like:
> 
> PREFIX_DOMAIN_BEHAVIOR( TARGET )
> 
> c++: `tvg::Picture::load(image);` `tvg::Text::load(font);` c: `tvg_picture_load(pic, mage);` `tvg_text_load((skip), font);` vs `tvg_load_font(font)`

@hermet `tvg_text_load((skip), font);` - by `skip` you mean pass null? 
do you consider to introduce at some point a font object? if yes, then your approach makes most sense, no changes in apis will be required. but if not, I'd like to keep the convention we have for other statics - I think @capnm proposition is good: `tvg_font_load`, `tvg_font_load_data`, etc, same as `tvg_engine_init`, `tvg_engine_term`.

**Comment by capnm** [comment]
>  then this one is incomplete - set what?
 
The thing_  also text characters ;) 

or  `tvg_text_set_chars(Tvg_Paint* paint, const char* text);` 
but doesn't look IMO much better. 

When considering the complexity of the SVG text standard and the potential evolution of font support in the future, it would I think make sense to split `Text` and `Font` into separate classes as the SVG standard continues to develop. Additionally, as SVG already has the capability to ascertain the `Image` size, the inclusion of a font list to load the required fonts is also necessary.

**Comment by hermet** [comment]
@mgrudzinska 

> `tvg_text_load((skip), font);` - by `skip` you mean pass null?

I don't think so but I meant `tvg_text_load(font);`  it's aligned with tvg::Text::load(font);

> do you consider to introduce at some point a font object?

It's likely, but I have no idea about the font features at the moment.  

This is my logic.
```
tvg_engine_init() : tvg::initializer::init() 
tvg_engine_term() : tvg::initializer:term()
tvg_text_load() : tvg::Text::load()
tvg_font_xxx : ?    
```

Note that we can keep the `Experimental API` for a while until it's more certain. Thanks

**Comment by mgrudzinska** [comment]
@hermet @capnm please check https://github.com/thorvg/thorvg/pull/2377 and let me know if you strongly disagree with some of the apis

**Comment by mgrudzinska** [comment]
just to summarize:
I kept 'font' in the names:
`tvg_font_load`, `tvg_font_load_data`, `tvg_font_unload`
and also I kept `tvg_text_set_text` 
these were the most controversial ones. hope you guys agree with the current version
