### ISSUE TITLE
Cubic bezier curve has an edge case

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#2379]
`<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#ff8300" d="m1 15c0-14 14-14 14 0z"/></svg>`

This SVG renders like this:
![image](https://github.com/thorvg/thorvg/assets/85438892/c7a0b280-1762-46f9-9638-03c36598a223)

**Comment by mgrudzinska** [comment]
beautiful catch!

**Comment by hermet** [comment]
the fix will be in v0.13.8, thanks.
