### ISSUE TITLE
sw_engine:  AA artifacts

### ISSUE THREAD

**Issue by capnm** [thorvg/thorvg#2401]
#### I have simplified the previous crashing [image](https://github.com/thorvg/thorvg/blob/main/examples/resources/svg/matheusmdx.svg)   and modified it so that it crashes the FAA again.

![crash-08](https://github.com/thorvg/thorvg/assets/4047289/db5af02d-a9ca-4f3f-a9b8-0e762f354f2d)

[crash-08.zip](https://github.com/user-attachments/files/15828156/crash-08.zip)

![image](https://github.com/thorvg/thorvg/assets/4047289/ce034aa0-5f9f-4dcc-83bf-7bb80991ea3b)

#### Can confirm  https://github.com/thorvg/thorvg/pull/2399 !

or a quick hack limiting the line->length[0]  
```cpp
while (pos <= line->length[0] && line->length[0] < (INT32_MAX / 2)) {
//while (pos <= line->length[0]) {
```
fixes the crash.

## However, I can spot some artefacts:

![crash-08](https://github.com/thorvg/thorvg/assets/4047289/2229af33-90cb-4599-a736-93a1efcc893a)

**Comment by hermet** [comment]
Thanks, I will revisit this. 

see also: https://github.com/thorvg/thorvg/issues/2391

**Comment by capnm** [comment]
# !! 
I have tested this image with the older version of your PR,

```cpp
         //Anti-Aliasing frames
         ay = y - aaSpans->yStart;
-        if (aaSpans->lines[ay].x[0] > x1) aaSpans->lines[ay].x[0] = x1;
-        if (aaSpans->lines[ay].x[1] < x2) aaSpans->lines[ay].x[1] = x2;
 
         //Range allowed
         if ((x2 - x1) >= 1 && (x1 < maxx) && (x2 > minx)) {
 
+            if (aaSpans->lines[ay].x[0] > x1) aaSpans->lines[ay].x[0] = x1;
+            if (aaSpans->lines[ay].x[1] < x2) aaSpans->lines[ay].x[1] = x2;
+
             //Perform subtexel pre-stepping on UV
...
```

but with the commit in main (51c2e66f51d815d5bf239859488b7d65d0063e56) the image unfortunately crashes the FAA again ...

**Comment by capnm** [comment]
@hermet The AA crash is now fixed! 

The artifact on the right side doesn't. (The test svg uses really strange transformations, not sure if it makes sense to investigate it further ...)

godot4.3b ++ v0.14.0
![image](https://github.com/thorvg/thorvg/assets/4047289/2db4e45e-4dbf-422a-bdcd-0c9b2aa19e6d)
