### ISSUE TITLE
What kind of triangulation technique Thorvg uses in OpenGL

### ISSUE THREAD

**Issue by sasmaster** [thorvg/thorvg#2423]
Hi.
I am wondering what triangulation approach the engine is using in GPU mode?
Is it stencil-coverage like in Nvidia NV_PATH extension or a regular triangulation? Or smth else?

Thanks!

**Comment by SergeyLebedkin** [comment]
Hi
In OpenGL we are using both approaches: regular triangilation and also stencil-coverage in a cases, where triangulation can not manage geometry configuration.
WebGPU uses stencil-coverage for fill the sapes and triangulation + stencil for strokes 
Regular triangilation is CPU based approach, stencil-coverage - GPU based

**Comment by sasmaster** [comment]
Sergey! How are you doing man!? Good to see you again ;)
