### ISSUE TITLE
lottie: embedded (png) images are not drawn properly

### ISSUE THREAD

**Issue by afsalz** [thorvg/thorvg#2428]
Hi, 

Having an issue rendering the below animation with thorvg. Looks like it is only rendering the background of the animation. 
Animation: [Animation - 1718860337023.json](https://github.com/user-attachments/files/15909075/Animation.-.1718860337023.json)

Result from Thorvg; 

https://github.com/thorvg/thorvg/assets/128362946/b54795c3-9d39-4797-a346-14cbe358335a

Expected Result: 

https://github.com/thorvg/thorvg/assets/128362946/94c701aa-7c09-4f33-a3ae-29aefa7307d6

**Comment by hermet** [comment]
@afsalz the fix will be in v0.14.1
