### ISSUE TITLE
engines: enhance the raster engines(GL/WG) feature capabilities

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2435]
We are currently developing ThorVG's GPU acceleration engine for high-performance rendering. The purpose of this task is to ensure that the GL/WG engines are compatible with the ThorVG examples. The following table shows the list of feature coverage and the current status that the GL and WebGPU engines need to achieve.

| Examples | OpenGL/ES | WebGPU |
| ------------- | ------------- | ------------- | 
| Shapes | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Path | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Scene | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Transform | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Accessor | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| CustomTransform | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Animation | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Update | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| PictureSvg | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| DataLoad | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| LinearGradient | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| RadialGradient | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| PictureJpg | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| PicturePng | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| PictureWebp | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| SceneTransform | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| GradientTransform | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| FillRule | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| ImageScaleDown | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| ImageScaleUp | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Arc | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| StrokeLine | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| DirectUpdate | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Text | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Retaining | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Stroke | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| AnimateMasking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| InvLumaMasking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Performance | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Opacity | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Duplicate | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Viewport | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| PictureRaw | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| InvMasking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Masking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| LumaMasking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| GradientMasking | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| ClipPath | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| FillSpread | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| GradientStroke | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| StrokeMiterLimit | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Blending | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| MaskingMethods | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| StrokeTrim | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| LottieExtension | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| LottieExpressions | <ul><li>[ ] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Lottie | <ul><li>[ ] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| Svg | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| SceneBlending | <ul><li>[x] Works </li></ul>  | <ul><li>[x] Works </li></ul> |
| SceneEffect | <ul><li>[ ] Works </li></ul>  | <ul><li>[ ] Works </li></ul> |

See history: 
- https://github.com/thorvg/thorvg/issues/1479
- https://github.com/thorvg/thorvg/issues/1687

**Comment by hermet** [comment]
Checked in Examples Pass Rate:
- OpenGL/ES: 85%
- WebGPU: 62%

**Comment by hermet** [comment]
Checked in Examples Pass Rate:

OpenGL/ES: 89%
WebGPU: 65%

**Comment by hermet** [comment]
@SergeyLebedkin here looks a regression:
![wg_fillspread](https://github.com/user-attachments/assets/90278834-1818-4086-ae04-3b20eb48e758)

**Comment by SergeyLebedkin** [comment]
> @SergeyLebedkin here looks a regression
Fixed

**Comment by hermet** [comment]
@SergeyLebedkin @RuiwenTang Darken/Lighten Masking Methods are introduced. 
See: https://github.com/thorvg/thorvg/pull/2613

**Comment by hermet** [comment]
GL/WG scene breakage by rectified the behavior: https://github.com/thorvg/thorvg/pull/2714
Main concept change is here:
If the scene has a blending option, it would require the intermediate composition surface.
backend engines needs to init the buffer with A(0), R(1), G(1), B(1) instead of A(0), R(0), G(0), B(0)).

SceneBlending in Examples (where uses Add/Overlay blending optinos)

![image](https://github.com/user-attachments/assets/2d5a36b7-1da6-425d-bbc3-c0ced6524d04)
![image](https://github.com/user-attachments/assets/a9d8b368-4be9-41aa-85ae-f8433af73fbd)

**Comment by hermet** [comment]
@RuiwenTang Still ThorVG GL doens't officially cover the `Lottie` example, It has been broken with a resource leak (I guess), `Lottie` performance has been dramatically dropped since v0.14 by this: 

```
commit cf253dd873f4c2d87689dae5f2f3436a9eae7375
Author: Hermet Park <hermet@lottiefiles.com>
Date:   Sat Jul 13 17:33:11 2024 +0900

    lottie: ++scene rendering optimization

    Apply LottieRenderPooler to path/rect/ellipse/polystar.

    This enhances the animation performance: ~10%
```

`RenderPooler` is a kind of instance pooling mechanism used to reuse `Shape` every frame without creation/destroy. Guess GL engine couldn't refresh the existing resource(`RenderData`) in that scenario.

**Comment by hermet** [comment]
@SergeyLebedkin LottieExtension has been broken:

![image](https://github.com/user-attachments/assets/3fddd1fe-b04e-46eb-8b67-4002ba88ef67)

**Comment by hermet** [comment]
@SergeyLebedkin SceneBlending
![image](https://github.com/user-attachments/assets/d5a55746-75d5-4837-b696-662f4fc9c4df)

**Comment by hermet** [comment]
See: https://github.com/thorvg/thorvg/issues/3054
