### ISSUE TITLE
lottie: drop shadow is not rendering properly

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2442]
Hello team, An issue has been reported on dotlottie-web that appears to be related to ThorVG. Any ideas?

Issue: https://github.com/LottieFiles/dotlottie-web/issues/257

**Comment by mgrudzinska** [comment]
Layer effects are not supported for now (issue https://github.com/thorvg/thorvg/issues/2153)
as I see a "Custom effect" and "Gaussian blur effect" are used in the provided sample.

**Comment by manikanta-miro** [comment]
Hey, thank you for taking the time to look into this. Is there any alternative approach we can explore to make it work properly?

**Comment by hermet** [comment]
> Hey, thank you for taking the time to look into this. Is there any alternative approach we can explore to make it work properly?

@manikanta-miro Hello, ThorVG will work on this support. However, it may take some months. If it is really necessary, you can replace the bottom shapes with blurred PNG images.

**Comment by hermet** [comment]
Here issue is not about the drop shadow but the blur effect thorvg already support.
