### ISSUE TITLE
wg_engine: webgpu engine optimization ideas

### ISSUE THREAD

**Issue by SergeyLebedkin** [thorvg/thorvg#2492]
- [x] AABB-based composition and blend
- [x] decompose blend, masked blend and composition shaders: single shader per blend and composition method
- [ ] global vertex buffer instead of individual vertex buffer per mesh
- [ ] simplified path trianglulation for shapes without strokes

**Comment by hermet** [comment]
@SergeyLebedkin please update the progress or or close.
