### ISSUE TITLE
gl_engine: compilation error on Windows

### ISSUE THREAD

**Issue by vtorri** [thorvg/thorvg#2503]
I've installed the Angle library with MSYS2, and I've got the error:

```
In file included from ../src/renderer/gl_engine/tvgGlRenderer.h:29,
                 from ../src/renderer/tvgInitializer.cpp:36:
../src/renderer/gl_engine/tvgGlGpuBuffer.h:35:24: error: 'GL_ARRAY_BUFFER' was not declared in this
scope; did you mean 'GL_DRAW_BUFFER'?
   35 |         ARRAY_BUFFER = GL_ARRAY_BUFFER,
      |                        ^~~~~~~~~~~~~~~
      |                        GL_DRAW_BUFFER
../src/renderer/gl_engine/tvgGlGpuBuffer.h:36:32: error: 'GL_ELEMENT_ARRAY_BUFFER' was not declared
in this scope
   36 |         ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~
../src/renderer/gl_engine/tvgGlGpuBuffer.h:37:26: error: 'GL_UNIFORM_BUFFER' was not declared in thi
s scope
   37 |         UNIFORM_BUFFER = GL_UNIFORM_BUFFER,
      |                          ^~~~~~~~~~~~~~~~~
```

in mesons-log.txt:

```Determining dependency 'gl' with pkg-config executable 'C:\\Documents\\msys2_2\\mingw64\\bin/pkg-config.EXE'
env[PKG_CONFIG_PATH]: C:\Documents\msys2_2\mingw64\lib\pkgconfig;C:\Documents\msys2_2\mingw64\share\pkgconfig
env[PKG_CONFIG_SYSTEM_INCLUDE_PATH]: C:/Documents/msys2_2/mingw64/include
env[PKG_CONFIG_SYSTEM_LIBRARY_PATH]: C:/Documents/msys2_2/mingw64/lib
env[PKG_CONFIG]: C:\Documents\msys2_2\mingw64\bin/pkg-config.EXE
-----------
Called: `C:\Documents\msys2_2\mingw64\bin/pkg-config.EXE --modversion gl` -> 1
stderr:
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gl' not found
-----------
Run-time dependency gl found: YES
```

note that Angle does not install .pc files, at least the MSYS2 package does not.

So on Windows, I did like with the EFL : I check the header file and import lib in src/renderer/gl_engine/meson.build like that:

```
diff --git a/src/renderer/gl_engine/meson.build b/src/renderer/gl_engine/meson.build
index 7341f82b..f50ce9f8 100644
--- a/src/renderer/gl_engine/meson.build
+++ b/src/renderer/gl_engine/meson.build
@@ -23,6 +23,16 @@ source_file = [

 if host_machine.system() == 'darwin'
     gl_dep = declare_dependency(link_args: ['-framework', 'OpenGL'])
+elif host_machine.system() == 'windows'
+    gl_dep = cc.find_library(
+        'GLESv2',
+        has_headers: 'GLES3/gl3.h'
+    )
+    if gl_dep.found()
+        target_opengles = true
+    else
+        error('GLES 3.0 library not found. Please make sure Angle library is installed, or disable OpenGL support.')
+    endif
 else
     #find a opengl library with fallbacks
     gl_dep = dependency('GL', required: false)

```

and it compiles.

**Comment by RuiwenTang** [comment]
I think, the best choice on Windows is use OpenGL not OpenGLES with Angle.

**Comment by vtorri** [comment]
why ?

**Comment by RuiwenTang** [comment]
In my opinion, Angle is a Mock implementation of GLES. Which Cross-compile the shader and function call to the GPU backend that is actually used (Vulkan, D3D, OpenGL ). 
Now that GLEngine code can support direct use of OpenGL, why does it still need to go through the Angle conversion layer?

**Comment by vtorri** [comment]
First, the best choice on Windows is Direct3D, vs gl or gles. But no implementation yet
Second, if you want gl, then the user need to download a SDK specific to his graphic cards. Then you will have to hope that the driver is not buggy.

At least, with Angle, you have something which works now, though without the best perf

Note: Windows supports without any additional driver only gl <= 1.1. And I've seen several projects which provide angle dll to support opengl rendering

**Comment by vtorri** [comment]
You can also have a way to test in CI if there is a problem or not.

**Comment by RuiwenTang** [comment]
I'm not saying that Angle brings some bugs, just that there is an easy way to enable GLEngine on Windows.

BTW:
The Windows SDK only includes the legacy OpenGL header files. This does not mean that Windows not support modern OpenGL. And It does not require installing additional drivers. It just requires using some dynamic function loader like [GLAD](https://glad.dav1d.de/) use the modern OpenGL API.

**Comment by vtorri** [comment]
glad is not an option for me as it is not an msys2 package. Eventually glew.

**Comment by vtorri** [comment]
see PR #2525
