### ISSUE TITLE
tvg: revise the binary version check 

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2506]
Replace the TVG header version information with auto-generated version info to prevent human-mistakes.

replace (in tvgFormat.h)
```
#define TVG_HEADER_VERSION "010000"       //Major 01, Minor 00, Micro 00
#define TVG_HEADER_VERSION_LENGTH 6
```

with (in config.h)
```
#define THORVG_VERSION_STRING "0.14.99"
```

**Comment by theashraf** [comment]
@hermet is there a way we can get the `THORVG_VERSION_STRING` from ThorVG C bindings ?

**Comment by hermet** [comment]
@theashraf No APIs yet, Any use cases? Probably we can provide apis if the use-case makes sense.

**Comment by theashraf** [comment]
@hermet Our use case involves avoiding hardcoding the Thorvg version in dotLottie-rs. Instead, it would be beneficial to pull this version directly from Thorvg itself as a single source of truth. This approach would ensure that the version is consistent across all our bindings, including dotLottie-android, iOS, and web. This way, users can easily identify which versions of dotLottie-rs and Thorvg they are currently using. Let me know your thoughts.

For example, in [dotLottie-viewer](https://lottiefiles.github.io/dotlottie-web/), we currently display a Thorvg version that we need to update manually every time we update the Thorvg version. Sometimes, we miss updating it, which results in incorrect information being displayed to the user.

<img width="400" alt="image" src="https://github.com/thorvg/thorvg/assets/39750790/c7b767d3-be87-4d27-904c-501a0b7be78e">

**Comment by hermet** [comment]
@theashraf please follow up this issue: https://github.com/thorvg/thorvg/issues/2543  thanks.
