### ISSUE TITLE
Failure to compile on vs 2017

### ISSUE THREAD

**Issue by fire** [thorvg/thorvg#2512]
Someone reported failure to compile thorvg https://github.com/thorvg/thorvg/releases/tag/v0.14.0 in Godot Engine on Visual Studio 2017 due to MIN and MAX defines.

Following up

**Comment by mgrudzinska** [comment]
yes, we had this issue already https://github.com/thorvg/thorvg/issues/1661

**Comment by mgrudzinska** [comment]
@hermet std::min/max does not [require](https://en.cppreference.com/w/cpp/algorithm/min) including 'algorithm'? something we wanted to avoid I think

**Comment by hermet** [comment]
> @hermet std::min/max does not [require](https://en.cppreference.com/w/cpp/algorithm/min) including 'algorithm'? something we wanted to avoid I think

No, it was just missed due to an innocent mistake or lack of awareness.

**Comment by hermet** [comment]
Hopefully, this will be resolved in v0.14.1 by https://github.com/thorvg/thorvg/pull/2514
