### ISSUE TITLE
example: multithread task cause the Lottie example crashed when using GLEngine

### ISSUE THREAD

**Issue by RuiwenTang** [thorvg/thorvg#2517]
In OpenGL/GLES, all the GL function and GL object needs to be used in the thread which GLContext is makecurrent. Otherwise, some driver implementation may generate error and abort the process.

Some reference: https://www.khronos.org/opengl/wiki/OpenGL_and_multithreading

This crash is caused by the GLContext being MakeCurrented in another thread, but dispose triggering glDeleteTextures in this thread
<img width="1665" alt="截屏2024-07-04 18 10 08" src="https://github.com/thorvg/thorvg/assets/26308154/a4b3ecc4-8dec-44e7-ab97-5a324f4e4773">

**Comment by SergeyLebedkin** [comment]
Same issue for webgpu

**Comment by hermet** [comment]
> MakeCurrented in another thread,

Lottie example doesn't use threads for makecurrent?

**Comment by hermet** [comment]
> Same issue for webgpu

@SergeyLebedkin It's a just engine implementation matter. RenderMethod guarantees the same thread to be called.

**Comment by SergeyLebedkin** [comment]
> > Same issue for webgpu
> 
> @SergeyLebedkin It's a just engine implementation matter. RenderMethod guarantees the same thread to be called.

Including dispoce?

**Comment by hermet** [comment]
@SergeyLebedkin just noticed it's not. Let's see.

**Comment by RuiwenTang** [comment]
> > MakeCurrented in another thread,
> 
> Lottie example doesn't use threads for makecurrent?

In this sample, the GLContext is created and set current by SDL in most cases, which happens in the main thread.
The sample also uses 4 threads to call `tvg::Initializer::init`. During rendering, `canvas->update` dispatches tasks on these threads. And these threads do not have a valid GLContext. This is why the crash occurs

**Comment by hermet** [comment]
@RuiwenTang @SergeyLebedkin One suggestion: you can queing them in the RenderMethod and free them in the sync(). That could maximize the thread efficiency of thorvg.

**Comment by SergeyLebedkin** [comment]
> @RuiwenTang @SergeyLebedkin One suggestion: you can queing them in the RenderMethod and free them in the sync(). That could maximize the thread efficiency of thorvg.

Got it, I will try in wgpu side

**Comment by SergeyLebedkin** [comment]
> @RuiwenTang @SergeyLebedkin One suggestion: you can queing them in the RenderMethod and free them in the sync(). That could maximize the thread efficiency of thorvg.

we need some thread save list or other type of container

**Comment by hermet** [comment]
@SergeyLebedkin please check this patch https://github.com/thorvg/thorvg/pull/2520/commits/94575ed1db65264578fd89d5e8d83167bee672e3
