### ISSUE TITLE
sw_engine: incorrect radial grad result

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#2530]
sample:
```
<svg
  viewBox="0 0 800 800"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <radialGradient id="myGradient" spreadMethod="pad"
      gradientUnits="userSpaceOnUse"
      r="30" cx="400" cy="400">
      <stop offset="0.0" stop-color="#000000" />
      <stop offset="1.0" stop-color="#FFFFFF" />
    </radialGradient>
  </defs>

  <circle cx="400" cy="400" r="400" fill="url(#myGradient)" />
</svg>
```

<img width="1156" alt="Zrzut ekranu 2024-07-6 o 02 34 25" src="https://github.com/thorvg/thorvg/assets/67589014/96ab4b4b-a7c3-4a24-9a8b-ae5be06c4b46">

**Comment by hermet** [comment]
@mgrudzinska Please note that visual quality or differences will not be classified as software bugs.

**Comment by mgrudzinska** [comment]
maybe changing pad -> reflect shows better the problem:

current:
<img width="400" alt="Zrzut ekranu 2024-07-6 o 10 52 13" src="https://github.com/thorvg/thorvg/assets/67589014/723fd163-c8ca-4c0d-9f20-5989650de999">

expected:
<img width="400" alt="Zrzut ekranu 2024-07-6 o 10 52 37" src="https://github.com/thorvg/thorvg/assets/67589014/9a94fbb0-99f4-4cc6-bce8-2ccc5e3d8d02">
