### ISSUE TITLE
Support version api

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2543]
@hermet Our use case involves avoiding hardcoding the Thorvg version in dotLottie-rs. Instead, it would be beneficial to pull this version directly from Thorvg itself as a single source of truth. This approach would ensure that the version is consistent across all our bindings, including dotLottie-android, iOS, and web. This way, users can easily identify which versions of dotLottie-rs and Thorvg they are currently using. Let me know your thoughts.

For example, in [dotLottie-viewer](https://lottiefiles.github.io/dotlottie-web/), we currently display a Thorvg version that we need to update manually every time we update the Thorvg version. Sometimes, we miss updating it, which results in incorrect information being displayed to the user.

<img width="400" alt="image" src="https://github.com/thorvg/thorvg/assets/39750790/c7b767d3-be87-4d27-904c-501a0b7be78e">

_Originally posted by @theashraf in https://github.com/thorvg/thorvg/issues/2506#issuecomment-2213289136_

**Comment by hermet** [comment]
```
uint32_t major, minor, micro;   //return values when they are given.
auto string = tvg::Initializer::version(&major, &minor, &micro);    //expected string = "0.14.0"
```

@mgrudzinska could you please suggest a capi for it? thanks.

**Comment by mgrudzinska** [comment]
> ```
> uint32_t major, minor, micro;   //return values when they are given.
> auto string = tvg::Initializer::version(&major, &minor, &micro);    //expected string = "0.14.0"
> ```
> 
> @mgrudzinska could you please suggest a capi for it? thanks.

`TVG_API Tvg_Result tvg_engine_version(uint32_t* major, uint32_t* minor, uint32_t* micro, const char** version);`

**Comment by hermet** [comment]
> > ```
> > uint32_t major, minor, micro;   //return values when they are given.
> > auto string = tvg::Initializer::version(&major, &minor, &micro);    //expected string = "0.14.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @mgrudzinska could you please suggest a capi for it? thanks.
> 
> `TVG_API Tvg_Result tvg_engine_version(uint32_t* major, uint32_t* minor, uint32_t* micro, const char** version);`

@theashraf is it ok for dotlottie?

**Comment by hermet** [comment]
see: _buildVersionInfo() in tvgInitializer.cpp

**Comment by hermet** [comment]
@theashraf @mgrudzinska the feature will be in v0.14.3, thanks.

**Comment by hermet** [comment]
@tinyjin We can bind this version apis with wasm and support it in viewer. https://github.com/thorvg/thorvg.viewer/issues/59
