### ISSUE TITLE
Performance Compared to RLottie

### ISSUE THREAD

**Issue by erfanmola** [thorvg/thorvg#2578]
How is this library compared to RLottie in terms of performance? My main purpose is for usage in web as WASM, the WASM build for RLottie was around 300KB-400KB, but this library was around 600KB, so not superior in bundle size, but is it superior performance wise? it would be nice if someone provides benchmarks.

**Comment by vtorri** [comment]
I guess that it also depends on the options you passed to thovg when building. which are they ?

**Comment by hermet** [comment]
@erfanmola Hello, the main reason for the size difference is that ThorVG supports WebP and Expressions, whereas rlottie does not. For a fair measurement, please see the size comparison if throvg disables these two modules: 

**rlottie: 500kb, thorvg: 300kb**

![image](https://github.com/user-attachments/assets/fa7a59c8-69e3-4d54-a22e-6dc467676a0e)
![image](https://github.com/user-attachments/assets/1f36652a-1cbd-479e-beba-6370f070a9dc)

With even this smaller size, I can assure that throvg lottie feature coverage / stability is much bigger than rlottie.

\+ Please read this post on Canva team's benchmarking, where ThorVG's performance is superior to rlottie's.
https://lottiefiles.com/blog/working-with-lottie-animations/canva-enhances-ios-rendering-faster-and-efficient-with-thorvg


As the maintainer of both projects, I strongly recommend ThorVG. There are no benefits to using rlottie now.

**Comment by vtorri** [comment]
@hermet also mention that by default thorvg is compiled with stripping and -s, so no optimization except for size. What about with -O2 ?

**Comment by erfanmola** [comment]
@hermet Thanks for the detailed answer, Then my decision is made up and i'll go with Thorvg, thanks for this amazing piece of software.

One thing I have noticed is the default wasm builder script generates a JS file that contains a base64 encoded version of .wasm binary in JS, which is considerably 2x in size, is there any possibility to load the wasm manually and not by inline base64?

**Comment by hermet** [comment]
@erfanmola please check this [file](https://github.com/thorvg/thorvg/blob/main/cross/wasm_x86_i686.txt), remove this option `-sSINGLE_FILE=1`

just so you know, for the compact lottie player, you can tweak build option as well in the [build script ](https://github.com/thorvg/thorvg/blob/main/wasm_build.sh)

```
meson -Db_lto=true -Ddefault_library=static -Dstatic=true -Dloaders="lottie, png, jpg, webp" -Dthreads=false -Dbindings="wasm_beta" --cross-file /tmp/.wasm_cross.txt build_wasm
```

**Comment by vtorri** [comment]
just for your information, on my computer, with software engine, with `Lottie` example:

debugoptimized (-Os) no simd : [  327]: elapsed time = 23ms (25ms)
debugoptimized (-Os) simd    : [  327]: elapsed time = 28ms (25ms)
release (-O3) no simd        : [  327]: elapsed time = 25ms (23ms)
release (-O3) simd           : [  327]: elapsed time = 20ms (20ms)

**Comment by hermet** [comment]
@vtorri Thanks. for now, the web bundle size might be a big concern, we need to compromise the option soon or later. (Probably, we can apply it to the default)
