### ISSUE TITLE
linearGradient doesn't abide by certain specifications

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#2582]
The first issue is with userSpaceOnUse, where values outside of [0, 1] are treated incorrectly.

```xml
<svg width="64" height="64" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a" x1="0" y1="0" x2="2" y2="2"><stop offset="0" stop-color="#ff4596"/><stop offset=".25" stop-color="#ffe345"/><stop offset="1" stop-color="#45ffa2"/></linearGradient><rect width="64" height="64" fill="url(#a)"/></svg>
```

Expectation:
![image](https://github.com/user-attachments/assets/e74590a7-0d78-4b2f-b66a-5727f25fc586)

Nothing is displayed though, whereas the specification has the following section: https://svgwg.org/svg2-draft/coords.html#ObjectBoundingBox

> Any numeric value can be specified for values expressed as a fraction or percentage of object bounding box units. In particular, fractions less are zero or greater than one and percentages less than 0% or greater than 100% can be specified.

The second issue concerns gradients that start where they end.

```xml
<svg width="64" height="64" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a" x1=".4" y1=".4" x2=".4" y2=".4" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#ff4596"/><stop offset=".25" stop-color="#ffe345"/><stop offset=".5" stop-color="#45ffa2"/></linearGradient><rect width="64" height="64" fill="url(#a)"/></svg>
```

Nothing is displayed, which goes against the specification: https://svgwg.org/svg2-draft/pservers.html#LinearGradientNotes

> If x1 = x2 and y1=y2, then the area to be painted will be painted as a single color using the color and opacity of the last gradient stop.

**Comment by hermet** [comment]
@MewPurPur @mgrudzinska  the fix will be in v0.14.5, thanks.
