### ISSUE TITLE
wg_engine: SVG rendering compatibility

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2592]
This list shows the broken compatibility of SVG rendering with the WebGPU backend.
https://github.com/thorvg/thorvg/tree/main/examples/resources/svg

- [ ] svg2009 //bridge strings not clear (have no ideas how to fix)
- [x] patch //dash line
- [x] consecutive_lines //line cap
- [x] rg1024_Ufo_in_metalic_style //cap color
- [x] vnu //corner quality is too poor

**Comment by hermet** [comment]
Pass rate: 71%

**Comment by SergeyLebedkin** [comment]
rendering problems arise when applying a gradient transformation.
See https://github.com/thorvg/thorvg/issues/2620

**Comment by hermet** [comment]
Pass rate: 89%

**Comment by hermet** [comment]
Pass rate: 94%

**Comment by hermet** [comment]
@SergeyLebedkin edge blending error?
![image](https://github.com/user-attachments/assets/b95b8827-b1ac-43c9-bd18-648f11041093)

**Comment by SergeyLebedkin** [comment]
> @SergeyLebedkin edge blending error? ![image](https://private-user-images.githubusercontent.com/3711518/381900312-b95b8827-b1ac-43c9-bd18-648f11041093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjgxNDQsIm5iZiI6MTczMDM2Nzg0NCwicGF0aCI6Ii8zNzExNTE4LzM4MTkwMDMxMi1iOTViODgyNy1iMWFjLTQzYzktYmQxOC02NDhmMTEwNDEwOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDk0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA1YTU5MDYwOWY3Yjk1YTRlOWZhNjQ5ZTVmZTliMzRjMmI4ZTFkMzI5ODZlMjNlZmMzYjA0NjVmMzQ5YzYyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ltlRy1coaifdcsPpkBqEfF6lDt3Yi6c4g7SBK2THKjo)


Could be. We need to investigate this issue

**Comment by hermet** [comment]
thine line quality issue has been moved: https://github.com/thorvg/thorvg/issues/2920
