### ISSUE TITLE
wg_engine: stroke trim issue

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#2595]
sample:
```
        auto shape1 = tvg::Shape::gen();
        shape1->appendCircle(245, 225, 50, 120);
        shape1->appendCircle(245, 565, 50, 120);
        shape1->fill(0, 50, 155, 100);
        shape1->strokeFill(0, 0, 255);
        shape1->strokeJoin(tvg::StrokeJoin::Round);
        shape1->strokeCap(tvg::StrokeCap::Round);
        shape1->strokeWidth(12);
        shape1->strokeTrim(0.0f, 0.75f, false);

        canvas->push(std::move(shape1));
```

<img width="829" alt="Zrzut ekranu 2024-07-25 o 15 36 29" src="https://github.com/user-attachments/assets/06972ba2-64d1-4ec8-a119-a1e4ec7dbba1">

**Comment by SergeyLebedkin** [comment]
Results are the same
![image](https://github.com/user-attachments/assets/a7553191-eb25-400b-98bf-14db14638c66)
![image](https://github.com/user-attachments/assets/82518fb5-1461-4ed6-a27e-43d2268e2714)

**Comment by mgrudzinska** [comment]
@SergeyLebedkin apparently my mistake... 
but here is another one:
```
        auto shape1 = tvg::Shape::gen();
        shape1->appendCircle(245, 225, 50, 120);
        shape1->appendCircle(245, 565, 50, 120);
        shape1->fill(0, 50, 155, 100);
        shape1->strokeFill(0, 0, 255);
        shape1->strokeJoin(tvg::StrokeJoin::Round);
        shape1->strokeCap(tvg::StrokeCap::Round);
        shape1->strokeWidth(12);
        shape1->strokeTrim(0.5f, 0.75f, false);

        canvas->push(std::move(shape1));
   ```
   
<img width="757" alt="Zrzut ekranu 2024-07-25 o 18 36 04" src="https://github.com/user-attachments/assets/7795db6f-449e-491d-ae9d-eb3440b036aa">

**Comment by mgrudzinska** [comment]
> Results are the same ![image](https://private-user-images.githubusercontent.com/7770034/352159664-a7553191-eb25-400b-98bf-14db14638c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjYyMzcsIm5iZiI6MTcyMTkyNTkzNywicGF0aCI6Ii83NzcwMDM0LzM1MjE1OTY2NC1hNzU1MzE5MS1lYjI1LTQwMGItOThiZi0xNGRiMTQ2MzhjNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTY0NTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNhMTRhOWU5MzliMGJkMWExYzQxNWZlZWM3ZjdmY2NiYzY1MzhlOWMyMjU4NjRmMmY0MTcyMThkODg4YWNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U2ZIRfSXXVaXtYMOLYi-o6KvJh5_UHKbw_J-RvEzkwA) ![image](https://private-user-images.githubusercontent.com/7770034/352159959-82518fb5-1461-4ed6-a27e-43d2268e2714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjYyMzcsIm5iZiI6MTcyMTkyNTkzNywicGF0aCI6Ii83NzcwMDM0LzM1MjE1OTk1OS04MjUxOGZiNS0xNDYxLTRlZDYtYTI3ZS00M2QyMjY4ZTI3MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTY0NTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNlNzkwZTM3MDM2ZjQzMjAzNGI2ZmQyZjBhZmQzNWQ4ZjU3YmYzMjI5MTViZGM3NjI0ODdmNDUwMjUzZmZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r2JIu8neuuk1Z8XP-o501ChmasHi-cR8Q3IorvOVlro)

@SergeyLebedkin I tested on main, there the issue is present, but in #2577 it is solved

**Comment by mgrudzinska** [comment]
```
        auto shape1 = tvg::Shape::gen();
        shape1->appendCircle(245, 125, 50, 120);
        shape1->appendCircle(245, 365, 50, 120);
        shape1->appendCircle(125, 245, 120, 50);
        shape1->appendCircle(365, 245, 120, 50);
        shape1->fill(0, 50, 155, 100);
        shape1->strokeFill(0, 0, 255);
        shape1->strokeJoin(tvg::StrokeJoin::Round);
        shape1->strokeCap(tvg::StrokeCap::Round);
        shape1->strokeWidth(12);
        shape1->strokeTrim(-0.5f, 0.0f, false);
```
<img width="1059" alt="Zrzut ekranu 2024-07-25 o 20 10 11" src="https://github.com/user-attachments/assets/7bdc9fa5-6af3-4daf-96ca-fb41fe83a34f">

**Comment by mgrudzinska** [comment]
> auto shape1 = tvg::Shape::gen();
>         shape1->appendCircle(245, 225, 50, 120);
>         shape1->appendCircle(245, 565, 50, 120);
>         shape1->fill(0, 50, 155, 100);
>         shape1->strokeFill(0, 0, 255);
>         shape1->strokeJoin(tvg::StrokeJoin::Round);
>         shape1->strokeCap(tvg::StrokeCap::Round);
>         shape1->strokeWidth(12);
>         shape1->strokeTrim(0.5f, 0.75f, false);
> 
>         canvas->push(std::move(shape1));

now solved in 2577

**Comment by mgrudzinska** [comment]
> @SergeyLebedkin apparently my mistake... but here is another one:
> 
> ```
>         auto shape1 = tvg::Shape::gen();
>         shape1->appendCircle(245, 225, 50, 120);
>         shape1->appendCircle(245, 565, 50, 120);
>         shape1->fill(0, 50, 155, 100);
>         shape1->strokeFill(0, 0, 255);
>         shape1->strokeJoin(tvg::StrokeJoin::Round);
>         shape1->strokeCap(tvg::StrokeCap::Round);
>         shape1->strokeWidth(12);
>         shape1->strokeTrim(0.5f, 0.75f, false);
> 
>         canvas->push(std::move(shape1));
> ```
> 
> <img alt="Zrzut ekranu 2024-07-25 o 18 36 04" width="757" src="https://private-user-images.githubusercontent.com/67589014/352216735-7795db6f-449e-491d-ae9d-eb3440b036aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzE1OTIsIm5iZiI6MTcyMTkzMTI5MiwicGF0aCI6Ii82NzU4OTAxNC8zNTIyMTY3MzUtNzc5NWRiNmYtNDQ5ZS00OTFkLWFlOWQtZWIzNDQwYjAzNmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE4MTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YmM2MGUxM2ViMjdkYjk0Mzc3YzUyMzY0Zjg3YmIzOTAwZmNmNGRjMjZhY2ZlMmExNzE0MzMxY2NlM2M4MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syoTZGvtIr7FPZMJRjmOW2NgXjQeDwiH_YbvGvAI5lY">

this remains valid issue
also file to test, seems to be the same problem:
[trim_ind.json](https://github.com/user-attachments/files/16382460/trim_ind.json)

**Comment by hermet** [comment]
confirmed this resolved.
