### ISSUE TITLE
api: deprecate Shape::appendArc()

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2632]
We are considering the removal of the Shape::appendArc() function from the API. It appears to be used only in the SVG loader, not elsewhere. We can migrate this functionality to the SVG loader and remove it as an official feature.

see: https://github.com/thorvg/thorvg/issues/1372

**Comment by mgrudzinska** [comment]
I need to think about that for a moment, because I may need arcs within Lottie while manipulating Beziers. An internal implementation will be enough, but in that case, the destination should be common, not the svg loader.

**Comment by hermet** [comment]
@mgrudzinska Could you please explain the Lottie feature you are considering?

**Comment by mgrudzinska** [comment]
The offset. when expanding (offset > 0) works well. However for offset < 0 problems start to arise. This causes the shapes to shrink, with the curves beginning to intersect more and more. Eventually, not only neighboring curves intersect, but even those further apart, until the shape disappears. I'm considering approximating the curves with an arcs in such cases

**Comment by hermet** [comment]
@mgrudzinska OK, thanks. Please make sure this is addressed before the v0.15 release. I guess it’s not compatible to use  due to the complicated context of Lottie, especially with transformations and direction.

**Comment by hermet** [comment]
@kisvegabor Hello, We just want to align it. Could this change affect LVGL feature support?

**Comment by kisvegabor** [comment]
Thank you for asking! :pray: 

I've search for `appendArc` in LVGL and haven't found it. However, @fastshift made most of the work with LVGL's vector support and ThorVG. @fastshift can you confirm that this function can be removed?

**Comment by FASTSHIFT** [comment]
> Thank you for asking! 🙏
> 
> I've search for `appendArc` in LVGL and haven't found it. However, @FASTSHIFT made most of the work with LVGL's vector support and ThorVG. @FASTSHIFT can you confirm that this function can be removed?

To be sure, we're not using thorvg's `appendArc` function in LVGL.

**Comment by Pau6b** [comment]
Hi!

Why was this deprecated? Isn't appendArc intended to be used by the final users of ThorVG?

**Comment by hermet** [comment]
@Pau6b Hi, yes. It’s going to be removed since we currently have no requirement for it. If you need a specific arc drawing scenario, please suggest an image. The `trimpath` feature might be able to handle your use case; otherwise, we can reconsider the deprecation if needed.

**Comment by Pau6b** [comment]
Hi!

I've tried trimpath but I only seem to get it working for drawing strokes of the shape of an arc, but I'm not able to draw a semicircle for example or pie shapes.
I'm just trying to support JS canvas using thorvg but I'm missing arc and quadratic beziers.

**Comment by hermet** [comment]
> I've tried trimpath but I only seem to get it working for drawing strokes of the shape of an arc, but I'm not able to draw a semicircle for example or pie shapes.

@Pau6b pie/semi-circle filiing without stroke is good for you?

**Comment by Pau6b** [comment]
Sure. Is it a limitation to have the pie shape+stroke?

**Comment by hermet** [comment]
@Pau6b We will consider it again. Thanks.
