### ISSUE TITLE
tvg_picture_load_data load "lottie" failed.

### ISSUE THREAD

**Issue by espressif2022** [thorvg/thorvg#2642]
Hello, evenyone. I encountered an issue while using the ThorVG library. 
When I load a file using `tvg_picture_load(picture, LOTTIE_FILENAME);` , the loading and display work fine, although the loading process is a bit slow. 

To improve performance, I decided to try loading from RAM.I used the following code to load resources:
`tvg_res = tvg_picture_load_data(picture, p, len, "lottie", true);`
The resource loads correctly, but when I use `tvg_animation_get_total_frame(animation, &f_total)`, the `f_total` value is always 0. I'm not sure where the issue lies and would appreciate some guidance.

Additionally, when I set the `bool copy` parameter to `false`, the program crashes. The memory resources are placed in flash.

![企业微信截图_17237987036431](https://github.com/user-attachments/assets/1de7914e-b9bb-49dc-9720-bd48b8afc080)

**Comment by mgrudzinska** [comment]
@espressif2022 true/false shouldn't matter from lottie files. frame rate works correctly as well on my site

please check the example https://github.com/thorvg/thorvg/pull/2644     
If you still have problems please provide sample you are using.

**Comment by espressif2022** [comment]
> @espressif2022 true/false shouldn't matter from lottie files. frame rate works correctly as well on my site
> 
> please check the example #2644 If you still have problems please provide sample you are using.

Thanks for your reply.

If I provide a mem src, will you operate or write back to that memory?

Maybe this line `data[data_size++] = '\0';`,because my file is mmap from flash, I think I should manually copy it to ram and add '\0' to try. And I notice ISSUE this https://github.com/thorvg/thorvg/issues/2389

**Comment by hermet** [comment]
> If I provide a mem src, will you operate or write back to that memory?

@espressif2022 Yes, the given memory is written back during JSON parsing for optimal data processing. 

> Maybe this line `data[data_size++] = '\0';`,because my file is mmap from flash, I think I should manually copy it to ram and add '\0' to try. And I notice ISSUE this #2389

@espressif2022 yes, exactly you understand it.

**Comment by hermet** [comment]
@espressif2022 Wait, I might miss the context. If copy is true, it would not write back to user memory but to copied memory.

**Comment by hermet** [comment]
@mgrudzinska I missed the mmap case, thorvg rather add `\0` for this inside.

\+ @espressif2022

**Comment by espressif2022** [comment]
> @mgrudzinska I missed the mmap case, thorvg rather add `\0` to the copied memory, inside.
> 
> @espressif2022 Does this better for your case?



> @mgrudzinska I missed the mmap case, thorvg rather add `\0` to the copied memory, inside.
> 
> @espressif2022 Does this better for your case?

Yes, I can run it now. It would be great if it could support loading from mmap memory (but still need to enable copy flag)

**Comment by hermet** [comment]
@espressif2022 The enhancement has been applied, https://github.com/thorvg/thorvg/pull/2646. You can directly set the memory map using the copy option.
