### ISSUE TITLE
Picture raw load data format is unclear

### ISSUE THREAD

**Issue by QuLogic** [thorvg/thorvg#2648]
The [raw `Picture::load` overload](https://thorvg.github.io/thorvg/html/classtvg_1_1Picture.html#a1fdf75092cebaa7cde48d6a7d4946368) takes a `uint32_t *data` described as "A pointer to a memory location where the content of the picture raw data is stored." However, that page does not define what "picture raw data" means.

Is it ARGB, or ABGR? Is it premultiplied or not? Given that `SwCanvas` accepts all combinations of those as its `Colorspace` but `GlCanvas`/`WgCanvas` don't, I don't know which one is expected.

Is it column major or row major order? Usually images are row-major order, so I expect that, but since it's a unspecified pointer shape, it's not clear.

There is also a `premultiplied` argument documented, but that isn't in the signature AFAICT.

**Comment by QuLogic** [comment]
> There is also a `premultiplied` argument documented, but that isn't in the signature AFAICT.

Ah, this one is documented in the 0.14.4 release, but not actually there. However, it is in the API on `main`.

**Comment by hermet** [comment]
@QuLogic Hello, currently, it supports only `ARGB8888`. The API should be revised to allow for different color spaces, but we haven’t done that yet. Also, you don’t need to worry about the GL/WG Canvas for this, as the renderer will handle the color format adjustments for the backend engines.

Issue: https://github.com/thorvg/thorvg/issues/1372
![image](https://github.com/user-attachments/assets/6fb7614a-e225-43fe-8871-fe23417dc7a6)

Please let us know if another specific format for raw data is necessary for you right now.

**Comment by QuLogic** [comment]
I think at this time, I can work with any colour space format; it just should be documented.

For the current 0.14.5 which doesn't have the `premultiplied` parameter, is the data premultiplied?

**Comment by hermet** [comment]
> For the current 0.14.5 which doesn't have the `premultiplied` parameter, is the data premultiplied?

yes => https://github.com/thorvg/thorvg/commit/82563bf29a5be71178137611dbff305c7296b92c
