### ISSUE TITLE
Are there any lists of Lottie features supported by ThorVG?

### ISSUE THREAD

**Issue by xlbao123** [thorvg/thorvg#2697]
Are there any lists of Lottie features supported by ThorVG? I need this to show our designers.

**Comment by hermet** [comment]
@xlbao123 Hello, please check this: https://lottiefiles.com/supported-features

You can regard dotLottie the same as ThorVG. It's the most powerful than other. It will quickly evolve to cover the full spec by the end of this year.

You can also test with:  
- https://thorvg-perf-test.vercel.app/
- https://www.thorvg.org/viewer
