### ISSUE TITLE
text: String measuring for text wrapping

### ISSUE THREAD

**Issue by lpogic** [thorvg/thorvg#2709]
To implement text wrapping, it would be useful to be able to get information about how many characters of a given string fit into a given width. It would be best if such a method did not render the text but returned the dimensions. 

For now, there is no other way than to render the text several times until the right length is found.

Example of similar feature: https://wiki.libsdl.org/SDL2_ttf/TTF_MeasureText

To consider:
- character round method - determines which string length is returned when the given width limit is reached in the middle of character (like rounding float to int methods: floor, nearest, ceil). Maybe not very useful for text wrapping, but more for gui toolkits (cursor position).
- index limit - specifies the maximum number of characters in a string. Maybe not as another attribute, but a separate method that is based on similar logic. The difference in the width of the shortened text and the width returned when the limit is reached is affected by kerning.

**Comment by hermet** [comment]
Good to discuss. Totally agree on your requirement.  Maybe we can suggest these rich text style apis as well:
```
text->limit(w, h); //specify the text base region
text->wrap(word / character / ellipsis)
text->align(left/center/right);
text->vertical(true)  //default horizontal
```
I know, Text always matters. In the end, a cursor based text layouting mechanism is necessary, more advanced features like markup text and bidirectional language support will be required as well. However, they seem excessive and may go beyond the capabilities of ThorVG primitives now. I'm not sure yet.

**Comment by lpogic** [comment]
To be clear, I haven't thought about adding support for multiline text right now. My idea is to provide users with a basic API so they can implement wrapping themselves. It's worth considering supporting multiline text, but I think there should also be a way to fold lines independently to deal with wild cases.

**Comment by hermet** [comment]
@lpogic If you're interested in this task, we could start by discussing the API design. We welcome your suggestions. However, you know, If thorvg (current) users want those functions to make multiline text or ellipsis such things, then it might better to directly support it for their convenience. Generally, that would be better for users. Otherwise that would be better if we can confirm what are users trying to do with thorvg text first.

I know, such a cases like edit field. if users are expected to implement more advanced features based on ThorVG, the API usage would become quite complex. This might run counter to ThorVG's goal of providing simple API-driven graphic output. We need to  carefully advance this.

**Comment by lpogic** [comment]
I agree that creating highly specialized functions in the library can harm its simplicity, which I loved. On the other hand, I really appreciate its flexibility, which allows for implementing very interesting solutions.

I recently started experimenting with custom GUI framework based on ThorVG. The issues I'm reporting are the result of this work. This one comes from the needs of the edit field, which you've already mentioned. At first I thought it was too specialized to propose. But as I found more use cases, I decided it was worth bringing it up. Implementing text wrapping is another, but I was also thinking about effects like text background in a given character range.

If we decide to add support for multiline text in the library, I think I could help with that. Regarding the API project:
- `text->limit(w, h)` - there could be also single argument version, where result text occupy as much lines as needed
- `text->wrap(word / character / ellipsis)` - we could consider the 'hyphen' option where words can be breaked in the middle
- `text->align(left/center/right)` - sometimes a 'column' option could be useful, but it would require some support for letter/word spacing (I think it is topic for another issue btw.)
- I don't know if it's possible, but if the text boundaries could be defined by a Shape object, it would be amazing :)

**Comment by hermet** [comment]
@lpogic Hi, let's drop the multiline support in ThorVG since you're now considering implementing the edit field.

> * I don't know if it's possible, but if the text boundaries could be defined by a Shape object, it would be amazing :)

Do you mean the rectangular boundary, like paint->bounds()? That form works for you?

```
    /**
     * @brief Gets the axis-aligned bounding box of the paint object.
     *
     * @param[out] x The x-coordinate of the upper-left corner of the object.
     * @param[out] y The y-coordinate of the upper-left corner of the object.
     * @param[out] w The width of the object.
     * @param[out] h The height of the object.
     * @param[in] transformed If @c true, the paint's transformations are taken into account in the scene it belongs to. Otherwise they aren't.
     *
     * @note This is useful when you need to figure out the bounding box of the paint in the canvas space.
     * @note The bounding box doesn't indicate the actual drawing region. It's the smallest rectangle that encloses the object.
     * @note If @p transformed is @c true, the paint needs to be pushed into a canvas and updated before this api is called.
     * @see Canvas::update()
     */
    Result bounds(float* x, float* y, float* w, float* h, bool transformed) const noexcept;
```

**Comment by lpogic** [comment]
What I meant by this point is rather that the shape area defines where the letters can go. For an input like this:

```
auto shape = tvg::Shape::gen();
shape->moveTo(0, 0);
shape->lineTo(200, 0);
shape->lineTo(200, 100);
shape->lineTo(100, 100);
shape->lineTo(100, 200);
shape->lineTo(0, 200);
shape->close();

auto text = tvg::Text::gen();
text->font("Arial", 20);
text->text("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
text->fill(0, 0, 0);
text->limit(shape);
canvas->push(std::move(text));
```

output like this:

![1](https://github.com/user-attachments/assets/08949aba-87d4-4a32-8837-d21246b97c8b)

> Hi, let's drop the multiline support in ThorVG since you're now considering implementing the edit field.

Ok. Can the issue be closed?

**Comment by hermet** [comment]
> output like this:

@lpogic For ThorVG native APIs, I don't think this is a good approach. Paths can have ambiguous shape boundaries, not necessarily rectangular ones. You can create custom text by appending text objects line by line internally and setting them according to the line geometry (boundaries, path->bounds()).

> Ok. Can the issue be closed?

@lpogic If you are ok.

**Comment by hermet** [comment]
Maybe, these are paragraph functional concepts: If ThorVG support line wrapping and boundary limits, you can create two text objects and compose them together like this:
1.
![image](https://github.com/user-attachments/assets/f5ecdfb8-54c8-4607-9cc4-14a23aac8bac)
2.
![image](https://github.com/user-attachments/assets/e6f4ca2a-1be9-4df0-9f1a-c964e7d0a061)
