### ISSUE TITLE
Web support is missing (only Lottie bindings are available)

### ISSUE THREAD

**Issue by alienself** [thorvg/thorvg#2732]
Hi,

I would love to use Thorvg in my project however it seems like the bindings are missing? 
I found the web package which seems to only expose a Lottie player confirmed by the bindings found [here](https://github.com/thorvg/thorvg/tree/7a6a89cf26139afaf7e33dc596f457db2b63c36a/src/bindings/wasm).
I would like to be able to control Thorvg api directly using typescript rather than c++ similar to Skia / CanvasKit.

Any plans to add more bindings?

**Comment by hermet** [comment]
@alienself Hello, we fully understand your requirement. Technically, it wouldn't be difficult for us, but we are currently facing some manpower challenges. At the moment, we aren't able to work on this and haven't prioritized it because there haven't been any requests for it. However, if you're open to a delayed timeline (after Nov.), we may be able to compromise the schedule for the best of both worlds. Thank you.

**Comment by alienself** [comment]
@hermet Thank you very much for your reply. I completely understand and would be able to wait until after November if that works with your timeline. 

How does Thorvg compare feature wise to Skia? I like skia but on the web it's very heavy (5MB wasm file).
I would also love to be able to use your library aside an existing webGPU renderer to be able to display ui element in 3d space which skia is not able to provide unless rendering to a texture first.

**Comment by hermet** [comment]
@alienself There must be obvious pros/cons. Skia offers broad functionality and good overall performance, while ThorVG is more compact and lightweight, with a focus on optimal features for a wide range of systems. Somehow thorvg could be a better choice, good portability and easy system integration, using less resources(0.5mb ~ 2mb) with fairly good enough performance. In the case of WebGPU, it is still in experimental development. We can't fully assess its capabilities yet, but using a WebGPU renderer with ThorVG direct compositing is one of our potential options moving forward. its first (official) release is expected in this Dec.

Perhaps you can prototype with the software backend first and switch to the WebGPU backend when the time comes. Overlaid, partially positioned UI controls might work well enough with the software backend.

**Comment by alienself** [comment]
Thank you very much for the quick reply! It does sound super compelling compared to skia for a web use case. Do you think that the December release could potentially contain the JS bindings too?

Ok I am going to play around with the software backend until WebGPU support. 
Will it be possible to provide an existing GPU device to the thorvg library rather than thorvg requesting the device/adapter on its own, so that it can be easily integrated within an existing webGPU renderer?

**Comment by hermet** [comment]
> Do you think that the December release could potentially contain the JS bindings too?

Unlikely for now. It seems a bit tight for the 1.0 release. I understand its priority, but we need a more thorough plan for it.

> Will it be possible to provide an existing GPU device to the thorvg library rather than thorvg requesting the device/adapter on its own, so that it can be easily integrated within an existing webGPU renderer?

Yes, currently ThorVG Web works as you mentioned. It doesn't create device resources by itself; instead, they are passed from the web canvas runtime to be shared. Actually, ThorVG supports both approaches, and the choice of integration is up to the user.
\+ @tinyjin @SergeyLebedkin

**Comment by hermet** [comment]
Please track this issue: https://github.com/thorvg/thorvg/issues/2736
