### ISSUE TITLE
the lottie render by swcanvas is not right in qt

### ISSUE THREAD

**Issue by evehal** [thorvg/thorvg#2755]
![1726993329074](https://github.com/user-attachments/assets/3ad4b1a8-876f-43b5-8494-955084d1b104)
![1726994775628](https://github.com/user-attachments/assets/d5641b21-947f-407d-a198-1e9aeacaa656)

**Comment by hermet** [comment]
@evehal Hi, could you please share the resource so we can verify it on our end? We're unable to assist with the limited information provided.
