### ISSUE TITLE
gl_engine: require code refactoring

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2780]
`CompositeMethod::ClipPath` will be replaced with the `Scene::clip()` (currently -> `Paint::clip()`) method. `gl_engine` needs to refactor to remove the enum value usage before proceeding with its removal.

![image](https://github.com/user-attachments/assets/ab20dc30-6974-412d-8e4b-5f9fe70b87e1)

see:
```
    /**
     * @brief Clip the drawing region of the paint object.
     *
     * This function restricts the drawing area of the paint object to the specified shape's paths.
     *
     * @param[in] clipper The shape object as the clipper.
     *
     * @retval Result::NonSupport If the @p clipper type is not Shape.
     *
     * @note @p clipper only supports the Shape type.
     * @note Experimental API
     */
    Result Paint::clip(std::unique_ptr<Paint> clipper);
```

**Comment by hermet** [comment]
@RuiwenTang Hello, that would be really helpful if you could help this.

**Comment by RuiwenTang** [comment]
I think can just remove the use of CompositeMethod::ClipPath in GLEngine, the GLRenderer can handle normal PathCLip as well
