### ISSUE TITLE
wg_engine: require code refactoring

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2783]
CompositeMethod::ClipPath will be replaced with the Scene::clip() (currently -> Paint::clip()) method. gl_engine needs to refactor to remove the enum value usage before proceeding with its removal.

![image](https://github.com/user-attachments/assets/7f0df78b-554b-4612-8b6e-7122e7bdd650)

see:
```
    /**
     * @brief Clip the drawing region of the paint object.
     *
     * This function restricts the drawing area of the paint object to the specified shape's paths.
     *
     * @param[in] clipper The shape object as the clipper.
     *
     * @retval Result::NonSupport If the @p clipper type is not Shape.
     *
     * @note @p clipper only supports the Shape type.
     * @note Experimental API
     */
    Result Paint::clip(std::unique_ptr<Paint> clipper);
```

**Comment by SergeyLebedkin** [comment]
@hermet 
wg_engine did not use CompositeMethod::ClipPath enum value at all. 
wg_engine uses only clips count in RenderMethod::prepare stage.
So nothing to change in a case of enum values

**Comment by hermet** [comment]
@SergeyLebedkin it does. Please check the screenshot.
