### ISSUE TITLE
lottie: animated slot color issue

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2797]
In this lottie animation file -> [animation.json](https://github.com/user-attachments/files/17201072/animation.json)

**Original color value:**

```json
"c": { "a": 0, "k": [0.961, 0.761, 0.267, 1], "sid": "ball_color" },
```

**Override color value:**

```json
"slots": {
  "ball_color": {
    "p": {
      "a": 1,
      "k": [
        {
          "i": { "x": [0.833], "y": [0.833] },
          "o": { "x": [0.167], "y": [0.167] },
          "t": 7,
          "s": [0, 0.176, 0.867]
        },
        {
          "i": { "x": [0.833], "y": [0.833] },
          "o": { "x": [0.167], "y": [0.167] },
          "t": 22,
          "s": [0.867, 0, 0.533]
        },
        {
          "i": { "x": [0.833], "y": [0.833] },
          "o": { "x": [0.167], "y": [0.167] },
          "t": 37,
          "s": [0.867, 0, 0.533]
        },
        { "t": 51, "s": [0, 0.867, 0.255] }
      ]
    }
  }
}
```

ThorVG ignored the override. You can test this behavior using the [dotLottie viewer](https://lottiefiles.github.io/dotlottie-web/).
<img width="809" alt="image" src="https://github.com/user-attachments/assets/28b7d8f9-8806-4314-80bb-34762bf078a3">

**Comment by hermet** [comment]
@theashraf  the fix will be in v0.15.3. thanks.

**Comment by hermet** [comment]
@theashraf hmm, could you please double-check it? it's working good here, no memory violations.

https://github.com/user-attachments/assets/52e7f87b-3d3d-4f25-baeb-78038e3b3d4a

**Comment by theashraf** [comment]
sorry @hermet, my thorvg build was cached, i can confirm it's working smoothly now
