### ISSUE TITLE
api: support RadialGradient focal parameters

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2860]
RadialGradient needs an API revision to expose focal parameters.

Result RadialGradient::RadialGradient::radial(float cx, float cy, float r)
 -> Result RadialGradient::RadialGradient::radial(float cx, float cy, float r, float fx, float fy, float fr)

**Comment by mgrudzinska** [comment]
@hermet do we want to keep both or only the new one? 
I can not set any def values to fx and fy since if not specified they should be equal to cx and cy
