### ISSUE TITLE
PNG image color differs for GL and Software renderers

### ISSUE THREAD

**Issue by alex-dorokhov** [thorvg/thorvg#2863]
I'm using the PicturePng example with my own image file (
![img_0_gimp](https://github.com/user-attachments/assets/dc01a8c0-8eb7-4895-949e-9fd85feed1a3)
).

The result on Mac OS is different depending on the renderer (GL - left, SW - right):

<img width="1601" alt="Screenshot 2024-10-15 at 17 04 41" src="https://github.com/user-attachments/assets/4d0946ce-3b18-44c6-b9e5-ae277e89ce64">

As you may see, the left (GL) picture is more pinky.

I'm using commit with the hash c9960fcc

**Comment by hermet** [comment]
@alex-dorokhov the fix will be in 1.0.0-pre3. Thanks.

**Comment by hermet** [comment]
@alex-dorokhov if you need an official release (v0.15.2), please let me know. thanks.
