### ISSUE TITLE
wg_engine: a regression

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2869]
`Clipping` & `PictureRaw` examples have been broken by:

```

commit adebbcd4e21172dd34e6ff617da284360f4181f2
Author: Sergii Liebodkin <s.lebedkin@gmail.com>
Date:   Tue Oct 15 12:13:17 2024 +0000

    wg_engine: fix miter qdge cases math
```
before:
![image](https://github.com/user-attachments/assets/7ec36fd2-6fd7-4fb3-a535-c5d8041705fe)
after:
![image](https://github.com/user-attachments/assets/b09cdd41-2621-4e5e-a781-bd00c00a7adb)

**Comment by SergeyLebedkin** [comment]
fixed in PR https://github.com/thorvg/thorvg/pull/2865
