### ISSUE TITLE
wg_engine: Need radial fill anti-aliased drawing

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2931]
See `FillSpread`

![image](https://github.com/user-attachments/assets/a0fa3608-116d-47b6-8cee-294d58ca01b9)

see also: https://github.com/thorvg/thorvg/pull/2528

**Comment by SergeyLebedkin** [comment]
SVG renderers have the same issue in case of repeat spread:
![repeat](https://github.com/user-attachments/assets/df7079e4-36cd-4e22-847d-969d8980d322)

**Comment by hermet** [comment]
Users will expect similar quality from ThorVG's graphic output capabilities, regardless of the backend rendering functionality. wg engine should be aligned the thorvg spec, not svg renderer.
