### ISSUE TITLE
lottie/slots: default slots override is not working

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2969]
on branch v0.15.x, i'm not getting the default slots overriding its targets as expected

Expected: 
<img width="383" alt="image" src="https://github.com/user-attachments/assets/e0cc2659-0517-4594-b9d2-9a076258fd8f">

Actual:
<img width="386" alt="image" src="https://github.com/user-attachments/assets/6b8bd228-73ab-4202-adf9-b8ce59e79579">

[test.json](https://github.com/user-attachments/files/17797704/test.json)

**Comment by hermet** [comment]
@theashraf the fix will be in v0.15.4. Thanks.
