### ISSUE TITLE
lottie: fail to load animation with PNG sequence

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2975]
Unable to load this Lottie asset:  

[pngSequence.json](https://github.com/user-attachments/files/17809227/pngSequence.json)  

Related dotLottie-web issue: <https://github.com/LottieFiles/dotlottie-web/issues/404>

**Comment by hermet** [comment]
![image](https://github.com/user-attachments/assets/c78f8f06-6c8c-4af5-b376-40a9a8d78bfc)

**Comment by hermet** [comment]
parsing error by:
![image](https://github.com/user-attachments/assets/a63e69ed-44eb-4987-8519-8857f38f0c59)

**Comment by hermet** [comment]
@theashraf the fix will be in v0.15.5. thanks.
