### ISSUE TITLE
lottie/slot: can't target multiple properties with a slot

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2988]
<img width="400" alt="image" src="https://github.com/user-attachments/assets/87a328c2-fee2-4768-ba7a-5ac87e7ecf1a">

[Main Scene.json](https://github.com/user-attachments/files/17861995/Main.Scene.json)

**Comment by hermet** [comment]
@theashraf the fix will be in v0.15.5 thanks.
