### ISSUE TITLE
wg_engine: wrong alpha pre-multiplication? 

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2992]
examples/lottie/a_mountain.json

![image](https://github.com/user-attachments/assets/304e3b19-91dd-4086-8b45-e06d1d754d5a)

**Comment by SergeyLebedkin** [comment]
SW and WG renderer.
Looks same
![image](https://github.com/user-attachments/assets/beca6e2d-8be0-4d92-8f06-3ad2e480995f)

**Comment by hermet** [comment]
@SergeyLebedkin did you test on web?

**Comment by SergeyLebedkin** [comment]
Latest main branch. Looks correct
![image](https://github.com/user-attachments/assets/e2914811-eacf-433a-9902-42586620c107)

**Comment by hermet** [comment]
@tinyjin could you please confirm this with "the latest main + the viewer".

**Comment by tinyjin** [comment]
@hermet @SergeyLebedkin 

Looks better in main branch.

[Current Viewer]
![CleanShot 2024-12-05 at 13 19 04@2x](https://github.com/user-attachments/assets/ef336a96-6697-4969-88b0-c284af27400c)

[Main Branch]
![CleanShot 2024-12-05 at 13 18 48@2x](https://github.com/user-attachments/assets/732da43a-6c6e-413d-8e94-7ea08c4a5423)
