### ISSUE TITLE
gl_engine: element with gradient transparency rendered incorrectly

### ISSUE THREAD

**Issue by AlTeveDev** [thorvg/thorvg#3030]
Lights of police strobe rendered incorrectly in Telegram police car animated sticker
Software or WebGpu rendered version has beautiful neat glowing
Gl rendered version has excessive glowing
![Screenshot_20241205_185124](https://github.com/user-attachments/assets/9e61d69c-e1a0-4c50-a7a3-1187ebbdde11)

Animation: https://gist.github.com/AlTeveDev/504ea59f8158fb955eb6c55bbc6913b1

**Comment by hermet** [comment]
\+ @RuiwenTang

**Comment by hermet** [comment]
@AlTeveDev Hello, the fix will be in v0.15.7. Thanks.
