### ISSUE TITLE
Renderer: Ensure short paths with stroke width are rendered

### ISSUE THREAD

**Issue by baszczewski** [thorvg/thorvg#3065]
ThorVG currently skips rendering paths with very short or zero-length segments. While this behavior may sometimes be justified, it should not occur when attributes such as ```stroke-width``` and ```stroke-linecap``` are applied.

This omission causes ThorVG to display SVG files or Lottie animations differently from other widely used tools, such as Google Chrome, Firefox, Inkscape, Figma, lottie-web, or Image Viewer (from the GNOME Desktop Environment).

### Observations

- The issue occurs across different rendering engines, including SW and GL. I have not tested it with WG, but similar behavior is likely expected.
- Using zero-length paths is a common and desirable technique in animation. Combined with stroke-width and stroke-linecap (e.g., round), it enables effects where a line is reduced to a dot at specific points in an animation.

### Example Use Case

In our ```Lordicon``` project, hundreds of icons rely on this technique. Removing this functionality would significantly complicate the animation preparation process, which is not a viable option.

### Attachments

Simply compare how the files below are rendered in browsers or in lottie-web versus in ThorVG.

**SVG:**

![simple](https://github.com/user-attachments/assets/0b46649d-998f-49d1-bed5-d331d45a08d0)

**Test SVG:**

![test](https://github.com/user-attachments/assets/2b265d99-d529-494b-a069-c34c61dcfe6c)

**Test Lottie:**

[test.json](https://github.com/user-attachments/files/18196150/test.json)

**Comment by hermet** [comment]
\+ @RuiwenTang

**Comment by hermet** [comment]
@baszczewski Thanks for reporting. Just for your information, you can quickly test resources using [thorvg viewer](https://www.thorvg.org/viewer)

![image](https://github.com/user-attachments/assets/bff97a3e-227a-469d-90cd-74fdcfeab2c4)

**Comment by hermet** [comment]
related: https://github.com/thorvg/thorvg/issues/2094

**Comment by hermet** [comment]
@baszczewski @mgrudzinska Thanks, the fix will be in v0.15.8.
