### ISSUE TITLE
svg: Nested clip-paths are displayed incorrectly

### ISSUE THREAD

**Issue by JSUYA** [thorvg/thorvg#3082]
A clip path can have another clip-path. Currently only the first clip path is displayed.

```html
<svg  viewBox="0 0 100 100"  xmlns="http://www.w3.org/2000/svg">

  <clipPath id="myClip2">
     <path id="path2" d="M40,40 L90,40 L90 90 L 40 90 Z" fill="red"/>
  </clipPath>

  <clipPath id="myClip">
     <path id="path" d="M20,20 L70,20 L70 70 L 20 70 Z" fill="red" clip-path="url(#myClip2)"/>
  </clipPath>

  <path
    id="heart"
    d="M10,30 A20,20,0,0,1,50,30 A20,20,0,0,1,90,30 Q90,60,50,90 Q10,60,10,30 Z" clip-path="url(#myClip)" />

</svg>

```

**Comment by hermet** [comment]
a temporal regression during dev

**Comment by JSUYA** [comment]
Maybe this problem is closer to https://github.com/thorvg/thorvg/issues/2928#issuecomment-2459065122.

**Comment by JSUYA** [comment]
> Maybe this problem is closer to [#2928 (comment)](https://github.com/thorvg/thorvg/issues/2928#issuecomment-2459065122).

I checked that https://github.com/thorvg/thorvg/pull/3079 fixed it.
