### ISSUE TITLE
SVG ClipPath doesn't work

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#429]
Try in the example:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path

**Comment by mgrudzinska** [comment]
1) ```clipPathUnits``` added in #985 

2) ```clip-path="circle() fill-box"``` format is not supported in tvg for now

**Comment by hermet** [comment]
Current result:

![thorvg](https://user-images.githubusercontent.com/3711518/230284329-e8bf95af-a60e-4f63-8da5-47eb1c9746e1.png)

**Comment by mgrudzinska** [comment]
the expected result (the css styling isn't supported everywhere): 
<img width="215" alt="Zrzut ekranu 2023-04-7 o 02 18 51" src="https://user-images.githubusercontent.com/67589014/230516108-448ad540-5209-4793-aed0-cc9200e466b4.png">

the top left will work after we implement #661 and #985 - both very old and has to be changed

**Comment by hermet** [comment]
@mgrudzinska  Hmm... clippath can be simply composed using a single shape. Probably, svg loader could achieve it without scene-clippath. it's better for performance.

**Comment by hermet** [comment]
the result checked on the latest:

![image](https://user-images.githubusercontent.com/3711518/236726248-7fd5a15b-e71c-4a7d-b493-e17d63deedc1.png)

**Comment by mgrudzinska** [comment]
after #1547 :

<img width="515" alt="Zrzut ekranu 2023-07-30 o 11 40 08" src="https://github.com/thorvg/thorvg/assets/67589014/0edb4d7a-f6df-4537-bef3-dea53a551e3e">

On Chrome, the results remain the same. The rest of these samples include CSS styling that isn't widely supported. Therefore, once we reach a consensus on #1547, we can close this issue. If necessary, we can open a new one to address the extension of CSS support.
