### ISSUE TITLE
Support Lottie Animation

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#692]
Lottie animation is becoming increasingly popular. If ThorVG supports animation, both ThorVG and Lottie would have their respective advantages. 

See: https://lottiefiles.com/

**Comment by JSUYA** [comment]
I thought about how to use the existing paint loader.

1)
```
auto picture = tvg::Picture::gen()
picture->load("a.json");
picture->size(width, height);

auto t = picture->totalFrame();
auto d = picture->duration();
picture->setFrame(FrameNo);

canvas->push(picture);
```


2)
```
auto picture = tvg::Picture::gen()
picture->load("a.json"); // "a.riv"
picture->size(width, height);

auto animation = tvg::Animation::gen();
animation->setPicture(picture); //or ->push(picture);
auto t = animation->totalFrame();
auto d = animation->duration();
animation->setFrame(FrameNo);

canvas->push(animation);
```

**Comment by hermet** [comment]
Good suggestion. I'm worrying Picture will become too complex. We need to consider this very carefully.

Here is another brief idea.

1. We might have Loader class for the universal way.

auto loader = tvg::Loader::gen();

//Animation provides the general functions to control frames.
auto animation = unique_ptr<Animation*>(loader->load("lottie.json" ...));
auto animation = unique_ptr<Animation*>(loader->load("rive.riv" ...));

//User can cast to the specific animation if they want to use the specific features of lottie / rive.
auto lottie = unique_ptr<LottieAnimation*>(loader->load("lottie.json" ...));
auto rive = unique_ptr<RiveAnimation*>(loader->load("lottie.riv" ...));

auto svg = unique_ptr<Picture*>(loader->load(".svg", ...));
auto tvg = unique_ptr<Picture*>(loader->load(".tvg", ...));
...

class Animation inherits Picture // General APIs for animation. Allow inheritance not like other tvg classes.
class LottieAnimation : public Animation   // Have the specific features of Lottie
class RiveAnimation : public Animation // Have the specific features of Rive

thorvg/src/loaders (or extensions ?)/lottie/thorvg_lottie.h   //resides LottieAnimation class (extension apis)
thorvg/src/loaders (or extensions ?)/rive/thorvg_rive.h       //resides RiveAnimation class (extension apis)

2. class Animation inherits the Picture
class Animation inherits Picture;
Animation or AnimatedPicture  or MotionPicture or ...

**Comment by JSUYA** [comment]
I agree too with picture become complexity.
and I am not against providing a Loader.
There are just a few things to be concerned about.

```auto svg = unique_ptr<Picture*>(loader->load(".svg", ...));```
If the image is changed here, the picture already extracted from the loader cannot be used.
The properties of the newly obtained picture will have to be set again(size, transform, etc..).

If we need to use a Loader, I think we can provide a picture->load() function that takes a Loader as an argument.
```cpp
auto loader = tvg::Loader::gen();
loader->load(".svg", ...) 
auto picture = tvg::Picture::gen();
picture->load(loader);
//////////////
auto loader = tvg::Loader::gen();
loader->load("lottie.json" ...)
auto animation = tvg::LottieAnimation::gen();
animation->load(loader)
```

**Comment by JSUYA** [comment]
Brief (my) plan

- Create a temporary json loader in the current loader
- Content loading based on first frame
- Make parser code (with rapidjson)
- Make tvg object tree(like SvgSceneBuilder) and list up features for lottie animation(blending, masking, matte...)
- Designing the animator interface
- Move to animator's json loader.

**Comment by JSUYA** [comment]
@hermet  How about this way?

Lottie case
```
auto lottie = tvg::Animation<Lottie>::gen();
lottie->load("abc.json");

auto totalFrame = lottie->totalFrame();
auto picture = lottie->picture(100, 100/* size w x h */, 10 /*frame*/);
//or
lottie->size(100, 100);
lottie->frame(10);
auto picture = lottie->picture();

canvas->push(move(picture))
```

Rive case
```
auto rive = tvg::Animation<Rive>::gen();
rive->load("abc.riv");
auto totalFrame = rive->totalFrame();
auto picture = rive->picture(100, 100, 10 /*frame*/);
canvas->push(move(picture))
```

**Comment by hermet** [comment]
```
class TVG_EXPORT Lottie final : public Picture, public Animation

lottie = Lottie::gen();
lottie->load("xx.json"); -----------------------------[LottieLoader]
lottie->frame(iframe);

//Is-a
auto lottiePtr = lottie.get();

-> lottie->size(100, 100);
-> canvas->push(move(lottie));
```

**Comment by hermet** [comment]
Two candidates for json parsers: 
1. https://github.com/simdjson/simdjson
2. https://github.com/Tencent/rapidjson

**Comment by JSUYA** [comment]
wow simdjson looks super fast...

**Comment by hermet** [comment]
Current suggestion of the usage:

```
//Animation Controller
auto animation = tvg::Animation::gen();  

//Get the designated picture of the animation, set basic info.
auto picture = animation->picture();
picture->load(EXAMPLE_DIR"/sample.json");
picture->size(width, height);

//Push the picture to a canvas
canvas->push(unique_ptr<tvg::Picture>(picture));
...

//Update the animation frame, every frame
animation->frame(curFrameNo);
...
//After then, update canvas
canvas->update(animation->picture());
...
//Draw Canvas & Sync
canvas->draw();
canvas->sync();
```

**Comment by hermet** [comment]
https://github.com/ibireme/yyjson

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/assets/3711518/2a8b74dd-faaf-4d4b-8848-f778b08acbd1

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/assets/3711518/b08ca2b1-a9e7-4e5b-9cff-7ed9d9a14e01

**Comment by hermet** [comment]
Lottie feature has been applied though there are some advanced properties are missing, 
We can incrementally enhance them from now.
