### ISSUE TITLE
Create thorvg loader and editor

### ISSUE THREAD

**Issue by mmaciola** [thorvg/thorvg#718]
I am thinking about a debugging software that could load file of formats supported by thorvg (mainly I mean tvg, svg and, if supported in future, json), display it and show list of elements. Allow hiding some elements, display paint’s composite as normal and highlight the element if hovered with mouse cursor.
I think about making it system and efl independent (browser app and wasm?).
Please write your comments

**Comment by hermet** [comment]
Sure, that's a good idea. Thorvg Viewer is the good place to support it, the thing is the manpower to do it. Probably, we can plan it for a next year goal?

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg.viewer

**Comment by steprun** [comment]
> https://github.com/Samsung/thorvg.viewer

Image file can not drag to viewer on google chrome. version is 95.0.4638.54

**Comment by mmaciola** [comment]
> > https://github.com/Samsung/thorvg.viewer
> 
> Image file can not drag to viewer on google chrome. version is 95.0.4638.54

I will test it with this particular chrome version on monday. Could you give me the below informations:
What operating system? Does it occur for a particular file or for all files you tested? Does this file load when you select it using "Add files" button?
Is there something printed in the developer console (Right click anywhere on the page -> Inspect -> Press "esc" -> click Console tab)?

**Comment by steprun** [comment]
> > > https://github.com/Samsung/thorvg.viewer
> > 
> > 
> > Image file can not drag to viewer on google chrome. version is 95.0.4638.54
> 
> I will test it with this particular chrome version on monday. Could you give me the below informations: What operating system? Does it occur for a particular file or for all files you tested? Does this file load when you select it using "Add files" button? Is there something printed in the developer console (Right click anywhere on the page -> Inspect -> Press "esc" -> click Console tab)?

Win 10 21H1 Ver 19043.1348
![1638153199(1)](https://user-images.githubusercontent.com/8555048/143799680-ad5ccd48-5cfb-432f-8cd8-1bf9735c85b7.png)
