### ISSUE TITLE
patterns are not supported

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#940]
@fire mentioned the file in issue #820 :
https://github.com/V-Sekai/godot-hop-dance/blob/main/hop_spin_dance/uiux/mockups/mockups_with_raster/VRM%20Viewer%20Screen%20Animate.svg

**Comment by hermet** [comment]
@mgrudzinska the link is no more valid. when a new issue is come, let's recreate it.

**Comment by mgrudzinska** [comment]
this issue is already mention in https://github.com/thorvg/thorvg/issues/1319#issuecomment-1418302861
