### ISSUE TITLE
Tests failing on Windows using MSVC

### ISSUE THREAD

**Issue by projectitis** [thorvg/thorvg#957]
Hi all,

The new static png and jpg loaders are compiling perfectly on Windows x64 MSVC.
However when I run the tests, I get 4 errors.
````
Summary:
    ThorVG version:        0.5.99
    Build Type:            release
    Prefix:                c:/
    SIMD Instruction:      none
    Raster Engine (SW):    true
    Raster Engine (GL):    false
    Loader (TVG):          true
    Loader (SVG):          true
    Loader (PNG):          true
    Loader (JPG):          true
    Saver (TVG):           true
    CAPI Binding:          false
    Log Message:           true
    Tests:                 true
    Examples:              false
    Tool (Svg2Tvg):        false
    Tool (Svg2Png):        false

User defined options
    backend        : ninja
    buildtype      : release
    debug          : false
    default_library: static
    loaders        : all
    log            : true
    savers         : tvg
    tests          : true

../test/testPicture.cpp(139): FAILED:
  REQUIRE( picture->load(data, size, "", false) == Result::Success )
with expansion:
  5 == 0

../test/testPicture.cpp(183): FAILED:
  REQUIRE( picture->load(data, size, "", false) == Result::Success )
with expansion:
  5 == 0

../test/testScene.cpp(68): FAILED:
  REQUIRE( scene->reserve(-1) == Result::FailedAllocation )
with expansion:
  0 == 3

../test/testSwCanvasBase.cpp(43): FAILED:
  REQUIRE( canvas->reserve(-1) == Result::FailedAllocation )
with expansion:
  0 == 3
````

**Comment by projectitis** [comment]
I have tried with the latest code. Just one test error now, but it's a new one:
````
../test/testPicture.cpp(358): FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
````
Note that last time I got a `SIGSEGV` in ThorVG it was because a large array was overflowing the stack.

**Comment by JSUYA** [comment]
> I have tried with the latest code. Just one test error now, but it's a new one:
> 
> ```
> ../test/testPicture.cpp(358): FAILED:
>   {Unknown expression after the reported line}
> due to a fatal error condition:
>   SIGSEGV - Segmentation violation signal
> ```
> 
> Note that last time I got a `SIGSEGV` in ThorVG it was because a large array was overflowing the stack.
> 
> Edit: These are my options:
> 
> ```
> Summary:
>     ThorVG version:        0.5.99
>     Build Type:            release
>     Prefix:                c:/
>     SIMD Instruction:      none
>     Raster Engine (SW):    true
>     Raster Engine (GL):    false
>     Loader (TVG):          true
>     Loader (SVG):          true
>     Loader (PNG):          true
>     Loader (JPG):          true
>     Saver (TVG):           true
>     CAPI Binding:          false
>     Log Message:           true
>     Tests:                 true
>     Examples:              false
>     Tool (Svg2Tvg):        false
>     Tool (Svg2Png):        false
> 
> User defined options:
>     backend        : ninja
>     buildtype      : release
>     debug          : false
>     default_library: static
>     loaders        : all
>     log            : true
>     savers         : tvg
>     tests          : true
> ```

Hi, I fixed the code relate to this test failure.
https://github.com/Samsung/thorvg/pull/974

Could you please check again?

**Comment by projectitis** [comment]
@JSUYA I just tried it now. Just one error now.
[testlog.txt](https://github.com/Samsung/thorvg/files/7458308/testlog.txt)
````
../test/testPicture.cpp(358): FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
````

**Comment by JSUYA** [comment]
> @JSUYA I just tried it now. Still the same error - unfortunately it did not resolve the issue. [testlog.txt](https://github.com/Samsung/thorvg/files/7458308/testlog.txt)
> 
> ```
> ../test/testPicture.cpp(358): FAILED:
>   {Unknown expression after the reported line}
> due to a fatal error condition:
>   SIGSEGV - Segmentation violation signal
> ```
> 
> I can confirm that `testPicture.cpp` has the change you made (`delete[] buffer;`).

oh i see. i will check again. thank you for check.

**Comment by JSUYA** [comment]
Hi @projectitis 
Sorry, I couldn't reproduce this test fail. In log file, Pass and fail occurred at the same time.
So we did a memory leak check(valgrind) related to the test and modified some code. https://github.com/Samsung/thorvg/issues/995

So.. Could you please check again?

**Comment by projectitis** [comment]
@JSUYA All tests pass!

```
All tests passed (1137 assertions in 73 test cases)
------------------------------------------------------------------------------
Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

Thank you for all your efforts :)

**Comment by projectitis** [comment]
Very sorry - I spoke too soon. I have been able to reproduce it.

These are my options for all tests passing ok:
```
meson configure -Dbuildtype=release -Ddebug=false -Dloaders=all -Dlog=true -Dsavers=tvg -Dtests=true
```

But if I do this as well (also the options above) then the `testPicture` test fails:
```
-Ddefault_library=static
```

And if I do this the tests fail by timeout after 30 seconds.
```
-Ddefault_library=static -Dstatic=true
```

**Comment by hermet** [comment]
Current situation:

![image](https://user-images.githubusercontent.com/3711518/233589371-530a9fd6-c35a-45d7-b9fc-6409346ae115.png)

**Comment by hermet** [comment]
@mgrudzinska I'm appreciated if you help this issue.

**Comment by vtorri** [comment]
i think that i have a similar error with msys2+mingw-w64

**Comment by mgrudzinska** [comment]
@hermet presented log is correct, no <svg/> tag comes from searching the type of a loader:
```REQUIRE(picture->load(data, size, "", false) == Result::Success);```

I believe that solving #1380 will solve also this problem. I'm working on #1380

**Comment by mgrudzinska** [comment]
@hermet @vtorri @projectitis after #1407 is applied this should be solved

**Comment by hermet** [comment]
@mgrudzinska confirmed, good job.
